### PR TITLE
fix: enable time unit functions for interpreter

### LINKED ISSUE #7512: Timestamp arithmetic functions do not work with pull query interpreter
**Describe the bug**
The following query fails:
```
SELECT  TIMESTAMPADD(MINUTES, 15,  TS) FROM TableA WHERE DUMMY_FIELD=1;
Unexpected error generating code for expression: TIMESTAMPADD(MINUTES, 15, 'k')
```
This is because time units (MINUTE, SECOND etc) are not implemented in TermCompiler.java yet: https://github.com/confluentinc/ksql/blob/0aeb57f41f6df58fb4788ea1d12ea6a9b8fc5191/ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/TermCompiler.java#L297

The error message is also confusing, since it doesn't actually print out what the error is https://github.com/confluentinc/ksql/blob/0aeb57f41f6df58fb4788ea1d12ea6a9b8fc5191/ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/InterpretedExpressionFactory.java#L69

### PR DESCRIPTION
**Pull request by jzaralim**
### Description 
Fixes #7512. Implements `visitIntervalUnit ` in `TermCompiler`.

### Testing done 
Added a unit test

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/terms/LiteralTerms.java [hunk 1]
```diff
@@ -209,4 +214,23 @@ public SqlType getSqlType() {
...
+    }
+
+    @Override
+    public Object getValue(final TermEvaluationContext context) {
+      return value;
+    }
+
+    @Override
+    public SqlType getSqlType() {
+      return null;
```
Comment (AlanConfluent) [inline ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/terms/LiteralTerms.java:233]: Does this not have a SqlType?  It doesn't seem like it since it's kind of a modifier rather than a data value, but just checking

**Review by AlanConfluent — APPROVED** [review]
Looks good.  You can also add to `ExpressionEvaluatorParityTest` if you want to ensure they both return the same results for same expressions.

File: ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/terms/LiteralTerms.java (hunk 1 above)
Comment (jzaralim) [reply ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/terms/LiteralTerms.java:233]: It does not. The only place it can exist is in a function (parser would reject everything else).
