### PR TITLE
fix: do not overwrite schemas from a CREATE STREAM/TABLE

### LINKED ISSUE #5553: KSQL should not register a schema when it's only consuming from a topic
**Describe the bug**
When creating a stream over an existing topic with value_format=avro, ksql will register a dynamically generated schema. When using producers that don't generate the schema, this can cause it to attempt to use a schema that is incompatible with our data model.

**To Reproduce**
Steps to reproduce the behavior, include:
1. version: confluentinc/ksqldb-server:0.9.0
3. ksql: 
```
CREATE STREAM appliedresearch_traffic_incident_updates_stream 
    (incident STRUCT<
        incidentId varchar, 
        cleared boolean, 
        confirmed boolean,
        details varchar,
        latitude double,
        longitude double,
        location varchar,
        roadwayDirection varchar, 
        roadwayName varchar,
        `timestamp` varchar,
        `type` varchar>)
WITH (
    kafka_topic = 'appliedresearch_traffic_incident_updates',
    value_format = 'avro'
);
```

**Expected behavior**
There should be no reason for ksql to register a schema here since it is only a consumer of the topic and would be using whatever schema was used to serialize the data.

**Actual behaviour**
It generates the following schema

```
{
  "connect.name": "io.confluent.ksql.avro_schemas.KsqlDataSourceSchema",
  "fields": [
    {
      "default": null,
      "name": "INCIDENT",
      "type": [
        "null",
        {
          "connect.name": "io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_INCIDENT",
          "fields": [
            {
              "default": null,
              "name": "INCIDENTID",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "default": null,
              "name": "CLEARED",
              "type": [
                "null",
                "boolean"
              ]
            },
            {
              "default": null,
              "name": "CONFIRMED",
              "type": [
                "null",
                "boolean"
              ]
            },
            {
              "default": null,
              "name": "DETAILS",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "default": null,
              "name": "LATITUDE",
              "type": [
                "null",
                "double"
              ]
            },
            {
              "default": null,
              "name": "LONGITUDE",
              "type": [
                "null",
                "double"
              ]
            },
            {
              "default": null,
              "name": "LOCATION",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "default": null,
              "name": "ROADWAYDIRECTION",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "default": null,
              "name": "ROADWAYNAME",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "default": null,
              "name": "timestamp",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "default": null,
              "name": "type",
              "type": [
                "null",
                "string"
              ]
            }
          ],
          "name": "KsqlDataSourceSchema_INCIDENT",
          "type": "record"
        }
      ]
    }
  ],
  "name": "KsqlDataSourceSchema",
  "namespace": "io.confluent.ksql.avro_schemas",
  "type": "record"
}
```

**Additional context**
The auto generated schema is never used in any way because we produce to this topic ourselves. KSQL is only consuming from it. But this can break a producer under some use cases where the producer is not in control of the schema but rather using the latest version from the schema registry. There is really no value to KSQL generating this schema at all. It should only generate a schema for a topic it is writing to.

### PR DESCRIPTION
**Pull request by agavra**
### Description 

fixes #5553 

This commit makes sure that `C*` statements do not overwrite existing schemas in schema registry and instead only check compatibility with a declared schema, if a declared schema is present.

**NOTE**: if you `INSERT INTO` a stream, all bets are off (i.e. another schema will be registered under the schema value, but that is not a regression as this is a serializer-specific behavior) 

### Testing done 

Unit tests, and manual testing (registered the same source with a subset schema and confirmed there's only one version in schema registry)

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by apurvam** [comment]
Thanks almog. Do we know when the regression was introduced? Ie. which version of community ksqlDB?

**Comment by agavra** [comment]
@apurvam yes, the regression was introduced by https://github.com/confluentinc/ksql/pull/4717 which made it into 0.8.0

File: ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java [hunk 1]
```diff
@@ -96,7 +99,8 @@ private void registerForCreateAs(final ConfiguredStatement<? extends CreateAsSel
         queryMetadata.getResultTopic().getKafkaTopicName(),
         queryMetadata.getResultTopic().getValueFormat().getFormatInfo(),
         cas.getConfig(),
-        cas.getStatementText()
+        cas.getStatementText(),
+        true
```
Comment (vpapavas) [inline ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java:103]: Just to make sure, in which case to we want to overwrite existing schemas?

Comment (agavra) [reply ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java:103]: we want to overwrite existing schemas in the case of `CREATE * AS SELECT`
