### PR TITLE
Fix the bug for null check in comparison expression code gen,

### LINKED ISSUE #1546: Null check for comparison fails for negative values
When having a comparison expression with a negative literal, the null check in code gen fails for negative values:
`select orderunits from orders where orderunits > -9.9;`
Generates wrong code.

### PR DESCRIPTION
**Pull request by hjafarpour**
### Description 
This patch fixes #1546 

### Testing done 
_Describe the testing stategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java [hunk 1]
```diff
@@ -131,4 +131,15 @@ public void shouldPostfixFunctionInstancesWithUniqueId() {
             + "((String) CONCAT_2.evaluate(\"-\","
             + " ((String) SUBSTRING_3.evaluate(TEST1_COL1, Integer.parseInt(\"4\"), Integer.parseInt(\"5\")))))))"));
   }
+
+  @Test
+  public void shouldGenerateCorrectCodeForComparisonWithNegativeNumbers() {
```
Comment (apurvam) [inline ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java]: We should add a query translation test for this.

**Comment by apurvam** [comment]
Is this a regression or was this always broken?

**Comment by hjafarpour** [comment]
@apurvam wanna take another look?
