### PR TITLE
Fix Joining on ROWKEY

### LINKED ISSUE #2470: join should preserve key column for result stream
Take the following series of statements:

```
create stream s1 (k string, v string) with (kafka_topic='s1', value_format='json', key='k');
create table t1 (k string, v string) with kafka_topic='t1', value_format='json', key='k');
create table t2 (k string, v string) with (kafka_topic='t2', value_format='json', key='k');
create stream s1t1 as select s1.k, s1.v, t1.v from s1 join t1 on s1.k = t1.k;
create stream s1t1t2 as select s1_k, s1_v, t1_v, t2.v from s1t1 join t2 on s1t1.s1_k=t2.k;
```

The first join has no repartition:
```
ksql> explain CSAS_S1T1_0;

ID                   : CSAS_S1T1_0
SQL                  : create stream s1t1 as select s1.k, s1.v, t1.v from s1 join t1 on s1.k = t1.k;

 Field   | Type
-------------------------------------
 ROWTIME | BIGINT           (system)
 ROWKEY  | VARCHAR(STRING)  (system)
 S1_K    | VARCHAR(STRING)
 S1_V    | VARCHAR(STRING)
 T1_V    | VARCHAR(STRING)
-------------------------------------

Sources that this query reads from:
-----------------------------------
T1
S1

For source description please run: DESCRIBE [EXTENDED] <SourceId>

Sinks that this query writes to:
-----------------------------------
S1T1

For sink description please run: DESCRIBE [EXTENDED] <SinkId>

Execution plan
--------------
 > [ SINK ] | Schema: [S1_K : VARCHAR, S1_V : VARCHAR, T1_V : VARCHAR] | Logger: CSAS_S1T1_0.S1T1
		 > [ PROJECT ] | Schema: [S1_K : VARCHAR, S1_V : VARCHAR, T1_V : VARCHAR] | Logger: CSAS_S1T1_0.Project
				 > [ JOIN ] | Schema: [S1.ROWTIME : BIGINT, S1.ROWKEY : VARCHAR, S1.K : VARCHAR, S1.V : VARCHAR, T1.ROWTIME : BIGINT, T1.ROWKEY : VARCHAR, T1.K : VARCHAR, T1.V : VARCHAR] | Logger: CSAS_S1T1_0.Join
						 > [ SOURCE ] | Schema: [ROWTIME : BIGINT, ROWKEY : VARCHAR, K : VARCHAR, V : VARCHAR] | Logger: CSAS_S1T1_0.KafkaTopic_Left
						 > [ SOURCE ] | Schema: [ROWTIME : BIGINT, ROWKEY : VARCHAR, K : VARCHAR, V : VARCHAR] | Logger: CSAS_S1T1_0.KafkaTopic_Right


Processing topology
-------------------
Topologies:
   Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000005 (topics: [s1])
      --> KSTREAM-MAPVALUES-0000000006
    Processor: KSTREAM-MAPVALUES-0000000006 (stores: [])
      --> KSTREAM-TRANSFORMVALUES-0000000007
      <-- KSTREAM-SOURCE-0000000005
    Source: KSTREAM-SOURCE-0000000000 (topics: [t1])
      --> KSTREAM-MAPVALUES-0000000001
    Processor: KSTREAM-TRANSFORMVALUES-0000000007 (stores: [])
      --> KSTREAM-JOIN-0000000008
      <-- KSTREAM-MAPVALUES-0000000006
    Processor: KSTREAM-JOIN-0000000008 (stores: [KafkaTopic_Right-reduce])
      --> KSTREAM-MAPVALUES-0000000009
      <-- KSTREAM-TRANSFORMVALUES-0000000007
    Processor: KSTREAM-MAPVALUES-0000000001 (stores: [])
      --> KSTREAM-TRANSFORMVALUES-0000000002
      <-- KSTREAM-SOURCE-0000000000
    Processor: KSTREAM-MAPVALUES-0000000009 (stores: [])
      --> KSTREAM-MAPVALUES-0000000010
      <-- KSTREAM-JOIN-0000000008
    Processor: KSTREAM-TRANSFORMVALUES-0000000002 (stores: [])
      --> KSTREAM-MAPVALUES-0000000003
      <-- KSTREAM-MAPVALUES-0000000001
    Processor: KSTREAM-MAPVALUES-0000000003 (stores: [])
      --> KSTREAM-AGGREGATE-0000000004
      <-- KSTREAM-TRANSFORMVALUES-0000000002
    Processor: KSTREAM-MAPVALUES-0000000010 (stores: [])
      --> KSTREAM-SINK-0000000011
      <-- KSTREAM-MAPVALUES-0000000009
    Processor: KSTREAM-AGGREGATE-0000000004 (stores: [KafkaTopic_Right-reduce])
      --> none
      <-- KSTREAM-MAPVALUES-0000000003
    Sink: KSTREAM-SINK-0000000011 (topic: S1T1)
      <-- KSTREAM-MAPVALUES-0000000010
```

The second one does:
```
ksql> explain CSAS_S1T1T2_1;

ID                   : CSAS_S1T1T2_1
SQL                  : create stream s1t1t2 as select s1_k, s1_v, t1_v, t2.v from s1t1 join t2 on s1t1.s1_k=t2.k;

 Field   | Type
-------------------------------------
 ROWTIME | BIGINT           (system)
 ROWKEY  | VARCHAR(STRING)  (system)
 S1_K    | VARCHAR(STRING)
 S1_V    | VARCHAR(STRING)
 T1_V    | VARCHAR(STRING)
 V       | VARCHAR(STRING)
-------------------------------------

Sources that this query reads from:
-----------------------------------
S1T1
T2

For source description please run: DESCRIBE [EXTENDED] <SourceId>

Sinks that this query writes to:
-----------------------------------
S1T1T2

For sink description please run: DESCRIBE [EXTENDED] <SinkId>

Execution plan
--------------
 > [ SINK ] | Schema: [S1_K : VARCHAR, S1_V : VARCHAR, T1_V : VARCHAR, V : VARCHAR] | Logger: CSAS_S1T1T2_1.S1T1T2
		 > [ PROJECT ] | Schema: [S1_K : VARCHAR, S1_V : VARCHAR, T1_V : VARCHAR, V : VARCHAR] | Logger: CSAS_S1T1T2_1.Project
				 > [ JOIN ] | Schema: [S1T1.ROWTIME : BIGINT, S1T1.ROWKEY : VARCHAR, S1T1.S1_K : VARCHAR, S1T1.S1_V : VARCHAR, S1T1.T1_V : VARCHAR, T2.ROWTIME : BIGINT, T2.ROWKEY : VARCHAR, T2.K : VARCHAR, T2.V : VARCHAR] | Logger: CSAS_S1T1T2_1.Join
						 > [ REKEY ] | Schema: [ROWTIME : BIGINT, ROWKEY : VARCHAR, S1_K : VARCHAR, S1_V : VARCHAR, T1_V : VARCHAR] | Logger: CSAS_S1T1T2_1.Join
								 > [ SOURCE ] | Schema: [ROWTIME : BIGINT, ROWKEY : VARCHAR, S1_K : VARCHAR, S1_V : VARCHAR, T1_V : VARCHAR] | Logger: CSAS_S1T1T2_1.KafkaTopic_Left
						 > [ SOURCE ] | Schema: [ROWTIME : BIGINT, ROWKEY : VARCHAR, K : VARCHAR, V : VARCHAR] | Logger: CSAS_S1T1T2_1.KafkaTopic_Right


Processing topology
-------------------
Topologies:
   Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000000 (topics: [t2])
      --> KSTREAM-MAPVALUES-0000000001
    Source: KSTREAM-SOURCE-0000000013 (topics: [Join-repartition])
      --> KSTREAM-JOIN-0000000014
    Processor: KSTREAM-JOIN-0000000014 (stores: [KafkaTopic_Right-reduce])
      --> KSTREAM-MAPVALUES-0000000015
      <-- KSTREAM-SOURCE-0000000013
    Processor: KSTREAM-MAPVALUES-0000000001 (stores: [])
      --> KSTREAM-TRANSFORMVALUES-0000000002
      <-- KSTREAM-SOURCE-0000000000
    Processor: KSTREAM-MAPVALUES-0000000015 (stores: [])
      --> KSTREAM-MAPVALUES-0000000016
      <-- KSTREAM-JOIN-0000000014
    Processor: KSTREAM-TRANSFORMVALUES-0000000002 (stores: [])
      --> KSTREAM-MAPVALUES-0000000003
      <-- KSTREAM-MAPVALUES-0000000001
    Processor: KSTREAM-MAPVALUES-0000000003 (stores: [])
      --> KSTREAM-AGGREGATE-0000000004
      <-- KSTREAM-TRANSFORMVALUES-0000000002
    Processor: KSTREAM-MAPVALUES-0000000016 (stores: [])
      --> KSTREAM-SINK-0000000017
      <-- KSTREAM-MAPVALUES-0000000015
    Processor: KSTREAM-AGGREGATE-0000000004 (stores: [KafkaTopic_Right-reduce])
      --> none
      <-- KSTREAM-MAPVALUES-0000000003
    Sink: KSTREAM-SINK-0000000017 (topic: S1T1T2)
      <-- KSTREAM-MAPVALUES-0000000016

  Sub-topology: 1
    Source: KSTREAM-SOURCE-0000000005 (topics: [S1T1])
      --> KSTREAM-MAPVALUES-0000000006
    Processor: KSTREAM-MAPVALUES-0000000006 (stores: [])
      --> KSTREAM-TRANSFORMVALUES-0000000007
      <-- KSTREAM-SOURCE-0000000005
    Processor: KSTREAM-TRANSFORMVALUES-0000000007 (stores: [])
      --> KSTREAM-FILTER-0000000008
      <-- KSTREAM-MAPVALUES-0000000006
    Processor: KSTREAM-FILTER-0000000008 (stores: [])
      --> KSTREAM-KEY-SELECT-0000000009
      <-- KSTREAM-TRANSFORMVALUES-0000000007
    Processor: KSTREAM-KEY-SELECT-0000000009 (stores: [])
      --> KSTREAM-MAPVALUES-0000000010
      <-- KSTREAM-FILTER-0000000008
    Processor: KSTREAM-MAPVALUES-0000000010 (stores: [])
      --> KSTREAM-FILTER-0000000012
      <-- KSTREAM-KEY-SELECT-0000000009
    Processor: KSTREAM-FILTER-0000000012 (stores: [])
      --> KSTREAM-SINK-0000000011
      <-- KSTREAM-MAPVALUES-0000000010
    Sink: KSTREAM-SINK-0000000011 (topic: Join-repartition)
      <-- KSTREAM-FILTER-0000000012
```

The second join doesn't need to repartition though, since the key has not changed and is the join key.

Note that this can be avoided by an explicit `partition by`:

```
create stream s2 (k string, v string) with (kafka_topic='s2', value_format='json', key='k');
create stream s2t1 as select s2.k, s2.v, t1.v from s2 join t1 on s2.k = t1.k partition by s2_k;
create stream s2t1t2 as select s2_k, s2_v, t1_v, t2.v from s2t1 join t2 on s2t1.s2_k=t2.k;
explain CSAS_S2T1T2_3;

ID                   : CSAS_S2T1T2_3
SQL                  : create stream s2t1t2 as select s2_k, s2_v, t1_v, t2.v from s2t1 join t2 on s2t1.s2_k=t2.k;

 Field   | Type
-------------------------------------
 ROWTIME | BIGINT           (system)
 ROWKEY  | VARCHAR(STRING)  (system)
 S2_K    | VARCHAR(STRING)
 S2_V    | VARCHAR(STRING)
 T1_V    | VARCHAR(STRING)
 V       | VARCHAR(STRING)
-------------------------------------

Sources that this query reads from:
-----------------------------------
S2T1
T2

For source description please run: DESCRIBE [EXTENDED] <SourceId>

Sinks that this query writes to:
-----------------------------------
S2T1T2

For sink description please run: DESCRIBE [EXTENDED] <SinkId>

Execution plan
--------------
 > [ SINK ] | Schema: [S2_K : VARCHAR, S2_V : VARCHAR, T1_V : VARCHAR, V : VARCHAR] | Logger: CSAS_S2T1T2_3.S2T1T2
		 > [ PROJECT ] | Schema: [S2_K : VARCHAR, S2_V : VARCHAR, T1_V : VARCHAR, V : VARCHAR] | Logger: CSAS_S2T1T2_3.Project
				 > [ JOIN ] | Schema: [S2T1.ROWTIME : BIGINT, S2T1.ROWKEY : VARCHAR, S2T1.S2_K : VARCHAR, S2T1.S2_V : VARCHAR, S2T1.T1_V : VARCHAR, T2.ROWTIME : BIGINT, T2.ROWKEY : VARCHAR, T2.K : VARCHAR, T2.V : VARCHAR] | Logger: CSAS_S2T1T2_3.Join
						 > [ SOURCE ] | Schema: [ROWTIME : BIGINT, ROWKEY : VARCHAR, S2_K : VARCHAR, S2_V : VARCHAR, T1_V : VARCHAR] | Logger: CSAS_S2T1T2_3.KafkaTopic_Left
						 > [ SOURCE ] | Schema: [ROWTIME : BIGINT, ROWKEY : VARCHAR, K : VARCHAR, V : VARCHAR] | Logger: CSAS_S2T1T2_3.KafkaTopic_Right


Processing topology
-------------------
Topologies:
   Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000005 (topics: [S2T1])
      --> KSTREAM-MAPVALUES-0000000006
    Processor: KSTREAM-MAPVALUES-0000000006 (stores: [])
      --> KSTREAM-TRANSFORMVALUES-0000000007
      <-- KSTREAM-SOURCE-0000000005
    Source: KSTREAM-SOURCE-0000000000 (topics: [t2])
      --> KSTREAM-MAPVALUES-0000000001
    Processor: KSTREAM-TRANSFORMVALUES-0000000007 (stores: [])
      --> KSTREAM-JOIN-0000000008
      <-- KSTREAM-MAPVALUES-0000000006
    Processor: KSTREAM-JOIN-0000000008 (stores: [KafkaTopic_Right-reduce])
      --> KSTREAM-MAPVALUES-0000000009
      <-- KSTREAM-TRANSFORMVALUES-0000000007
    Processor: KSTREAM-MAPVALUES-0000000001 (stores: [])
      --> KSTREAM-TRANSFORMVALUES-0000000002
      <-- KSTREAM-SOURCE-0000000000
    Processor: KSTREAM-MAPVALUES-0000000009 (stores: [])
      --> KSTREAM-MAPVALUES-0000000010
      <-- KSTREAM-JOIN-0000000008
    Processor: KSTREAM-TRANSFORMVALUES-0000000002 (stores: [])
      --> KSTREAM-MAPVALUES-0000000003
      <-- KSTREAM-MAPVALUES-0000000001
    Processor: KSTREAM-MAPVALUES-0000000003 (stores: [])
      --> KSTREAM-AGGREGATE-0000000004
      <-- KSTREAM-TRANSFORMVALUES-0000000002
    Processor: KSTREAM-MAPVALUES-0000000010 (stores: [])
      --> KSTREAM-SINK-0000000011
      <-- KSTREAM-MAPVALUES-0000000009
    Processor: KSTREAM-AGGREGATE-0000000004 (stores: [KafkaTopic_Right-reduce])
      --> none
      <-- KSTREAM-MAPVALUES-0000000003
    Sink: KSTREAM-SINK-0000000011 (topic: S2T1T2)
      <-- KSTREAM-MAPVALUES-0000000010
```

The underlying cause is that StructuredDataOutputNode sets the key field to the fully qualified source field name (s1.k), while the actual schema uses the projected names (s1_k).

### LINKED ISSUE #2525: KSQL partitions by column in source when there is a name collision with a column in the sink
Setup:

```
ksql> create stream TEST_1 (a varchar, b varchar)  \
  WITH (KAFKA_TOPIC='TEST_PART_1', value_format='delimited', \
  key='a');

 Message
----------------
 Stream created
----------------
ksql> create stream TEST_2 WITH (KAFKA_TOPIC='TEST_PART_2', \
  value_format='delimited') as select a + '_NEW' as a, b \
  from TEST_1 partition by a;

 Message
----------------------------
 Stream created and running
----------------------------
```

Produce to `TEST_PART_1`:
```
$ kafkacat -b localhost:9092 -t TEST_PART_1 -P -K:
C:C,D
E:E,F
```

See that the key in stream `TEST_2` is the original value from `TEST_1`, not the modified value:

```
ksql> create stream TEST_2 WITH (KAFKA_TOPIC='TEST_PART_2', \
  value_format='delimited') as select a + '_NEW' as a, b \
  from TEST_1 partition by a;

 Message
----------------------------
 Stream created and running
----------------------------
ksql> select * from TEST_2;
1551824886814 | C | C_NEW | D
1551824930017 | E | E_NEW | F
```

As we can see, the query `TEST_2` is picking the key column `a` from the source, rather than the modified key column with the same name `a` from the `TEST_2` select statement.

If we modify the name of `a` in `TEST_2` to `a_new`, and partition by `a_new`, then it behaves as expected:

```
ksql> create stream TEST_3 WITH (KAFKA_TOPIC='TEST_PART_3', \
   value_format='delimited') as select a + '_NEW' as a_new, b \
   from TEST_1 partition by a_new;

 Message
----------------------------
 Stream created and running
----------------------------
ksql> select * from TEST_3;
1551825264867 | K_NEW | K_NEW | L
```
That produces the correct key for the input:

```
$ kafkacat -b localhost:9092 -t TEST_PART_1 -P -K:
K:K,L
```

This is odd default behavior. We should always be choosing the key from the columns in the sink rather than the source when there are name collisions.

### LINKED ISSUE #2636: Fix issues with currently handling of `keyField` of sources.
Current version, (v5.2.0), of KSQL can set the `keyField` of sources created from `CREATE STREAM AS SELECT...` and `CREATE TABLE AS SELECT...` statements.

The issues fail into one of a couple of categories:

1. key field in metastore for OUTPUT contains internal column names e.g. 'KSQL_INTERNAL_COL0' or 'CAST(KSQL_INTERNAL_COL_0 AS INTEGER)'
   - fix implications:
      - fixing would mean downstream queries might avoid an unnecessary repartition step (fix is NOT backwards compatible by default)

1. key field in metastore for OUTPUT either matches INPUT or contains internal column names, but should be null
    - fix implications: 
        - fixing would not affect downstream queries as the key field is not available in the value schema either before or after the fix
      (fix IS backwards compatible by default)

1. key field in metastore has wrong type (STRING)
    - fix implications: 
        - Currently, OUTPUT can be joined to sources that have a matching (incorrect) key type, which should not be possible.
      (fix is NOT backwards compatible by default, though could argue maintaining backwards compatibility here is wrong)
       - Currently, OUTPUT would fail to join to anything with matching (correct) key type, which should be possible.
     (fix IS backwards compatible)

1. key field in metastore has not picked up the aliasing of the key field in the project, i.e. key field matches source, but should be alias
    - fix implications:
       - If the projection has no fields that match the source key field then the implications are the same as issue #1
       - If the projection has a field that duplicates the name of the source key field then additionally:
          - Downstream queries that PARTITION BY or GROUP BY the duplicate field name would not work correctly as no repartition would happen
      (fix is backwards compatible as it fixes broken functionality)
           - Downstream queries that PARTITION BY or GROUP BY the new alias would stop introducing unnecessary repartition step
      (fix is NOT backwards compatible by default)

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 

Fixes #2636
Fixes #2525
Fixes #2470

This continues the work to clean up key field handling in the existing code.

This PR addresses issues when joining by ROWKEY. 
 - Previous versions of KSQL haven't handled this too well as they introduce unnecessary repartition steps.  This is now resolved.
 - Plus there was an outstanding issue from earlier work where the 'new' key field was incorrectly being set to `empty` on the source added to the metastore when joining on ROWKEY. This is also now resolved.

##### Review notes:

1. The first commit is just switching a test to Mockito and refactoring it to keep the next commit clean, so review it by itself and ignore in the main review.
1. I'd start by looking at `joins.json` to see the tests that have been fixed and added.
1. Then look at `Analyzer`, which now builds the `KeyField`s that the `JoinNode` needs.
1. Then look at `JoinNode` for the wiring. Note: `getKeyField` now returns `leftKeyField`, which may feel wrong, but this is refactored existing functionality. I'll be looking into this more soon, as there are issues around key fields where only the right join key is in the projection.
1. The look at `SchemaKStream`, specifically `selectKey` as this is where the magic happens.  This will, if using new key fields i.e. if a new query, early out and not repartition is selecting rowkey. It still repartitions if using legacy key fields. This method also builds a new key field, replacing ROWKEY in the new key, and uses this to create new `SchemaKStream`, which fixes the `empty` key issue.
1. Take a look at `PhysicalPlanBuilderTest` as this adds functional tests around the different combinations on join keys.
1. The rest is just plumbing...

### Testing done 
Extensive JSON and Unit tests added.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java [hunk 1]
```diff
@@ -515,21 +515,31 @@ SelectValueMapper getSelectValueMapper() {
...
       final boolean updateRowKey,
       final QueryContext.Stacker contextStacker
   ) {
-    final Optional<Field> resolved = keyField.resolve(schema, ksqlConfig);
+    final Field field = selectKeyField.resolve(schema, ksqlConfig)
+        .orElseThrow(IllegalArgumentException::new);
 
-    final boolean namesMatch = resolved
-        .map(kf -> SchemaUtil.matchFieldName(kf, newKeyField.name()))
+    final KeyField newKeyField =
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: it took me a surprising amount of time to grok this code (especially in relation to the rest of the method). I think what tripped me up is the `keyField.withLegacy(selectKeyField.legacy())`. This splits the key, but the split is only really needed for the `if (namesMatch ...)` clause (as evidenced by the basically duplicated condition), but is only used if the namesMatch part of the condition matches. 

Instead, I think we should expose this cyclomatic complexity in explicit if/else (or if/return if you so desire) branches instead of hiding it under conditional state:
```
if (names match) {
  // use selectKeyField
} else if (usingNewKeys && isRowKey()) {
  // use the existing keyField (doesn't matter what legacy is set to)
} else {
  // do the repartition
}
```
Feel free to do something else instead of my suggestion, but I do request exposing the structure in control blocks instead of state. This complexity is also compounded by the fact that at this point it is very possible that the legacy key is null (empty) but the new key will never be empty.

File: ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java [hunk 2]
```diff
@@ -352,19 +355,15 @@ Joiner getJoiner(final DataSource.DataSourceType leftType,
...
     }
 
-    @SuppressWarnings("OptionalGetWithoutIsPresent")
-    Field getJoinKey(final String alias, final KeyField keyField) {
-      final KeyField keyFieldWithAlias = KeyField.of(
-          keyField.name().map(name -> SchemaUtil.buildAliasedFieldName(alias, name)),
+    static KeyField getJoinKey(final String alias, final KeyField keyField) {
+      final String latest = keyField.name()
+          .map(name -> SchemaUtil.buildAliasedFieldName(alias, name))
+          .orElse(SchemaUtil.buildAliasedFieldName(alias, SchemaUtil.ROWKEY_NAME));
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java]: oooh! what if we have a `KeyField#aliased(String)` that turns both the elements into aliases? Then this code becomes so simple:
```java
final String latest = keyField.name().orElse(ROWKEY_NAME);
return KeyField.of(Optional.of(latest), keyField.legacy()).aliased(alias);
```

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java [hunk 3]
```diff
@@ -739,42 +740,333 @@ public void shouldHaveOptionalFieldsInResultSchema() {
...
+
+    // When:
+    final QueryMetadata result = execute("CREATE STREAM s1 AS "
+        + "SELECT * FROM test2 JOIN test3 WITHIN 1 SECOND "
+        + "ON test2.id = test3.col0;")
+        .get(0);
+
+    // Then:
+    assertThat(result.getExecutionPlan(),
+        containsString("[ REKEY ] | Schema: [TEST3.ROWTIME : BIGINT"));
```
Comment (agavra) [inline ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: is there anything in the execution plan that indicates we are rekeying to the correct column?

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java [hunk 4]
```diff
@@ -739,42 +740,333 @@ public void shouldHaveOptionalFieldsInResultSchema() {
...
+        + "SELECT * FROM test2 JOIN test3 WITHIN 1 SECOND "
+        + "ON test2.rowkey = test3.rowkey;")
+        .get(0);
+
+    // Then:
+    assertThat(result.getExecutionPlan(), not(containsString("[ REKEY ]")));
+  }
+
+  @Test
+  public void shouldNotRepartitionEitherStreamsIfJoiningOnRowKeyEvenIfStreamsHaveNoKeyField() {
```
Comment (agavra) [inline ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: just wondering, what happens if you join on ROWKEY and then PARTITION BY ROWKEY? I assume it should work fine, but maybe a good thing to QTT for

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java [hunk 5]
```diff
@@ -515,21 +515,31 @@ SelectValueMapper getSelectValueMapper() {
...
   @SuppressWarnings("unchecked")
   public SchemaKStream<?> selectKey(
-      final Field newKeyField,
+      final KeyField selectKeyField,
       final boolean updateRowKey,
       final QueryContext.Stacker contextStacker
   ) {
-    final Optional<Field> resolved = keyField.resolve(schema, ksqlConfig);
+    final Field field = selectKeyField.resolve(schema, ksqlConfig)
+        .orElseThrow(IllegalArgumentException::new);
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: I've not bothered as its a programming error if this is hit, i.e. it shouldn't be see with any combination of SQL.

What do you reckon?

File: ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java [hunk 6]
```diff
@@ -292,22 +286,27 @@ Joiner getJoiner(final DataSource.DataSourceType leftType,
         throw new RuntimeException("Expected to find a Table, found a stream instead.");
       }
 
-      final String expectedKeyField = SchemaUtil.buildAliasedFieldName(tableName, keyFieldName);
+      final String expectedKeyField = nodeKeyField
+          .resolve(node.getSchema(), builder.getKsqlConfig())
+          .orElseThrow(IllegalStateException::new)
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java]: I've not bothered as its a programming error if this is hit, i.e. it shouldn't be see with any combination of SQL.

What do you reckon?

File: ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java [hunk 7]
```diff
@@ -316,17 +315,21 @@ Joiner getJoiner(final DataSource.DataSourceType leftType,
...
         final SchemaKStream stream,
-        final String targetKey,
+        final KeyField targetKeyField,
         final QueryContext.Stacker contextStacker
     ) {
       final Schema schema = stream.getSchema();
-      final Field field = SchemaUtil.getFieldByName(schema, targetKey)
+
+      final String fieldName = targetKeyField.resolveName(builder.getKsqlConfig())
+          .orElseThrow(IllegalStateException::new);
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java]: I've not bothered as its a programming error if this is hit, i.e. it shouldn't be see with any combination of SQL.

What do you reckon?

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java [hunk 8]
```diff
@@ -563,6 +572,16 @@ SelectValueMapper getSelectValueMapper() {
     );
   }
 
+  private boolean usingNewKeyFields() {
+    return !ksqlConfig.getBoolean(KsqlConfig.KSQL_USE_LEGACY_KEY_FIELD);
+  }
+
+  private static boolean isRowKey(final String fieldName) {
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: Yeah, I actually moved it there, but forgot to update this bit. Will do.

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java (hunk 1 above)
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: I'll have a play and see what works.  I agree: code that's easy to read is good code.

File: ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java (hunk 2 above)
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java]: I did think about that, but thought its potentially putting too much logic into `KeyField`.  I'll take another look.

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java (hunk 3 above)
Comment (big-andy-coates) [reply ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: I'll take a look.  The main thing I was looking for was to ensure presence / absence of the repartition step -  but you're right, may as well check _what_ its being reparatitioned by as well.

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java (hunk 4 above)
Comment (big-andy-coates) [reply ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: Yeah, also while working on this I've realised really we need `KeyFields` not `KeyField`, cos there's plenty of scope for to be multiple copies of the key in the projection...

File: ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (agavra) [reply ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java]: I think it's just nice from a reading the code perspective even if the user will never see it but not a big deal

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java (hunk 1 above)
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: So....

>  I think what tripped me up is the keyField.withLegacy(selectKeyField.legacy()). This splits the key, but the split is only really needed for the if (namesMatch ...) clause 

This is not the cause, the result is used for all paths.

I've reworked it very slightly and renamed some vars to hopefully make things clearer.

File: ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java (hunk 2 above)
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java]: Done.

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java (hunk 3 above)
Comment (big-andy-coates) [reply ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: Unfortunately, I can't see anything in the plan / query that currently shows _what_ it's partitioned by.

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java (hunk 4 above)
Comment (big-andy-coates) [reply ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: Gave it a try and you can't `PARTITION BY ROWKEY` its not valid.

File: ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java [hunk 9]
```diff
@@ -352,19 +357,34 @@ Joiner getJoiner(final DataSource.DataSourceType leftType,
...
+
+      return KeyField.of(latest, leftKeyField.legacy())
+          .withAlias(leftAlias);
+    }
 
-      return joinNode.schema.field(keyFieldName);
+    /**
+     * The key field of the resultant joined stream for OUTER joins.
+     *
+     * <p>Note: for outer joins neither source's key field can be used as they may be null.
```
Comment (hjafarpour) [inline ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java]: Good catch!

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java [hunk 10]
```diff
@@ -104,12 +107,38 @@
   private static final String FILTER_MAPVALUES_NODE = "KSTREAM-MAPVALUES-0000000004";
   private static final String FOREACH_NODE = "KSTREAM-FOREACH-0000000005";
 
-  private static final String createStream = "CREATE STREAM TEST1 (COL0 BIGINT, COL1 VARCHAR, COL2 DOUBLE) WITH ( "
-      + "KAFKA_TOPIC = 'test1', VALUE_FORMAT = 'JSON' );";
+  private static final String CREATE_STREAM_TEST1 = "CREATE STREAM TEST1 "
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: That's what I've already done...

Constant `CREATE_STREAM_TEST1` CREATEs a STEAM called TEST1...
