### PR TITLE
fix: deals with issue #5521 by adding more descriptive error message

### LINKED ISSUE #5521: should throw more descriptive error on scale mismatch for INSERT into decimal statements
**Describe the bug**
Current error message simply states that row cannot be serialized. Real issue is that the scale is not being appropriately matched. This was found after looking at issue #5282 

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL. : 0.9.0
2. Sample source data. 
3. Any SQL statements you ran : 

```
 CREATE STREAM s1 (
>    x DECIMAL(12, 2)
>) WITH (
>    kafka_topic = 's1',
>    partitions = 1,
>    value_format='avro'
>);

INSERT INTO s1 (x) VALUES (2.1);

```
**Expected behavior**
Should give more descriptive error message than cannot serialize, such as scales do not match

**Actual behaviour**

`Failed to insert values into 'S1'. Could not serialize row: [ 2.1 ]
`

### PR DESCRIPTION
**Pull request by nae701**
fixes #5521 

### Description 
Error message before was not very helpful, this patch serves to make it more clear to the user that the decimal scale was not being matched appropriately for example.

### Testing done 
Reviewed manually by running some insert statements on ksql to see that error message was more appropriate now

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java [hunk 1]
```diff
@@ -100,41 +100,41 @@ public InsertValuesExecutor() {
   public interface RecordProducer {
 
     void sendRecord(
-        ProducerRecord<byte[], byte[]> record,
-        ServiceContext serviceContext,
-        Map<String, Object> producerProps
+            ProducerRecord<byte[], byte[]> record,
```
Comment (agavra) [inline ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java:103]: it looks like you have IntelliJ set to use 4 spaces for tabs instead of 2. Please make sure to change that style setting and change this file back :)

File: ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenSpec.java [hunk 2]
```diff
@@ -101,9 +101,8 @@ public String getStructSchemaName(final CreateStructExpression createStructExpre
     private final Map<ColumnName, String> columnRefToName = new HashMap<>();
     private final ImmutableListMultimap.Builder<FunctionName, String> functionNameBuilder =
         ImmutableListMultimap.builder();
-    private final ImmutableMap.Builder<CreateStructExpression, String> structToSchemaName =
-        ImmutableMap.builder();
-
+    private final Map<CreateStructExpression, String> structToSchemaName =
+            new HashMap<CreateStructExpression, String>();
```
Comment (agavra) [inline ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenSpec.java:105]: this change seems to be leftover from a previous commit - please make sure to rebase from master and push only the most recent commit to this PR branch. (same comment about the files below)

**Comment by nae701** [comment]
I followed similar steps to try and push the changes for the zero edge case, but it ended up committing them here, is it okay if I leave this here and simply link this pull request with Michael's original issue #5282 ?
