### PR TITLE
Fix array store exception in TopKDistinct

### LINKED ISSUE #911: TopK distinct throws ArrayStoreException when used with integers and longs
TopK distinct throws an ArrayStoreException when used with anything other than double

### PR DESCRIPTION
**Pull request by dguy**
`TopKDistinct` throws `ArrayStoreException` when they type is anything other than `Double`
Fixes #911

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctAggFunctionFactory.java [hunk 1]
```diff
@@ -39,13 +39,13 @@ public KsqlAggregateFunction getProperAggregateFunction(List<Schema> argTypeList
...
+        return new TopkDistinctKudaf<>(-1, 0, Schema.INT32_SCHEMA, Integer.class);
       case INT64:
-        return new TopkDistinctKudaf<Long>(-1, 0, Long.class);
+        return new TopkDistinctKudaf<>(-1, 0, Schema.INT64_SCHEMA, Long.class);
       case FLOAT64:
-        return new TopkDistinctKudaf<Double>(-1, 0, Double.class);
+        return new TopkDistinctKudaf<>(-1, 0, Schema.FLOAT64_SCHEMA, Double.class);
       case STRING:
-        return new TopkDistinctKudaf<String>(-1, 0, String.class);
+        return new TopkDistinctKudaf<>(-1, 0, Schema.STRING_SCHEMA, String.class);
```
Comment (bluemonk3y) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctAggFunctionFactory.java]: The problem with the Schema stuff is that there is loads of nut-and-bolts style code scattered everywhere. We talked about stripping it out to use enums to handle these types of statements and then inject a lambda to create the function. It out of scope of this PR but everytime I see the schema class it IRKs me....

Comment (dguy) [reply ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctAggFunctionFactory.java]: @bluemonk3y - yes, tell me about it. However as this is for 4.1 we don't want to make big changes
