### PR TITLE
Ksql 1029 improve csas/ctas existing stream error message

### LINKED ISSUE #1029: Misleading error on CSAS if another query targets same topic
```
ksql> CREATE STREAM FOO AS SELECT * FROM SYSLOG;

 Message
----------------------------
 Stream created and running
----------------------------
ksql> CREATE STREAM BAR WITH (KAFKA_TOPIC='FOO') AS SELECT * FROM SYSLOG;
io.confluent.ksql.util.KsqlException: Cannot add the new topic. Another topic with the same name already exists: FOO
ksql>
```

This error is not accurate. A stream can be created if the topic already exists. The error should read something like: 

```
Cannot create the stream. The output topic FOO is already used by another stream or table
```

For bonus points, tell the user which existing stream or table is writing to the output topic. Or, instruct them to run `SHOW STREAMS` and look at the `Kafka Topic` column to see.

### PR DESCRIPTION
**Pull request by hjafarpour**
### Description 
This PR fixes #1029 by improving the error message.

### Testing done 
Unit tests.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/test/java/io/confluent/ksql/QueryEngineTest.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+  public void shouldThrowExpectedExceptionForDuplicateStream() {
+    final QueryEngine queryEngine = new QueryEngine(ksqlEngine,
+        new CommandFactories(topicClient, schemaRegistryClient, true));
+    try {
+      final List<Pair<String, Statement>> statementList = ksqlEngine.parseQueries(
+          "CREATE STREAM FOO AS SELECT * FROM TEST2; CREATE STREAM BAR WITH (KAFKA_TOPIC='FOO') AS SELECT * FROM TEST2;", metaStore.clone());
+      queryEngine.buildLogicalPlans(metaStore, statementList, ksqlConfig);
+      Assert.fail();
+    } catch (KsqlException e) {
+      assertThat(e.getMessage(), equalTo("Cannot create the stream. The output topic FOO is already used by FOO"));
```
Comment (apurvam) [inline ksql-engine/src/test/java/io/confluent/ksql/QueryEngineTest.java]: Ideally, this test should update the meta store with one statement that registers topic `FOO`, and then try to do it again with a different statement, and then check that the topic name and source in the error message are accurate.

Also, what if you do a `CREATE TABLE`? Will we still print "Cannot create the stream"?

File: ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java [hunk 2]
```diff
@@ -129,7 +129,16 @@ private PlanNode buildQueryLogicalPlan(
               ksqlStructuredDataOutputNode.getKsqlTopic()
           );
       if (analysis.isDoCreateInto()) {
-        tempMetaStore.putTopic(ksqlStructuredDataOutputNode.getKsqlTopic());
+        try {
+          tempMetaStore.putTopic(ksqlStructuredDataOutputNode.getKsqlTopic());
+        } catch (KsqlException e) {
+          final String sourceName = tempMetaStore.getSourceForTopic(
+              ksqlStructuredDataOutputNode.getKsqlTopic().getName()).getName();
+          throw new KsqlException(
```
Comment (apurvam) [inline ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java]: Is this the only reason why the `putTopic` can fail?

**Comment by hjafarpour** [comment]
@rodesai @apurvam wanna take another look at this?

File: ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java (hunk 2 above)
Comment (apurvam) [reply ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java]: I think the point is that we should make sure that the put failed because the topic already exists _before_ returning that in the error message. 

This way, if the put can fail in the future for other reasons, we won't return the wrong error message.

Comment (hjafarpour) [reply ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java]: The only time we get `KsqlException` from `putTopic` is when the topic already exists. For any other problem we won't get `KsqlException`. Also the check is done in the `putTopic` method anyway!
