### PR TITLE
fix: change default exception handling for timestamp extractors

### LINKED ISSUE #2609: Fatal user code error in TimestampExtractor
KSQL 5.2

Set up test data

```
kafkacat -P -b localhost -t time_test <<EOF
{"order_id":101,"customer_id":513,"order_ts":"2019-03-24T07:38:05Z","order_total_usd":"56615.44","make":"Ford"}
EOF
```

Declare stream, with the timestamp set based on a column in the payload

```
SET 'auto.offset.reset' = 'earliest';

CREATE STREAM TIME_TEST (ORDER_ID INT, ORDER_TS VARCHAR) WITH (TIMESTAMP='ORDER_TS', TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX', KAFKA_TOPIC='time_test', VALUE_FORMAT='JSON');
```

Query stream

```
ksql> SELECT * FROM TIME_TEST;
1553413085000 | null | 101 | 2019-03-24T07:38:05Z
```

Insert bad record into topic, in which the timestamp column doesn't exist: 

```
kafkacat -P -b localhost -t time_test <<EOF
{"shipment_id":"ship-uu20951","order_id":102,"shipment_provider":"ups","shipment_ts":"2019-03-26T06:45:10Z"}
EOF
```

🛑 `SELECT` breaks: 

```
ksql> SELECT * FROM TIME_TEST;
1553413085000 | null | 101 | 2019-03-24T07:38:05Z
Fatal user code error in TimestampExtractor callback for record ConsumerRecord(topic = time_test, partition = 0, leaderEpoch = null, offset = 1, CreateTime = 1553601617291, serialized key size = -1, serialized value size = 108, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [ 102 | null ]).
Caused by: text
Query terminated
```

🛑  CSAS fails too

```
ksql-server_1             | [2019-03-26 12:04:27,300] INFO stream-thread [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537] State transition from RUNNING to PENDING_SHUTDOWN (org.apache.kafka.streams.processor.internals.StreamThread:214)
ksql-server_1             | [2019-03-26 12:04:27,300] INFO stream-thread [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537] Shutting down (org.apache.kafka.streams.processor.internals.StreamThread:1205)
ksql-server_1             | [2019-03-26 12:04:27,340] INFO stream-thread [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537] State transition from PENDING_SHUTDOWN to DEAD (org.apache.kafka.streams.processor.internals.StreamThread:214)
ksql-server_1             | [2019-03-26 12:04:27,341] INFO stream-client [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c] State transition from RUNNING to ERROR (org.apache.kafka.streams.KafkaStreams:263)
ksql-server_1             | [2019-03-26 12:04:27,341] ERROR stream-client [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c] All stream threads have died. The instance will be in error state and should be closed. (org.apache.kafka.streams.KafkaStreams:423)
ksql-server_1             | Exception in thread "_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537" org.apache.kafka.streams.errors.StreamsException: Fatal user code error in TimestampExtractor callback for record ConsumerRecord(topic = time_test, partition = 0, leaderEpoch = null, offset = 1, CreateTime = 1553601617291, serialized key size = -1, serialized value size = 108, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [ 102 | null ]).
ksql-server_1             | [2019-03-26 12:04:27,343] INFO stream-thread [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537] Shutdown complete (org.apache.kafka.streams.processor.internals.StreamThread:1225)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.RecordQueue.maybeUpdateTimestamp(RecordQueue.java:174)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.RecordQueue.poll(RecordQueue.java:115)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.PartitionGroup.nextRecord(PartitionGroup.java:100)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:349)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:199)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:420)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:889)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:804)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:773)
ksql-server_1             | Caused by: java.lang.NullPointerException: text
ksql-server_1             |     at java.util.Objects.requireNonNull(Objects.java:228)
ksql-server_1             |     at java.time.format.DateTimeFormatter.parseBest(DateTimeFormatter.java:1891)
ksql-server_1             |     at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:46)
ksql-server_1             |     at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:42)
ksql-server_1             |     at io.confluent.ksql.util.timestamp.StringTimestampExtractor.extract(StringTimestampExtractor.java:45)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.RecordQueue.maybeUpdateTimestamp(RecordQueue.java:169)
ksql-server_1             |     ... 8 more
```

PRINT works: 

```
ksql> PRINT 'time_test' FROM BEGINNING;
Format:JSONC to interrupt
{"ROWTIME":1553601533808,"ROWKEY":"null","order_id":101,"customer_id":513,"order_ts":"2019-03-24T07:38:05Z","order_total_usd":"56615.44","make":"Ford"}
{"ROWTIME":1553601617291,"ROWKEY":"null","shipment_id":"ship-uu20951","order_id":102,"shipment_provider":"ups","shipment_ts":"2019-03-26T06:45:10Z"}
```

Works fine if `TIMESTAMP` not set: 

```
ksql> CREATE STREAM TIME_TEST2 (ORDER_ID INT, ORDER_TS VARCHAR) WITH (KAFKA_TOPIC='time_test', VALUE_FORMAT='JSON')

 Message
----------------
 Stream created
----------------
ksql> SELECT * FROM TIME_TEST2;
1553601533808 | null | 101 | 2019-03-24T07:38:05Z
1553601617291 | null | 102 | null
```

Workaround presumably is to define the first stream without `TIMESTAMP`, create a derived one in which records without the timestamp field are filtered out and set the timestamp in the created one. 

But, this should be fixed properly, and just as undeserialisable messages are dropped but processing continues, the same here. At the moment it's a very sharp edge.

### PR DESCRIPTION
**Pull request by agavra**
fixes #2609 

### Description 
ksqlDB currently fails violently whenever a timestamp cannot be extracted from a record. Perhaps more fatally, it also does not log anything to the processing log meaning users that are using the cloud offering of ksql will not be able to see what happened to their queries.

This PR addresses both of those concerns and gives users the ability to toggle whether they want the failure to be violent or graceful so that they can choose not to lose data.

### Testing done 

New unit tests and end to end testing:
```
ksql> PRINT ts FROM BEGINNING;
Value format: JSON or KAFKA_STRING
rowtime: 2/25/20 3:11:47 PM PST, key: <null>, value: {"TS":"10-04-19 12:00:17"}
rowtime: 2/25/20 3:11:52 PM PST, key: <null>, value: {"TS":"10-04-19 X 12:00:17"}
rowtime: 2/25/20 3:11:55 PM PST, key: <null>, value: {"TS":"10-04-19 12:00:17"}

ksql> CREATE STREAM ts (ts VARCHAR) WITH (value_format='json', kafka_topic='ts', partitions=1, timestamp='ts', timestamp_format='yy-MM-dd HH:mm:ss')

ksql> SELECT * FROM ts EMIT CHANGES;
+--------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------+
|ROWTIME                                                       |ROWKEY                                                        |TS                                                            |
+--------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------+
|1271703617000                                                 |null                                                          |10-04-19 12:00:17                                             |
|1271703617000                                                 |null                                                          |10-04-19 12:00:17                                             |
^CQuery terminated

ksql> SELECT * FROM KSQL_PROCESSING_LOG EMIT CHANGES;
+--------------+--------------+--------------+--------------+--------------+--------------+
|ROWTIME       |ROWKEY        |LOGGER        |LEVEL         |TIME          |MESSAGE       |
+--------------+--------------+--------------+--------------+--------------+--------------+
|1582672325285 |null          |processing.211|ERROR         |1582672325277 |{TYPE=0, DESER|
|              |              |78117353354788|              |              |IALIZATIONERRO|
|              |              |25            |              |              |R={ERRORMESSAG|
|              |              |              |              |              |E=Text '10-04-|
|              |              |              |              |              |19 X 12:00:17'|
|              |              |              |              |              | could not be |
|              |              |              |              |              |parsed at inde|
|              |              |              |              |              |x 9, RECORDB64|
|              |              |              |              |              |=null, CAUSE=[|
|              |              |              |              |              |]}, RECORDPROC|
|              |              |              |              |              |ESSINGERROR=nu|
|              |              |              |              |              |ll, PRODUCTION|
|              |              |              |              |              |ERROR=null}   |
```

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+import org.apache.kafka.clients.consumer.ConsumerRecord;
+import org.apache.kafka.streams.processor.TimestampExtractor;
+
+/**
+ * A wrapper around {@code TimestampExtractor} that can be configured to suppress any
+ * errors and instead returns a negative timestamp (indicating to streams that the message
+ * should be ignored). Additionally, this class ensures that any errors are logged to the
+ * processing log (even the fatal ones) for visibility.
+ */
+public class LoggingTimestampExtractor implements TimestampExtractor {
```
Comment (spena) [inline ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java]: You might want to implement from `KsqlTimestampExtractor` to we can support this on CSAS/CTAS statements too.

File: ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+  @Override
+  public long extract(final ConsumerRecord<Object, Object> record, final long partitionTime) {
+    try {
+      return delegate.extract(record, partitionTime);
+    } catch (final Exception e) {
+      logger.error(deserializationErrorMsg(e, record));
+      if (failOnError) {
+        throw e;
+      }
+      return -1L;
```
Comment (spena) [inline ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java]: Will this allow KSQL to display the row with ROWTIME = -1 in case of a failure? 

I'm trying to understand how the `FailOnInvalidTimestamp` will work in this situation. If a -1 is found on the row, then the `FailOnInvalidTimestamp` will throw an exception which this code will catch and log it to the processing log. But it returns a -1 back to stream, so the stream will set it to as ROWTIME, won't it?

File: ksql-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java [hunk 3]
```diff
@@ -314,7 +315,13 @@ private static TimestampExtractor timestampExtractor(
         .map(Column::index)
         .orElse(-1);
 
-    return timestampPolicy.create(timestampIndex);
+    return timestampPolicy.create(
+        timestampIndex,
+        ksqlConfig.getBoolean(KsqlConfig.KSQL_TIMESTAMP_THROW_ON_INVALID),
+        queryBuilder.getProcessingLogContext()
+            .getLoggerFactory()
+            .getLogger(queryBuilder.getQueryId().getId())
```
Comment (rodesai) [inline ksql-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java]: Use this for the logger name instead of the id directly:

```
final QueryId queryId = queryBuilder.getQueryId();
final QueryContext queryContex = source.getProperties().getQueryContext()
final String loggerNamePrefix = QueryLoggerUtil.queryLoggerName(queryId, queryContext);
```

This way you will get a more specific logger prefix that tells you where in the query plan the message was generated.

File: ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactory.java [hunk 4]
```diff
@@ -34,6 +36,20 @@ private SerdeProcessingLogMessageFactory() {
   public static Function<ProcessingLogConfig, SchemaAndValue> deserializationErrorMsg(
       final Throwable exception,
       final Optional<byte[]> record
+  ) {
+    return message(exception, () -> record.map(Base64.getEncoder()::encodeToString).orElse(null));
+  }
+
+  public static Function<ProcessingLogConfig, SchemaAndValue> deserializationErrorMsg(
```
Comment (rodesai) [inline ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactory.java]: I'd use a different message type for this error. Deserialization error messages generally mean the serde couldn't deserialize the record in the topic, and contain a base64 encoded representation of the data inside (in a field called `recordB64`). The data written out here represents something different - KSQL's view of the row once it's been deserialized.

Comment (rodesai) [reply ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactory.java]: You should be able to use the existing record processing error (`EngineProcessingLogMessageFactory.recordProcessingError`)

Comment (agavra) [reply ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactory.java]: i was debating which I should do since this felt like a type of deserialization error to me, but I'll update it to a new type (I can see both sides)

File: ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java (hunk 2 above)
Comment (agavra) [reply ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java]: any negative timestamp causes the event to be ignored by Kafka Streams. That means that if this wraps `FailOnInvalidTimestamp` but you set `ksql.timestamp.throw.on.invalid` to `false` then it will suppress the throw and just ignore the message

File: ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java (hunk 1 above)
Comment (agavra) [reply ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java]: I think it's already supported because this just wraps other extractors (we always return this extractor). I'm not sure exactly what you mean here?

Comment (agavra) [reply ksql-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/LoggingTimestampExtractor.java]: ah `KsqlTimestampExtractor` is something new. I'll do this
