### PR TITLE
DoubleMaxKudaf doesn't work correctly

### LINKED ISSUE #908: DoubleMaxUDAF doesn't work correctly
It is initialised with Double.MIN_VALUE, however this is a positive number which means that any smaller numbers will not be considered, i.e., `0 > Double.MIN_VALUE` == `false`

### PR DESCRIPTION
**Pull request by dguy**
It uses `Double.MIN_VALUE` as the inital value. This is a positive number so doesn't behave as anticipated.

Fixes #908

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudaf.java [hunk 1]
```diff
@@ -29,7 +29,7 @@
 public class DoubleMaxKudaf extends KsqlAggregateFunction<Double, Double> {
 
   DoubleMaxKudaf(int argIndexInValue) {
-    super(argIndexInValue, () -> Double.MIN_VALUE, Schema.FLOAT64_SCHEMA,
+    super(argIndexInValue, () -> -Double.MAX_VALUE, Schema.FLOAT64_SCHEMA,
```
Comment (xvrl) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudaf.java]: what happens if we encounter Double.NEGATIVE_INFINITY?

Comment (dguy) [reply ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudaf.java]: Good point - thanks @xvrl will use that instead

Comment (xvrl) [reply ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudaf.java]: you may want to look at the implications at serialization time though. For instance, there is no standard representation in JSON for infinities. Jackson stores them as strings by default. As long as you stick to jackson you should be fine, but other systems may break.
