### PR TITLE
fix: If startup hangs (esp on preconditions), shutdown server correctly

### LINKED ISSUE #4779: KSQL may get stuck shutting down if it's stuck in tryStart
`KsqlRestApplication.tryStart` doesn't coordinate with the shutdown handling code to ensure graceful shutdown if it's stuck somewhere in `tryStart`. This can cause the JVM to hang during shutdown. For example, if a user has installed a precondition that is never met, the server would never exit.

### PR DESCRIPTION
**Pull request by AlanConfluent**
### Description 
Often when the server is starting up, it waits for preconditions to be met.  If the preconditions can't be met, it tries indefinitely.  If the server shuts down, the JVM will not stop due to this unending preconditions effort.

This change allows the preconditions to be interrupted during shutdown so that the application and JVM exit properly. 

Fixes #4779 

### Testing done 
`mvn package`

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by rodesai** [comment]
How'd you test it out? Were you able to reproduce locally?

**Comment by AlanConfluent** [comment]
> How'd you test it out? Were you able to reproduce locally?

I introduced a precondition that never completes.  Then I ran the server and would then issue a kill command, which would call the shutdown method.  I pretty much verified that the startup method completes immediately and that the jvm quits within some reasonable window, e.g. 5-10 seconds after that.

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java [hunk 1]
```diff
@@ -391,6 +404,13 @@ private KsqlFailedPrecondition(final String message) {
     }
   }
 
+  static final class AbortApplicationStartException extends Exception {
```
Comment (big-andy-coates) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java]: Why are we using a checked exception here?  We don't really use checked exceptions any more. They're a PITA! Why not extend `KsqlServerException`?

File: ksqldb-common/src/main/java/io/confluent/ksql/util/RetryUtil.java [hunk 2]
```diff
@@ -53,6 +55,7 @@ public static void retryWithBackoff(
       final int initialWaitMs,
       final int maxWaitMs,
       final Runnable runnable,
+      final AtomicBoolean stopRetrying,
```
Comment (big-andy-coates) [inline ksqldb-common/src/main/java/io/confluent/ksql/util/RetryUtil.java]: nit: Rather than taking a `AtomicBoolean`, why not take a `Supplier<Boolean>`?  The latter is more general and flexible, allowing method that returns a boolean to be used.  

You can then wire this up by passing `stopRetrying::get`.

File: ksqldb-common/src/test/java/io/confluent/ksql/util/RetryUtilTest.java [hunk 3]
```diff
@@ -80,4 +85,27 @@ public void shouldThrowPassThroughExceptions() {
...
+      if (times[0]++ == 1) {
+        stopRetrying.set(true);
+      }
+      return null;
+    }).when(sleep).accept(any());
+    try {
+      RetryUtil.retryWithBackoff(3, 1, 100, runnable, sleep, stopRetrying, Collections.emptyList());
+      fail("retry should have thrown");
+    } catch (final RuntimeException e) {
+    }
```
Comment (big-andy-coates) [inline ksqldb-common/src/test/java/io/confluent/ksql/util/RetryUtilTest.java]: You can do this with less code with:

```java
assertThrows(
   RuntimeException.class,
   () -> RetryUtil.retryWithBackoff(3, 1, 100, runnable, sleep, stopRetrying, Collections.emptyList())
);
```

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java [hunk 4]
```diff
@@ -404,17 +424,27 @@ private void checkPreconditions() {
...
+      RetryUtil.retryWithBackoff(
+          Integer.MAX_VALUE,
+          1000,
+          30000,
+          this::checkPreconditions,
+          shuttingDown,
+          predicates
+      );
+    } catch (KsqlFailedPrecondition e) {
+      log.error("Finished Precondition retrying", e);
```
Comment (big-andy-coates) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java]: This message seems a little confusing. It's an error, but the text sounds more like a success...  maybe

```java
log.error("Failed to meet preconditions. Existing...", e);
```

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java [hunk 5]
```diff
@@ -456,6 +486,13 @@ private void initialize(final KsqlConfig configWithApplicationServer) {
   @SuppressWarnings("checkstyle:NPathComplexity")
   @Override
   public void triggerShutdown() {
+    // First, make sure the server wasn't stuck in startup.  Set the shutdown flag and interrupt the
+    // startup thread if it's been hanging.
+    shuttingDown.set(true);
+    if (startAsyncThread != null) {
+      startAsyncThread.interrupt();
```
Comment (big-andy-coates) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java]: If we're interrupting the start up thread, then there's a high chance we'll see interrupt exceptions being thrown. Yet I don't see anywhere that we catch this, now expected, exception.  This may lead to the exception being logged out, which isn't ideal if its expected.

Maybe the code in `startAsync` need to also catch interrupted exceptions and log out the `Aborting application start`?

File: ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java [hunk 6]
```diff
@@ -415,7 +421,7 @@ public void shouldNotInitializeUntilPreconditionsChecked() {
   }
 
   @Test
-  public void shouldConfigureRocksDBConfigSetter() {
+  public void shouldConfigureRocksDBConfigSetter() throws AbortApplicationStartException {
```
Comment (big-andy-coates) [inline ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java]: If we make `AbortApplicationStartException` a non-checked exception we can drop all these `throws`...

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java (hunk 5 above)
Comment (AlanConfluent) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java]: In this particular case, it's caught in `RetryUtil`:

```
duration -> {
          try {
            Thread.sleep(duration);
          } catch (final InterruptedException e) {
            log.debug("retryWithBackoff interrupted while sleeping");
          }
        },
```

I believe it would only throw this exception if someone did something that could be interrupted (like sleeping), and since it's a checked exception, they would have to catch it explicitly (or let it bubble up explicitly).  In this case, I would want them to catch it and then throw a `AbortApplicationStartException` which is already handled.  So I don't think catching `InterruptedException`s at the `startAsync` level would be required.  Is that reasonable?

File: ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java (hunk 6 above)
Comment (AlanConfluent) [reply ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java]: Done

File: ksqldb-common/src/main/java/io/confluent/ksql/util/RetryUtil.java (hunk 2 above)
Comment (AlanConfluent) [reply ksqldb-common/src/main/java/io/confluent/ksql/util/RetryUtil.java]: Good suggestion.

File: ksqldb-common/src/test/java/io/confluent/ksql/util/RetryUtilTest.java (hunk 3 above)
Comment (AlanConfluent) [reply ksqldb-common/src/test/java/io/confluent/ksql/util/RetryUtilTest.java]: Done
