### PR TITLE
Fix: Consistency between inserted rowkey and key values when inserting into a table with a key

### LINKED ISSUE #3347: INSERT VALUES fails if key field is not STRING
```sql
CREATE TABLE movies (id INT, title VARCHAR, release_year INT) WITH (kafka_topic='movies', key='id', partitions=1, value_format='avro');

CREATE STREAM ratings (id INT, rating DOUBLE) WITH (kafka_topic='ratings', partitions=1, value_format='avro');

INSERT INTO movies (id, title, release_year) VALUES (294, 'Die Hard', 1998);
-- fails with: 
-- Failed to insert values into stream/table: MOVIES
-- Caused by: Invalid Java object for schema type STRING: class java.lang.Integer
--	for field: "ROWKEY"
```

The issue here is that the `id` key field specified in the `movies` WITH clause is an `INT`.  
KSQL sees that the `id` field is the same as the key and hence tries to set ROWKEY to `294`, but `ROWKEY` is a `STRING` field, and KSQL blows up...

Until we have primitive keys other than String I think KSQL needs to support converting the value to a STRING to store in `ROWKEY`.

We need to make sure the conversion is compatible with what KSQL would do if storing, for example, a `STRUCT` field in the key as part of a `GROUP BY` clause.

A secondary issue is that even if the user attempts to explicitly supply `ROWKEY`, or `ROWKEY` and not `Id`, it still fails:

```sql
INSERT INTO ratings (rowkey, id, title, release_year) VALUES ('294', 294, 'Die Hard', 1998);
-- fails with:
-- Failed to insert values into stream/table: RATINGS
-- Caused by: java.lang.IllegalStateException

NSERT INTO ratings (rowkey, title, release_year) VALUES ('294', 'Die Hard', 1998);
-- fails with:
--  Failed to insert values into stream/table: RATINGS
--  Caused by: java.lang.IllegalStateException
```

### PR DESCRIPTION
**Pull request by purplefox**
### Description 

Fixes #3347 

- When inserting into a TABLE with a key, and specifying the key field but not the rowkey, we ensure that the rowkey is set to the string form of the key
- When inserting into a TABLE with a key and specifying both the rowkey and the key, we check that the rowkey matches the string form of the key

### Testing done 

Added several new RQTT tests to test various combinations of inserting with rowkey and key for different types.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java [hunk 1]
```diff
@@ -323,13 +323,16 @@ private static void handleExplicitKeyField(
...
-        values.putIfAbsent(SchemaUtil.ROWKEY_NAME, keyValue);
-      } else if (!Objects.equals(keyValue, rowKeyValue)) {
-        throw new KsqlException(
-            String.format(
-                "Expected ROWKEY and %s to match but got %s and %s respectively.",
-                key, rowKeyValue, keyValue));
+        if (keyValue == null) {
+          values.putIfAbsent(key, rowKeyValue);
+        } else {
+          // Note, ROWKEY must always be a String, but key might not be so we need toString()
```
Comment (big-andy-coates) [inline ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java]: nit: remove the comment.  It's unnecessary.

File: ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java [hunk 2]
```diff
@@ -323,13 +323,16 @@ private static void handleExplicitKeyField(
...
       if (keyValue != null ^ rowKeyValue != null) {
-        values.putIfAbsent(key, rowKeyValue);
-        values.putIfAbsent(SchemaUtil.ROWKEY_NAME, keyValue);
-      } else if (!Objects.equals(keyValue, rowKeyValue)) {
-        throw new KsqlException(
-            String.format(
-                "Expected ROWKEY and %s to match but got %s and %s respectively.",
-                key, rowKeyValue, keyValue));
+        if (keyValue == null) {
+          values.putIfAbsent(key, rowKeyValue);
```
Comment (big-andy-coates) [inline ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java]: with the guarding `if` block, this can now just be:

```suggestion
          values.put(key, rowKeyValue);
```

Right? 

Likewise for the one below.

File: ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json [hunk 3]
```diff
@@ -66,6 +66,138 @@
         {"topic": "test_topic", "key": "10", "value": {"ID": null}}
       ]
     },
+    {
+      "name": "rowkey should be set when stream has int key and only id specified in insert",
```
Comment (big-andy-coates) [inline ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json]:
```suggestion
      "name": "rowkey should be set when stream has int key and only key field specified in insert",
```

What's important here is not that a field named `id` is set, but that the key field is set.

Same for other tests.

File: ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json [hunk 4]
```diff
@@ -66,6 +66,138 @@
...
+        "INSERT INTO TEST (ID) VALUES (TRUE);"
+      ],
+      "inputs": [
+      ],
+      "outputs": [
+        {"topic": "test_topic", "key": "true", "value": {"ID": true}}
+      ]
+    },
+    {
+      "name": "id should be set when stream has string key and only rowkey specicified in insert",
```
Comment (big-andy-coates) [inline ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json]: Likewise

```suggestion
      "name": "key field should be set when stream has string key and only rowkey specified in insert",
```

Same for other tests

File: ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json [hunk 5]
```diff
@@ -66,6 +66,138 @@
...
+        "INSERT INTO TEST (ROWKEY) VALUES ('10');"
+      ],
+      "inputs": [
+      ],
+      "outputs": [
+        {"topic": "test_topic", "key": "10", "value": {"ID": "10"}}
+      ]
+    },
+    {
+      "name": "rowkey and id should match when stream has int key",
```
Comment (big-andy-coates) [inline ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json]:
```suggestion
      "name": "rowkey and key field should match when stream has int key",
```

same for others

File: ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json [hunk 6]
```diff
@@ -77,6 +209,18 @@
         "message": "Failed to prepare statement: Expected number columns and values to match: [ROWKEY, ID], ['10']",
         "status": 400
       }
+    },
+    {
+      "name": "should fail on mismatch between rowkey and id values when stream has key",
```
Comment (big-andy-coates) [inline ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json]:
```suggestion
      "name": "should fail on mismatch between rowkey and key field values when stream has key field",
```
