### PR TITLE
fix: use schema in annotation as schema provider if present

### LINKED ISSUE #5164: UDF with Generic return type can't handle Decimal fields
**Describe the bug**
Regression in how UDF's handle functions with generic return type with Decimal parameters (Array, Map, Struct). Present after 5.4.x branch

**To Reproduce**
Add this UDF
```

import java.math.BigDecimal;
import java.math.RoundingMode;
import org.apache.kafka.connect.data.Decimal;
import org.apache.kafka.connect.data.Schema;
import org.apache.kafka.connect.data.SchemaBuilder;
import org.apache.kafka.connect.data.Struct;

@UdfDescription(name = "DecimalStructUdf", description = "return a decimal")
public class DecimalStructUdf {

  @Udf(schema = "STRUCT<VAL DECIMAL(64,2)>")
  public Struct getDecimalStruct() {
    final Schema schema = SchemaBuilder.struct()
        .optional()
        .field("VAL",
            Decimal.builder(2).optional().parameter("connect.decimal.precision", "64").build())
        .build();

    Struct struct = new Struct(schema);
    struct.put("VAL", BigDecimal.valueOf(123.45).setScale(2, RoundingMode.CEILING));
    return struct;
  }
}
```
Run
```
ksql> select decimalstructudf() from KSQL_PROCESSING_LOG emit changes limit 2;
```

**Expected behavior**
The query starts streaming.

**Actual behaviour**
Errors with `Cannot convert param type to sql type: DECIMAL`

**Additional context**
I believe the issue is that Decimal is missing in this class https://github.com/confluentinc/ksql/blob/master/ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SchemaConverters.java#L353
`toSqlType` is called on the UDF schema, which fails with that exception since DECIMAL isn't checked for.

### PR DESCRIPTION
**Pull request by agavra**
fixes #5164
replaces #5190 

### Description 

This change (1) eagerly resolves the return type if possible to fail early if a function cannot be loaded and (2) skips resolving the java type to a sql type if the udf annotation contains the `schema` field.

Thanks @stevenpyzhang for exploring the issue!

### Testing done 

Lots of new unit tests and end-to-end testing with the UDF linked in the ticket.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java [hunk 1]
```diff
@@ -180,17 +180,27 @@ static ParamType getReturnType(
...
     final Function<List<SqlType>, SqlType> schemaProvider;
-    if (!schemaProviderFunctionName.equals("")) {
+    if (!Udf.NO_SCHEMA_PROVIDER.equals(schemaProviderFunctionName)) {
       schemaProvider = handleUdfSchemaProviderAnnotation(
           schemaProviderFunctionName, theClass, functionName);
-    } else if (javaReturnSchema instanceof DecimalType) {
-      throw new KsqlException(String.format("Cannot load UDF %s. BigDecimal return type "
-          + "is not supported without a schema provider method.", functionName));
+    } else if (!Udf.NO_SCHEMA.equals(annotationSchema)) {
+      schemaProvider = args -> parser.parse(annotationSchema).getSqlType();
```
Comment (big-andy-coates) [inline ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java:194]: Is it worth parsing once, and failing early, rather than on each call?  Or is this not really an issue?

File: ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java [hunk 2]
```diff
@@ -180,17 +180,27 @@ static ParamType getReturnType(
...
+    } else if (!GenericsUtil.hasGenerics(javaReturnSchema)) {
+      final SqlType sqlType;
+      try {
+        sqlType = SchemaConverters.functionToSqlConverter().toSqlType(javaReturnSchema);
+      } catch (final Exception e) {
+        throw new KsqlException("Cannot load UDF " + functionName + ". "
+            + javaReturnSchema + " return type is not supported without a schema annotation.");
+      }
+      schemaProvider = args -> sqlType;
```
Comment (big-andy-coates) [inline ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java:203]: This method is getting large - consider moving this code into its own function?

File: ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java [hunk 3]
```diff
@@ -180,17 +180,27 @@ static ParamType getReturnType(
...
-          + "is not supported without a schema provider method.", functionName));
+    } else if (!Udf.NO_SCHEMA.equals(annotationSchema)) {
+      schemaProvider = args -> parser.parse(annotationSchema).getSqlType();
+    } else if (!GenericsUtil.hasGenerics(javaReturnSchema)) {
+      final SqlType sqlType;
+      try {
+        sqlType = SchemaConverters.functionToSqlConverter().toSqlType(javaReturnSchema);
+      } catch (final Exception e) {
+        throw new KsqlException("Cannot load UDF " + functionName + ". "
+            + javaReturnSchema + " return type is not supported without a schema annotation.");
```
Comment (big-andy-coates) [inline ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java:201]: Either a schema _or schemaProvider_ is required, right?

... and users may find 'schema annotation;' confusing, given the 'schema' is the name of a property of the annotation, not the name of the annotation.

Maybe:

```suggestion
        throw new KsqlException("Cannot load UDF " + functionName + ". "
            + javaReturnSchema + " return type is not supported without either a schema or schemaProvider set in the annotation.");
```

Though even better would be to pass down the type of the annotation so that the error could be explicit and say `set in the @Udf annotation`, or `in the @Udtf annotation` etc.

Comment (agavra) [reply ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java:201]: I changed the error to clarify, but did not pass down the annotation. I think it's clear enough without it :)
