### PR TITLE
fix: make api client recognize ddl warnings better

### LINKED ISSUE #9253: Ksql migration tool fails when using create with if not exists condition
**Describe the bug**
Ksql migration tool fails when using create table statement with a if not exists condition. Possibly only happens when the table already exists as the ksql client fails to parse the received result in that case.

**To Reproduce**
Using docker image: confluentinc/ksqldb-server:0.26.0

migrations/V000001__Baseline.sql

```
create table if not exists tasks
(
    taskId varchar primary key
) with (kafka_topic='tasks', value_format='json', partitions=1);
```

Using command:
`ksql-migrations apply -c ./ksql-migrations.properties -a`

**Expected behavior**
Applying migration should succeed.

**Actual behaviour**
Tool output:

```
Validating current migration state before applying new migrations
Loading migration files
1 migration file(s) loaded.
Applying migration version 1: Baseline
./migrations/V000001__Baseline.sql contents:
create table if not exists tasks
(
    taskId varchar primary key
) with (kafka_topic='tasks', value_format='json', partitions=1);

Failed to execute sql: create table if not exists tasks
(
    taskId varchar primary key
) with (kafka_topic='tasks', value_format='json', partitions=1);. Error: io.confluent.ksql.api.client.exception.KsqlClientException: The ksqlDB server accepted the statement issued via executeStatement(), but the response received is of an unexpected format. The executeStatement() method is only for 'CREATE', 'CREATE ... AS SELECT', 'DROP', 'TERMINATE', and 'INSERT INTO ... AS SELECT' statements. Use the createConnector() method instead.
Execution time: 1.1870 seconds
```

### PR DESCRIPTION
**Pull request by jzaralim**
### Description 
Fixes #9253

Previously, we were identifying DDL warnings by looking for "IF NOT EXISTS" in the command, but that fails when the command is in lower case or has extra spaces.

See discussion in #8322 for context on why we are filtering warning responses to begin with.

### Testing done 
Unit + integration

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlResponseHandlers.java [hunk 1]
```diff
@@ -73,8 +73,8 @@ private static boolean isCommandStatusEntity(final JsonObject ksqlEntity) {
   }
 
   private static boolean isIfNotExistsWarning(final JsonObject ksqlEntity) {
-    return ksqlEntity.getString("statementText") != null
-        && ksqlEntity.getString("statementText").contains("IF NOT EXISTS")
+    return ksqlEntity.getString("message") != null
+        && ksqlEntity.getString("message").startsWith("Cannot add")
```
Comment (jzaralim) [inline ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlResponseHandlers.java:77]: I don't love this, but this is necessary until we start adding more information to warning entities.

**Review by cprasad1 — APPROVED** [review]
lgtm. Thanks @jzaralim !
