### PR TITLE
Fix handling of table tombstones

### LINKED ISSUE #1169: KSQL dropping tombstone records for tables
Changelog topics for tables can contain tombstone records with null values to indicate that a given key is deleted from a table. KSQL implements tables by creating a KStream on the source topic, doing some transformations to add time/key fields and then using KGroupedStream.reduce to produce a KTable. However the reduce processor ignores null values. For now we should switch to an aggregator that can handle null values.

### PR DESCRIPTION
**Pull request by rodesai**
Changelog topics for tables can contain tombstone records with null values to
indicate that a given key is deleted from a table. KSQL implements tables by
building a KStream over the changelog topic, applying some transformations for
adding columns (one of which Kafka Streams only supports for KStreams), and
then reducing the result into a KTable. The problem is that Kafka Streams
filters out null values in the reduce and aggregation processors for
GroupedKStreams. This patch works around this problem by mapping to
Optional<GenericRow> just before grouping and aggregating into the final
KTable, and then implementing an aggregator for handling Optional.EMPTY as
a tombstone

Fixes #1169

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java [hunk 1]
```diff
@@ -248,34 +249,54 @@ private KTable createKTable(
...
     } else {
       return table(
           builder.stream(
               ksqlTable.getKsqlTopic().getKafkaTopicName(),
-              Consumed.with(Serdes.String(), genericRowSerde).withOffsetResetPolicy(autoOffsetReset)
-          ).mapValues(nonWindowedValueMapper).transformValues(new AddTimestampColumn()),
+              Consumed.with(
+                  Serdes.String(), genericRowSerde).withOffsetResetPolicy(autoOffsetReset))
+              .mapValues(nonWindowedValueMapper)
+              .transformValues(new AddTimestampColumn())
```
Comment (guozhangwang) [inline ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java]: Just wondering: could we just merge these two steps (transformValues and the following mapValues) into a single transformValues? Is it just for code readability?

Comment (rodesai) [reply ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java]: The one that produces the Optional? To do that we'd either need to move the Optional.ofNullable call into one of those mappers (timestamp or key) or do the reverse. I'd rather keep Optional.ofNullable here since its a fairly subtle implementation detail of how we build tables. So it would be best to keep it next to the code thats building the ktable. And doing the reverse I think hurts readability.
