### PR TITLE
fix: Gives a query completed message for stream pull queries

### LINKED ISSUE #8554: SELECT Query not returning a valid JSON
**Describe the bug**
Following the official quickstart tutorial [here](https://ksqldb.io/quickstart.html), after populating the stream with events if you run the following query:

```SQL
"SELECT * FROM riderLocations;"
```

It returns:

```JSON
[
	{
		"header": {
			"queryId": "transient_RIDERLOCATIONS_2722336623052488734",
			"schema": "`PROFILEID` STRING, `LATITUDE` DOUBLE, `LONGITUDE` DOUBLE"
		}
	},
	{
		"row": {
			"columns": [
				"c2309eec",
				37.7877,
				-122.4205
			]
		}
	},
	{
		"row": {
			"columns": [
				"18f4ea86",
				37.3903,
				-122.0643
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				37.3952,
				-122.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				38.3952,
				-122.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				38.3952,
				-122.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				38.3952,
				-122.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				38.3952,
				-121.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ddad000",
				37.7857,
				-122.4011
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ddad000",
				37.7857,
				-122.4011
			]
		}
	},
]
```

Which has an extra comma (",") at the end that brakes any JSON Parser.

**To Reproduce**
Steps to reproduce the behavior, include:
1. Follow the quickstart guide [here](https://ksqldb.io/quickstart.html)
2. Run the query `SELECT * FROM riderLocations;`

**Expected behavior**
The response to be a valid JSON.

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. The response is not a valid JSON

### PR DESCRIPTION
**Pull request by AlanConfluent**
### Description 

fixes #8554 

Stream pull queries current produce invalid json #8554.  

This fix produces a final message for stream pull queries saying "Query Completed".  Normal pull queries keep a row buffered to avoid this bug so that they know if there is another row that follows, allowing them to output a comma or not.  While I could have ported stream pull queries over to the logic of normal pull queries, this would have been a much larger change since stream pull queries resemble push queries much more than pull. Also, a final message is just part of the API, so should be handled regardless of the nature of push, pull, etc.

### Testing done 
Tested examples given in the issue and ran existing tests.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by nateab — APPROVED** [review]
LGTM!

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java [hunk 1]
```diff
@@ -125,6 +125,8 @@ public void write(final OutputStream out) {
 
       if (limitReached) {
         objectMapper.writeValue(out, StreamedRow.finalMessage("Limit Reached"));
+      } else if (complete) {
+        objectMapper.writeValue(out, StreamedRow.finalMessage("Query Completed"));
```
Comment (agavra) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java:129]: Thanks for the fix @AlanConfluent! Can we add test coverage for this?

Comment (AlanConfluent) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java:129]: Sure, added some unit test coverage for both code paths.

**Review by cprasad1 — APPROVED** [review]

**Review by vvcephei — APPROVED** [review]
Thanks, @AlanConfluent ! 

This is ringing a bell... I noticed before that pull queries printed out a final message on the `/query` endoint, but not the `/query-stream` endpoint, and I thought I had emulated that behavior, but apparently I missed something.

Thanks for the patch!
