### PR TITLE
fix: reject incorrectly typed HEADER columns

### LINKED ISSUE #8447: Creating a stream with HEADERS does not fail if I specify a key/value type other than STRING/BYTES
**Describe the bug**
In the following CREATE statement, I used a `hdrs array<struct<key int, value int>> headers` column that has `value` as int. An error should have been thrown 'cause we support only bytes in headers columns.

```
ksql> create stream s1(key string key, message string, hdrs array<struct<key int, value int>> headers) with (kafka_topic='topic1', value_format='delimited');

 Message        
----------------
 Stream created 
----------------
ksql> select key, message, hdrs as appId from s1 emit changes;
+-------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------------------+
|KEY                                                          |MESSAGE                                                      |APPID                                                        |
+-------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------------------+
|1                                                            |message1                                                     |[{KEY=appName, VALUE=a2Fma2FjYXQ=}, {KEY=appId, VALUE=MQ==}] |
|2                                                            |message2                                                     |[{KEY=appName, VALUE=a2Fma2FjYXQ=}, {KEY=appId, VALUE=MQ==}] |
|3                                                            |messag3                                                      |[{KEY=appName, VALUE=a2Fma2FjYXQ=}, {KEY=appId, VALUE=Mg==}] |
|4                                                            |message4                                                     |[{KEY=appId, VALUE=Mw==}]                                    |
|5                                                            |message5                                                     |[]                                                           |
|6                                                            |message6                                                     |[{KEY=appId, VALUE=Mw==}]                                    |
|7                                                            |message7                                                     |[{KEY=appId, VALUE=Mw==}, {KEY=appId, VALUE=NA==}]           |
^CQuery terminated
```

### PR DESCRIPTION
**Pull request by jzaralim**
### Description 
Fixes #8447 

Throws an error if a user tries to create a source with a HEADER column with an incorrect type

### Testing done 
QTT and unit tests

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/TableElements.java [hunk 1]
```diff
@@ -91,6 +95,9 @@ public LogicalSchema toLogicalSchema() {
       if (tableElement.getConstraints().isKey() || tableElement.getConstraints().isPrimaryKey()) {
         builder.keyColumn(fieldName, fieldType);
       } else if (tableElement.getConstraints().isHeaders()) {
+        throwOnIncorrectHeaderColumnType(
```
Comment (spena) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/TableElements.java:98]: I think this check should be done earlier in the `AstBuilder` where the `TableElement` is created. My opinion is that once `TableElement` is created, then `toLogicalSchema` shouldn't fail. This method just converts from one object to another (unsure why isEmpty() fails, but it's already there). Also, the `AstBuilder` may check for invalid syntax, so why I think it should live there. What do you think?

Comment (jzaralim) [reply ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/TableElements.java]: That makes sense. Moved.

**Review by spena — APPROVED** [review]
LGTM
