### PR TITLE
fix: Consider topics created by join operations internal

### LINKED ISSUE #8456: Two internal topics are not cleaned up after terminating query for FK join
**Describe the bug**
Two internal topics(*KTABLE-FK-JOIN-SUBSCRIPTION-RESPONSE* and *KTABLE-FK-JOIN-SUBSCRIPTION-REGISTRATION*)  don't get deleted after terminating query for FK join.

**To Reproduce**
Version 0.21.0 (CP 7.0.0)
1. Create a FK join between tables
```
create table T1_LHS(id struct<id1 varchar, code varchar> primary key, fk1 varchar, desc varchar) with(kafka_topic='T1_LHS_topic',partitions=3,key_format='json',value_format='json');
create table T1_RHS(id struct<id1 varchar> primary key, desc varchar) with(kafka_topic='T1_RHS_topic',partitions=3,key_format='json',value_format='json');
create table T1_JOIN as select T1_RHS.id FK_ID,T1_RHS.desc DESC_RHS,T1_LHS.id LHS_ID, T1_LHS.desc LHS_DESC from T1_LHS INNER JOIN T1_RHS ON STRUCT(ID1 := T1_LHS.FK1) = T1_RHS.ID;
```
2. Check internal topics
```
 _confluent-ksql-default_query_CTAS_T1_JOIN_97-KTABLE-FK-JOIN-SUBSCRIPTION-REGISTRATION-0000000012-topic    | 3          | 1                  
 _confluent-ksql-default_query_CTAS_T1_JOIN_97-KTABLE-FK-JOIN-SUBSCRIPTION-RESPONSE-0000000020-topic        | 3          | 1                  
 _confluent-ksql-default_query_CTAS_T1_JOIN_97-KTABLE-FK-JOIN-SUBSCRIPTION-STATE-STORE-0000000016-changelog | 3          | 1                  
 _confluent-ksql-default_query_CTAS_T1_JOIN_97-KafkaTopic_Left-Reduce-changelog                             | 3          | 1                  
 _confluent-ksql-default_query_CTAS_T1_JOIN_97-KafkaTopic_Right-Reduce-changelog                            | 3          | 1                  
 _confluent-ksql-default_query_CTAS_T1_JOIN_97-Project-Last-changelog                                       | 3          | 1 
```
3.Terminate the query

**Expected behavior**
All internal topics are deleted

**Actual behaviour**
Two internal topics are not deleted

```
- [ ]  _confluent-ksql-default_query_CTAS_T1_JOIN_97-KTABLE-FK-JOIN-SUBSCRIPTION-REGISTRATION-0000000012-topic | 3          | 1                  
- [ ]  _confluent-ksql-default_query_CTAS_T1_JOIN_97-KTABLE-FK-JOIN-SUBSCRIPTION-RESPONSE-0000000020-topic     | 3          | 1  
```

### PR DESCRIPTION
**Pull request by Gerrrr**
### Description 

Fixes #8456.

Ideally, we should probably rely on a standard predicate in KStreams, but given this issue is a release blocker, we can probably introduce this predicate to KStreams and update ksql's dependency in follow-up PRs.

### Testing done 

* Added a unit test
* Double-checked that ksqlDB's classification of internal topics matches [KStreams' one](https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/tools/StreamsResetter.java#L683-L690).

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java [hunk 1]
```diff
@@ -447,20 +447,26 @@ public void shouldToCallOutToKafkaIfDeleteListIsEmpty() {
...
     // Given:
     final String applicationId = "whatEva";
-    final String internalTopic1 = applicationId + "-something-repartition";
-    final String internalTopic2 = applicationId + "-someting-changelog";
+    final String internalTopic1 = applicationId
+        + "-KTABLE-FK-JOIN-SUBSCRIPTION-REGISTRATION-0000000012-topic";
+    final String internalTopic2 = applicationId
+        + "-KTABLE-FK-JOIN-SUBSCRIPTION-RESPONSE-0000000012-topic";
+    final String internalTopic3 = applicationId + "-something-repartition";
+    final String internalTopic4 = applicationId + "-someting-changelog";
```
Comment (suhas-satish) [inline ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java:455]: nit: typo in something

**Review by suhas-satish — APPROVED** [review]

File: ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java (hunk 1 above)
Comment (Gerrrr) [reply ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java]: Fixed in https://github.com/confluentinc/ksql/pull/8520/commits/0c9865e57da8e53df2ca3191011ffaa8d5bf5be6#diff-dfb8a82a63edbd6892fa746e000c798422084f930fb0499e1d434f9bcf32ac9cR454-R455.

File: ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java [hunk 2]
```diff
@@ -370,10 +371,13 @@ private Config getConfig() {
...
   }
 
+  @SuppressWarnings("checkstyle:BooleanExpressionComplexity")
   private static boolean isInternalTopic(final String topicName, final String applicationId) {
     return topicName.startsWith(applicationId + "-")
         && (topicName.endsWith(KsqlConstants.STREAMS_CHANGELOG_TOPIC_SUFFIX)
-        || topicName.endsWith(KsqlConstants.STREAMS_REPARTITION_TOPIC_SUFFIX));
+        || topicName.endsWith(KsqlConstants.STREAMS_REPARTITION_TOPIC_SUFFIX))
+        || topicName.matches(KsqlConstants.STREAMS_JOIN_REGISTRATION_TOPIC_PATTERN)
+        || topicName.matches(KsqlConstants.STREAMS_JOIN_RESPONSE_TOPIC_PATTERN);
```
Comment (cadonna) [inline ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java:380]: This expression does not seem completely correct. Currently it is `A && (B || C) || D || E`. Shouldn't it be `A && (B || C || D || E)`? Maybe that is also the reason you get a checkstyle error that you need to suppress.
If I am right, then we are missing some tests that check the negative case.

**Review by cadonna — COMMENTED** [review]
@Gerrrr Thank you for the PR!

I have a doubt about the expression to determine the internal topics.

File: ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java (hunk 2 above)
Comment (Gerrrr) [reply ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java]: Good catch! I fixed it and added checks for the negative cases in 9e2652e.

**Review by cadonna — APPROVED** [review]
LGTM!

**Comment by Gerrrr** [comment]
Even though CI is broken, I think that it is ok to merge it because:
* There was a green build (and other builds with unrelated failures) before the CI broke.
* The change itself is very much isolated and likely won't affect other tests.
* I tested the change locally.
* The issue is a release blocker.
