### PR TITLE
Fix some more rest api inconsistencies

### LINKED ISSUE #1199: inconsistencies in rest endpoint
there are a number of inconsistencies in the rest endpoint that i think should be addressed

for queries:
```
[
  {
    "@type": "queries",
    "statementText": "show queries;",
    "queries": [
      {
        "queryString": "create stream blah as select * from BLAH;",
        "kafkaTopic": "BLAH",
        "id": {
          "id": "CSAS_BLAH"
        }
      }
    ]
  },
  {
    "@type": "query_descriptions",
    "statementText": "show queries extended;",
    "queryDescriptions": [
      {
        "id": {
          "id": "CSAS_BLAH"
        },
        "statementText": "create stream blah as select * from BLAH;",
        "schema": [
          {
            "name": "ROWTIME",
            "type": "BIGINT"
          },
          {
            "name": "ROWKEY",
            "type": "VARCHAR(STRING)"
          },
          {
            "name": "REGISTERTIME",
            "type": "BIGINT"
          },
          {
            "name": "GENDER",
            "type": "VARCHAR(STRING)"
          },
          {
            "name": "REGIONID",
            "type": "VARCHAR(STRING)"
          },
          {
            "name": "USERID",
            "type": "VARCHAR(STRING)"
          }
        ],
        "sources": [
          "BLAH"
        ],
        "sinks": [],
        "topology": "Topologies:\n   Sub-topology: 0\n    Source: KSTREAM-SOURCE-0000000000 (topics: [_confluent-metrics])\n      --> KSTREAM-MAPVALUES-0000000001\n    Processor: KSTREAM-MAPVALUES-0000000001 (stores: [])\n      --> KSTREAM-TRANSFORMVALUES-0000000002\n      <-- KSTREAM-SOURCE-0000000000\n    Processor: KSTREAM-TRANSFORMVALUES-0000000002 (stores: [])\n      --> KSTREAM-MAPVALUES-0000000003\n      <-- KSTREAM-MAPVALUES-0000000001\n    Processor: KSTREAM-MAPVALUES-0000000003 (stores: [])\n      --> KSTREAM-MAPVALUES-0000000004\n      <-- KSTREAM-TRANSFORMVALUES-0000000002\n    Processor: KSTREAM-MAPVALUES-0000000004 (stores: [])\n      --> KSTREAM-SINK-0000000005\n      <-- KSTREAM-MAPVALUES-0000000003\n    Sink: KSTREAM-SINK-0000000005 (topic: BLAH)\n      <-- KSTREAM-MAPVALUES-0000000004\n\n",
        "executionPlan": " > [ SINK ] Schema: [ROWTIME : INT64 , ROWKEY : STRING , REGISTERTIME : INT64 , GENDER : STRING , REGIONID : STRING , USERID : STRING].\n\t\t > [ PROJECT ] Schema: [ROWTIME : INT64 , ROWKEY : STRING , REGISTERTIME : INT64 , GENDER : STRING , REGIONID : STRING , USERID : STRING].\n\t\t\t\t > [ SOURCE ] Schema: [BLAH.ROWTIME : INT64 , BLAH.ROWKEY : STRING , BLAH.REGISTERTIME : INT64 , BLAH.GENDER : STRING , BLAH.REGIONID : STRING , BLAH.USERID : STRING].\n",
        "overriddenProperties": {}
      }
    ]
  }
]
```
the first response returns in an object named `queries` whereas the extended version is `queryDescriptions`
the first response returns the query as `queryString` whereas the extended version is `statementText`
both embed `id` an extra level deep
the extended description `sinks` array is empty, but I believe it should have the value from the first query's `kafkaTopic` in it
can we use `topic` instead of `kafkaTopic`?

for streams/tables:
```
[
  {
    "@type": "streams",
    "statementText": "show streams;",
    "streams": [
      {
        "type": "STREAM",
        "name": "DERP",
        "topic": "derp",
        "format": "JSON"
      }
  },
  {
    "@type": "source_descriptions",
    "statementText": "show streams extended;",
    "sourceDescriptions": [
      {
        "name": "DERP",
        "readQueries": [],
        "writeQueries": [],
        "schema": [
          {
            "name": "ROWTIME",
            "type": "BIGINT"
          },
          {
            "name": "ROWKEY",
            "type": "VARCHAR(STRING)"
          },
          {
            "name": "REGISTERTIME",
            "type": "BIGINT"
          },
          {
            "name": "GENDER",
            "type": "VARCHAR(STRING)"
          },
          {
            "name": "REGIONID",
            "type": "VARCHAR(STRING)"
          },
          {
            "name": "USERID",
            "type": "VARCHAR(STRING)"
          }
        ],
        "type": "STREAM",
        "key": "SOMETHING_KEYFUL",
        "timestamp": "",
        "statistics": "",
        "errorStats": "",
        "extended": true,
        "serdes": "JSON",
        "topic": "derp",
        "replication": 1,
        "partitions": 12
      }
  }
]
```

the first response returns in an object named `streams/tables` whereas the extended version is `queryDescriptions`
the first response returns in an object named `format` whereas the extended version is `serdes`

### LINKED ISSUE #1206: incorrect values in readQueries/writeQueries on extended source description
result for a `show streams extended;` will have something like 
```      {
        "name": "WHATEVER",
        "readQueries": [
          "CSAS_WHATEVER : create stream WHATEVER as select * from blah;"
        ],
        "writeQueries": [
          "id:CSAS_WHATEVER - create stream WHATEVER as select * from blah;"
        ],
```

a couple of issues

1. both `(read|write)Queries` have ~ the same data, but at least one should be different (not sure which means which tbh)
1. they are formatted differently, but convey the same information
1. we are embedding the id data, `CSAS_WHATEVER in this case, in a string rather than in a readable field

### PR DESCRIPTION
**Pull request by rodesai**
- Use the name sourceDescription(s) for fields that contain a
SourceDescription or List<SourceDescription>
- Use the name queryDescription(s) for fields that contain a
QueryDescription or List<QueryDescription>
- List sinks in the RunningQuery object (instead of a topic name)
- Return a simple string for query ids
- Include sinks in QueryDescriptions. Previously we had a bug where
they were not being listed.
- Display read queries in SourceDescriptions. Previously we had a bug
where readQueries actually listed queries writing into a source
- Return RunningQuery objects in SourceDescription

Fixes #1199
Fixes #1206

### CODE REVIEW

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java [hunk 1]
```diff
@@ -385,10 +386,11 @@ private void printAsTable(KsqlEntity ksqlEntity) {
           .withColumnHeaders(PROPERTIES_COLUMN_HEADERS)
           .withRows(propertiesRowValues(properties));
     } else if (ksqlEntity instanceof Queries) {
-      List<Queries.RunningQuery> runningQueries = ((Queries) ksqlEntity).getQueries();
+      List<RunningQuery> runningQueries = ((Queries) ksqlEntity).getQueries();
       tableBuilder.withColumnHeaders("Query ID", "Kafka Topic", "Query String");
       runningQueries.forEach(
-          r -> tableBuilder.withRow(r.getId().toString(), r.getKafkaTopic(), r.getQueryString()));
+          r -> tableBuilder.withRow(
+              r.getId().toString(), String.join(",", r.getSinks()), r.getQueryString()));
```
Comment (dguy) [inline ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java]: nit: don't need the `toString()`

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java [hunk 2]
```diff
@@ -34,7 +33,7 @@
 
 public class QueryDescription {
 
-  private final QueryId id;
+  private final String id;
```
Comment (dguy) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java]: Why do we need to change this to a `String`? `QueryId` describes what it is, `String` doesn't. I presume there is a valid reason?

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java [hunk 3]
```diff
@@ -173,7 +173,7 @@ public String getType() {
   }
 
   public String getSerdes() {
-    return serdes;
+    return format;
```
Comment (dguy) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java]: perhaps we should rename the method? it isn't really getting the serdes??

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java [hunk 4]
```diff
@@ -410,44 +412,25 @@ private SourceDescription describe(String name, boolean extended) throws KsqlExc
...
+        getQueries(q -> q.getSourceNames().contains(dataSource.getName())),
+        getQueries(q -> q.getSinkNames().contains(dataSource.getName())),
         ksqlEngine.getTopicClient()
     );
   }
 
-  private List<String> getReadQueryIds(List<PersistentQueryMetadata> queries) {
-    return queries
+  private List<RunningQuery> getQueries(Predicate<PersistentQueryMetadata> predicate) {
+    return ksqlEngine.getPersistentQueries().values()
```
Comment (dguy) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java]: How about we add a method on `ksqlEngine`? something like `getPersistentQueryMetadata` or similar so we aren't exposing the internals so much? i.e., we should be trying to push functionality into the objects themselves as much as possible rather than exposing the internal structure?

File: ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java [hunk 5]
```diff
@@ -415,14 +400,14 @@ public void shouldReturnDescriptionsForShowTablesExtended() throws Exception {
         hasItem(
             new SourceDescription(
                 testResource.getKsqlEngine().getMetaStore().getSource("TEST_TABLE"),
-                true, "JSON", Collections.EMPTY_LIST, Collections.EMPTY_LIST,
+                true, "JSON", Collections.emptyList(), Collections.emptyList(),
```
Comment (dguy) [inline ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java]: nice tidy-ups!

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java (hunk 2 above)
Comment (norwood) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java]: all queryid contains is the id. it makes dealing with this field annoying

```    "queryDescriptions": [
      {
        "id": {
          "id": "CSAS_BLAH"
        },
```

Comment (rodesai) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java]: I think rendering QueryId as an API object is also bad because its not part of the entities package, which makes the api more prone to breakage (since someone may change QueryId without realizing its used to render api objects).

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java (hunk 4 above)
Comment (rodesai) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java]: How about an interface for getting a Collection of all queries and an interface for getting a specific query by ID? It seems gratuitous to push the filtering stuff in. I think it's reasonable to return a Collection and leverage the java.util stuff to warp it into the needed form on the client side.

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java (hunk 2 above)
Comment (big-andy-coates) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java]: You can add a _thing_ to Jackson so that you can leave it as a `QueryId` in the model, (which is more descriptive / typesafe from the Java standpoint, as @dguy notes), while having it render to Json as just `"id" "CSAS_BLAH"` - just need to remember / find what the _thing_ was... I've done it before... hang on...

Comment (big-andy-coates) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java]: Found it - you can add a `@JsonValue` to the `getId` or `toString` method of `QueryId` and it will render without the superfluous nesting and id field.... best of both worlds! :D

File: ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java [hunk 6]
```diff
@@ -478,8 +479,14 @@ public boolean terminateQuery(final QueryId queryId, final boolean closeStreams)
     return true;
   }
 
-  public Map<QueryId, PersistentQueryMetadata> getPersistentQueries() {
-    return new HashMap<>(persistentQueries);
+  public PersistentQueryMetadata getPersistentQuery(QueryId queryId) {
+    return persistentQueries.get(queryId);
+  }
+
+  public Collection<PersistentQueryMetadata> getPersistentQueries() {
```
Comment (big-andy-coates) [inline ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java]: Any reason not to return  `List<PQM>` so users can benefit from richer API?

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java (hunk 2 above)
Comment (big-andy-coates) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java]: @JsonValue rocks! :D

Comment (dguy) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java]: Yep, how it is rendered via json etc is a different concern to how it is represented in the model.

Comment (rodesai) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java]: Agree on the separation of concerns. My point was that we should keep the api model classes decoupled from everything else. I'll add a new class for query ids in the model. I'll do this in another PR so that c3 is unblocked.

**Comment by rodesai** [comment]
Merging this and fixing the QueryId stuff in another PR.
