### PR TITLE
Ksql 919 assert correct conversion in string time udfs

### LINKED ISSUE #919: StringToTimestampTest and TimestampToStringTest fail in machines with time local other than UTC
`TimestampToStringTest` and `StringToTimestampTest` assertions are based on the time in UTC. So some of the tests fail when they run on machines with different local time.

### PR DESCRIPTION
**Pull request by hjafarpour**
Use the local time to assert test correctness, otherwise, tests will fail because of using UTC.
This fixes #919

### CODE REVIEW

File: ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToTimestampTest.java [hunk 1]
```diff
@@ -84,7 +90,12 @@ public void shouldBeThreadSafe() {
     IntStream.range(0, 10_000)
         .parallel()
         .forEach(idx -> {
-          shouldCovertStringToTimestamp();
+          try {
+            shouldCovertStringToTimestamp();
+          } catch (ParseException e) {
+            e.printStackTrace();
```
Comment (ewencp) [inline ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToTimestampTest.java]: guess this is fine since it's just test code, but is this here for something other than debugging? seems like the ParseException should be enough to indicate something is wrong and then you could just try to reproduce locally under a debugger.

Comment (dguy) [reply ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToTimestampTest.java]: perhaps fail with the message from the `ParseException`?

Comment (hjafarpour) [reply ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToTimestampTest.java]: Used the ParseException message for fail as @dguy suggested.
