### PR TITLE
#1938 GEO_DISTANCE function broken by new UDF Invoker

### LINKED ISSUE #1938: GEO_DISTANCE function broken by new UDF Invoker
The scalar functions which existed prior to the introduction of the new UDF support could make use of null-checking on their trailing input arguments to provide support for optional parameters. (i.e. if the last 2 parameteres are considered optional, and the function code correctly handles them being null, everything works as intended).

When we introduced the new UDF framework, and moved to using it to invoke the older functions too, in 5.0 the support for this functionality was broken and replaced by an assumption that any function wanting to support optional parameters would implement a separate constructor per parameter-permutation it wanted to support.

A quick pass through the codebase shows only 2 functions impacted by this, `substring` and `geo_distance`, and `substring` was fixed during the UDF migration. This leaves `geo_distance` to fix up to allow its last parameter to be treated as optional once again.

### PR DESCRIPTION
**Pull request by uurl**
### Description 
This PR fixes #1938 GEO_DISTANCE function broken by new UDF Invoker 

### Testing done 
mvn clean package

### Reviewer checklist
- [x] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [x] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 1]
```diff
@@ -44,20 +50,28 @@
...
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
+        final double lat1,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
+        final double lon1,
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
+        final double lat2,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
+        final double lon2,
+      @UdfParameter(description = "The chosen Earth radius.")
+        final String... radius) {
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]: instead of using variable-arguments here I recommend polymorphism (i.e. have two methods, one with the radius and one without). This should fully support backwards compatibility

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 2]
```diff
@@ -18,17 +18,23 @@
...
- * 
+ *
  * <p>An optional fifth parameter allows to specify either "MI" (miles) or "KM" (kilometers) as the
  * desired unit for the output measurement. Default is KM.
- *
  */
+@UdfDescription(name = "geodistance", author = "Confluent",
+    description = "Compute the distance between two points on the surface of the earth,"
+        + " according to the Haversine formula for \"great circle distance\".")
 public class GeoDistanceKudf implements Kudf {
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
 public class GeoDistanceKudf  {
```
You don't need to implement `Kudf` with the new UDF framework, and then you can also remove the `evaluate` method

File: ksql-engine/src/test/resources/query-validation-tests/geodistance.json [hunk 3]
```diff
@@ -0,0 +1,34 @@
+{
+  "tests": [
+    {
+      "name": "geo distance",
```
Comment (agavra) [inline ksql-engine/src/test/resources/query-validation-tests/geodistance.json]: this is great! can you also add another test for the case where radius isn't supplied at all?

File: ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java [hunk 4]
```diff
@@ -262,16 +260,6 @@ private void addMathFunctions() {
 
     private void addGeoFunctions() {
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java]: you can delete the whole method :)

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 5]
```diff
@@ -71,6 +79,22 @@ public Object evaluate(final Object... args) {
...
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
+      final double lat1,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
+      final double lon1,
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
+      final double lat2,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
+      final double lon2) {
+
+    return this.geoDistance(lat1, lon1, lat2, lon2, "KM");
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
    return geoDistance(lat1, lon1, lat2, lon2, VALID_RADIUS_NAMES_KMS.get(0));
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 6]
```diff
@@ -71,6 +79,22 @@ public Object evaluate(final Object... args) {
     return distanceInRadians * chosenRadius;
   }
 
+  @Udf(description = "The 2 input points should be specified as (lat, lon) pairs, measured"
+      + " in decimal degrees. An optional fifth parameter allows to specify either \"MI\" (miles)"
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
      + " in decimal degrees. The distance returned is in kilometers.";
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 7]
```diff
@@ -85,19 +109,18 @@ private void validateLatLonValues(
     }
   }
 
-  private double selectEarthRadiusToUse(final Object... args) {
+  private double selectEarthRadiusToUse(final String... radius) {
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
  private double selectEarthRadiusToUse(final String radius) {
```
No need to pass in varargs here either

File: ksql-engine/src/test/resources/query-validation-tests/geodistance.json [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+      "name": "geo_distance",
+      "statements": [
+        "CREATE STREAM TEST (ID bigint, LAT1 double, LON1, double, LAT2, double, LON2 double, RADIUS varchar) WITH (kafka_topic='test_topic', value_format='JSON');",
+        "CREATE STREAM DISTANCE_STREAM AS select ID, geo_distance(LAT1, LON1, LAT2, LON2, RADIUS) as CALCULATED_DISTANCE from test;"
+      ],
+      "inputs": [
+        {"topic": "test_topic", "value": {"ID": 1, "LAT1": 37.4439, "LON1": -122.1663, "LAT2": 51.5257, "LON2": -0.1122}},
+        {"topic": "test_topic", "value": {"ID": 2, "LAT1": 37.4439, "LON1": -122.1663, "LAT2": 51.5257, "LON2": -0.1122}, "RADIUS": "KM"},
+        {"topic": "test_topic", "value": {"ID": 3, "LAT1": 37.4439, "LON1": -122.1663, "LAT2": 51.5257, "LON2": -0.1122}, "RADIUS": "MI"},
+        {"topic": "test_topic", "value": {"ID": 4, "LAT1": 51.5257, "LON1": -0.1122, "LAT2": -33.9323, "LON2": 18.4197}},
```
Comment (agavra) [inline ksql-engine/src/test/resources/query-validation-tests/geodistance.json]: nit: this is a good test to have, but I meant to have another test suite with
```
      "statements": [
        "CREATE STREAM TEST (ID bigint, LAT1 double, LON1, double, LAT2, double, LON2 double) WITH (kafka_topic='test_topic', value_format='JSON');",
        "CREATE STREAM DISTANCE_STREAM AS select ID, geo_distance(LAT1, LON1, LAT2, LON2) as CALCULATED_DISTANCE from test;"
      ],
```
To test the case where the UDF is called with only 4 params (not a null 5th param)

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 9]
```diff
@@ -44,20 +49,23 @@
...
+  public Object geoDistance(
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
+        final double lat1,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
+        final double lon1,
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
+        final double lat2,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
+        final double lon2,
+      @UdfParameter(description = "The chosen Earth radius.")
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
      @UdfParameter(description = "The units for the return value.")
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 10]
```diff
@@ -44,20 +49,23 @@
   private static final List<String> VALID_RADIUS_NAMES_KMS =
       Lists.newArrayList("km", "kilometer", "kilometers", "kilometre", "kilometres");
 
+  @Udf(description = "The 2 input points should be specified as (lat, lon) pairs, measured"
+      + " in decimal degrees. An optional fifth parameter allows to specify either \"MI\" (miles)"
+      + " or \"KM\" (kilometers) as the desired unit for the output measurement. Default is KM.")
+  public Object geoDistance(
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
  public Double geoDistance(
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 11]
```diff
@@ -71,6 +79,22 @@ public Object evaluate(final Object... args) {
     return distanceInRadians * chosenRadius;
   }
 
+  @Udf(description = "The 2 input points should be specified as (lat, lon) pairs, measured"
+      + " in decimal degrees. An optional fifth parameter allows to specify either \"MI\" (miles)"
+      + " or \"KM\" (kilometers) as the desired unit for the output measurement. Default is KM.")
+  public Object geoDistance(
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
  public Double geoDistance(
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 12]
```diff
@@ -85,19 +109,18 @@ private void validateLatLonValues(
...
-      final String outputUnit = args[4].toString().toLowerCase();
+    if (radius != null && radius.length > 0) {
+      final String outputUnit = radius[0].toLowerCase();
       if (VALID_RADIUS_NAMES_MILES.contains(outputUnit)) {
         chosenRadius = EARTH_RADIUS_MILES;
       } else if (VALID_RADIUS_NAMES_KMS.contains(outputUnit)) {
         chosenRadius = EARTH_RADIUS_KM;
       } else {
         throw new KsqlFunctionException(
             "GeoDistance function fifth parameter must be ('MI' or 'miles')"
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
            "GeoDistance function fifth parameter must be one of " + VALID_RADIUS_NAMES_MILES + " or " + VALID_RADIUS_NAMES_KMS
```

File: ksql-engine/src/test/resources/query-validation-tests/geodistance.json [hunk 13]
```diff
@@ -0,0 +1,35 @@
...
+        {"topic": "test_topic", "value": {"ID": 5, "LAT1": 51.5257, "LON1": -0.1122, "LAT2": -33.9323, "LON2": 18.4197}, "RADIUS": "KM"},
```
Comment (agavra) [inline ksql-engine/src/test/resources/query-validation-tests/geodistance.json]:
```suggestion
        {"topic": "test_topic", "value": {"ID": 5, "LAT1": 51.5257, "LON1": -0.1122, "LAT2": -33.9323, "LON2": 18.4197, "RADIUS": "KM"}},
```
Same for other elements of this test, RADIUS needs to be within the value.

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 14]
```diff
@@ -85,19 +108,18 @@ private void validateLatLonValues(
...
       if (VALID_RADIUS_NAMES_MILES.contains(outputUnit)) {
         chosenRadius = EARTH_RADIUS_MILES;
       } else if (VALID_RADIUS_NAMES_KMS.contains(outputUnit)) {
         chosenRadius = EARTH_RADIUS_KM;
       } else {
         throw new KsqlFunctionException(
-            "GeoDistance function fifth parameter must be ('MI' or 'miles')"
-            + " or ('KM' or 'kilometers')."
-            + " Values are case-insensitive.");
+            "GeoDistance function fifth parameter must be one of " + VALID_RADIUS_NAMES_MILES
```
Comment (agavra) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
            "GeoDistance function radius parameter must be one of " + VALID_RADIUS_NAMES_MILES
```

**Comment by uurl** [comment]
@agavra @rodesai @vcrfxia @big-andy-coates Ready

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 15]
```diff
@@ -44,20 +49,23 @@
   private static final List<String> VALID_RADIUS_NAMES_KMS =
       Lists.newArrayList("km", "kilometer", "kilometers", "kilometre", "kilometres");
 
+  @Udf(description = "The 2 input points should be specified as (lat, lon) pairs, measured"
+      + " in decimal degrees. An optional fifth parameter allows to specify either \"MI\" (miles)"
+      + " or \"KM\" (kilometers) as the desired unit for the output measurement. Default is KM.")
+  public Double geoDistance(
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
+        final double lat1,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
```
Comment (vcrfxia) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
      @UdfParameter(description = "The longitude of the first point in decimal degrees.")
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 16]
```diff
@@ -44,20 +49,23 @@
...
+        final double lon1,
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
```
Comment (vcrfxia) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
      @UdfParameter(description = "The latitude of the second point in decimal degrees.")
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 17]
```diff
@@ -44,20 +49,23 @@
...
+        final double lat2,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
+        final double lon2,
+      @UdfParameter(description = "The units for the return value.")
+        final String radius) {
```
Comment (vcrfxia) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
        final String units) {
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 18]
```diff
@@ -71,6 +79,21 @@ public Object evaluate(final Object... args) {
     return distanceInRadians * chosenRadius;
   }
 
+  @Udf(description = "The 2 input points should be specified as (lat, lon) pairs, measured"
+      + " in decimal degrees. The distance returned is in kilometers.")
+  public Double geoDistance(
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
+      final double lat1,
+      @UdfParameter(description = "The longitude of the second point in decimal degrees.")
```
Comment (vcrfxia) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
      @UdfParameter(description = "The longitude of the first point in decimal degrees.")
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 19]
```diff
@@ -71,6 +79,21 @@ public Object evaluate(final Object... args) {
...
+      final double lon1,
+      @UdfParameter(description = "The latitude of the first point in decimal degrees.")
```
Comment (vcrfxia) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
      @UdfParameter(description = "The latitude of the second point in decimal degrees.")
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 20]
```diff
@@ -85,19 +108,18 @@ private void validateLatLonValues(
     }
   }
 
-  private double selectEarthRadiusToUse(final Object... args) {
+  private double selectEarthRadiusToUse(final String radius) {
```
Comment (vcrfxia) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]:
```suggestion
  private double selectEarthRadiusToUse(final String units) {
```

File: ksql-engine/src/test/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudfTest.java [hunk 21]
```diff
@@ -60,41 +60,27 @@ public void shouldComputeDistanceDifferentHemisphere() {
...
+    expectedException.expectMessage("valid latitude values for GeoDistance function");
+    distanceUdf.geoDistance(90.1, -122.1663, -91.5257, -0.1122);
   }
 
   @Test
   public void shouldFailInvalidUnitOfMeasure() {
     expectedException.expect(KsqlFunctionException.class);
-    expectedException.expectMessage("GeoDistance function fifth parameter must be");
-    distanceUdf.evaluate(37.4439, -122.1663, 51.5257, -0.1122, "Widget");
+    expectedException.expectMessage("GeoDistance function radius parameter must be one of");
```
Comment (vcrfxia) [inline ksql-engine/src/test/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudfTest.java]:
```suggestion
    expectedException.expectMessage("GeoDistance function units parameter must be one of");
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java [hunk 22]
```diff
@@ -17,19 +17,24 @@
...
+ *
  * <p>An optional fifth parameter allows to specify either "MI" (miles) or "KM" (kilometers) as the
  * desired unit for the output measurement. Default is KM.
- *
  */
-public class GeoDistanceKudf implements Kudf {
+@UdfDescription(name = "geo_distance", author = "Confluent",
+    description = "Compute the distance between two points on the surface of the earth,"
+        + " according to the Haversine formula for \"great circle distance\".")
+public class GeoDistanceKudf {
```
Comment (vcrfxia) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistanceKudf.java]: nit: It'd be nice to rename this file to `GeoDistance` (and rename the associated unit test file as well), now that it's no longer a `Kudf`.

**Comment by uurl** [comment]
@vcrfxia Ready, thanks
