### PR TITLE
#1439 TIMESTAMP_FORMAT does not respect escaping

### LINKED ISSUE #1439: TIMESTAMP_FORMAT does not respect '' escaping
`CREATE STREAM foo (thing_id BIGINT, event_timestamp VARCHAR) WITH (VALUE_FORMAT='JSON', KAFKA_TOPIC='triggers', TIMESTAMP='event_timestamp', TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX');`

The above appears to work.  But trying to select from the streams results in the following:

`Caused by: Invalid value java.lang.IllegalArgumentException: Unknown pattern letter: T for configuration Invalid date format: yyyy-MM-dd''T''HH:mm:ssX Unknown pattern letter: T`

Version: 5.0.0-beta30

### PR DESCRIPTION
**Pull request by uurl**
### Description 
This PR resolves #1439 TIMESTAMP_FORMAT does not respect '' escaping

### Testing done 
mvn clean package

### Reviewer checklist
- [x] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [x] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by uurl** [comment]
@big-andy-coates @apurvam @rodesai review please

**Comment by uurl** [comment]
@dguy Added 👍

File: ksql-common/src/main/java/io/confluent/ksql/util/StringUtil.java [hunk 1]
```diff
@@ -26,12 +26,13 @@ private StringUtil() {
   public static String cleanQuotes(final String stringWithQuotes) {
     // TODO: move check to grammar
     if (stringWithQuotes.startsWith("'") && stringWithQuotes.endsWith("'")) {
-      return stringWithQuotes.substring(1, stringWithQuotes.length() - 1);
+      return stringWithQuotes.substring(1, stringWithQuotes.length() - 1)
+                .replaceAll("'(.*)'", "$1");
     }
-    return stringWithQuotes;
+    return stringWithQuotes.replaceAll("'(.*)'", "$1");
```
Comment (big-andy-coates) [inline ksql-common/src/main/java/io/confluent/ksql/util/StringUtil.java]: I would not change the string if the passed in string is not actually quoted, i.e. I would just return `stringWithQuotes`. 

I would also suggest changing the replace to just replace all double single-quotes with a single-quote, i.e.  `.replaceAll("''", "')`.

Making this method:

```
public static String cleanQuotes(final String stringWithQuotes) {
    // TODO: move check to grammar
    if (!stringWithQuotes.startsWith("'") || !stringWithQuotes.endsWith("'")) {
      return stringWithQuotes;
    }

    return stringWithQuotes
              .substring(1, stringWithQuotes.length() - 1)
              .replaceAll("''", "'");
}
```

File: ksql-common/src/test/java/io/confluent/ksql/util/StringUtilTest.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+
+import static org.hamcrest.CoreMatchers.is;
+import static org.hamcrest.MatcherAssert.assertThat;
+
+import org.junit.Test;
+
+public class StringUtilTest {
+
+  @Test
+  public void testCleanQuotes() {
```
Comment (big-andy-coates) [inline ksql-common/src/test/java/io/confluent/ksql/util/StringUtilTest.java]: Maybe add some tests that are more about quote handling, rather than just date formats, e.g.

```
@Test
  public void testNotCleanIfMissingQuotePrefix() {
    assertCleaned("COLUMN_NAME'", "COLUMN_NAME'");
  }

  @Test
  public void testNotCleanIfMissingQuotePostfix() {
    assertCleaned("'COLUMN_NAME", "'COLUMN_NAME");
  }

  @Test
  public void testCleanQuotesIfQuoted() {
    assertCleaned("'COLUMN_NAME'", "COLUMN_NAME");
  }

  @Test
  public void testDoesNotReduceAnyQuotesIfNotQuotedString() {
    assertCleaned("prefix ''Something in quotes'' postfix",
        "prefix ''Something in quotes'' postfix");
  }

  @Test
  public void testReducesDoubleSingleQuotesInQuotedStringToSingleSingleQuotes() {
    assertCleaned("'prefix ''Something in quotes'' postfix'",
        "prefix 'Something in quotes' postfix");

    assertCleaned("'a '''' b ''' c '''' d '' e '' f '''",
        "a '' b '' c '' d ' e ' f '");
  }

  @Test
  public void testCleanDateFormat() {
    assertCleaned("'yyyy-MM-dd''T''HH:mm:ssX'", "yyyy-MM-dd'T'HH:mm:ssX");
    assertCleaned("'yyyy.MM.dd G ''at'' HH:mm:ss z'", "yyyy.MM.dd G 'at' HH:mm:ss z");
    assertCleaned("'EEE, MMM d, ''''yy'", "EEE, MMM d, ''yy");
    assertCleaned("'hh ''o''clock'' a, zzzz'", "hh 'o'clock' a, zzzz");
    assertCleaned("'YYYY-''W''ww-u'", "YYYY-'W'ww-u");
  }

  private static void assertCleaned(final String input, final String expected){
    final String result = cleanQuotes(input);
    assertThat(result, is(expected));
  }
```

File: ksql-common/src/main/java/io/confluent/ksql/util/StringUtil.java (hunk 1 above)
Comment (uurl) [reply ksql-common/src/main/java/io/confluent/ksql/util/StringUtil.java]: But,  what happen if it receives something like:
`yyyy-MM-dd''T''HH:mm:ssX`

should  the code return `yyyy-MM-dd'T'HH:mm:ssX`?

I don't know, 😄maybe it's impossible to input this String

**Comment by big-andy-coates** [comment]
Brilliant - thanks @uurl !!!

**Comment by rmoff** [comment]
great stuff, thank you @uurl 🙇

**Comment by pacuna** [comment]
can anyone please push the new version to the [dockerhub image](https://hub.docker.com/r/confluentinc/cp-ksql-cli )? I'm having the timestamp issue with the latest image version.

Thanks in advance.
