### PR TITLE
fix: make to_bytes work with lowercase hex

### LINKED ISSUE #8302: Function TO_BYTES does not accept HEX values in lowercase
**Describe the bug**
The `to_bytes` function returns null when passing a string with lowercase hexadecimal values.

```
sql> select to_bytes('7b0a', 'hex'), to_bytes('7B0A', 'hex') from b emit changes;
+--------------------------------------------------------------------+--------------------------------------------------------------------+
|KSQL_COL_0                                                          |KSQL_COL_1                                                          |
+--------------------------------------------------------------------+--------------------------------------------------------------------+
|null                                                                |ewo=                                                                |
^CQuery terminated
```

**Expected behavior**
`to_bytes` should allow hex values in lower/upper case.

**Additional context**
The problem is in the `BytesUtils` class which uses the following function to code values:
```
private static byte[] hexDecoding(final String value) {
    return BaseEncoding.base16().decode(value);
  }
```

I debugged the code and found the following exception thrown:
```
com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: b
```

`BaseEncoding` only supports A-B and 0-9 values (all uppercase). We should find another library that accepts lower cases. 

An idea is to convert `value` to upper case, but this is adding extra overhead to the hexDecoding() function. Say a user wants to decode a long long string (first parse would be to upper case, second parse would be to decode).

### PR DESCRIPTION
**Pull request by jzaralim**
### Description 
Fixes #8302

Replaces Google's BaseEncoding class with `javax.xml.bind.DatatypeConverter ` for Hex conversions.

### Testing done 
Added unit and QTT tests

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/ToBytesTest.java [hunk 1]
```diff
@@ -40,6 +40,8 @@ public void shouldConvertHexStringToBytes() {
             is(ByteBuffer.wrap(new byte[]{33})));
         assertThat(udf.toBytes("", "hex"),
             is(ByteBuffer.wrap(new byte[]{})));
+        assertThat(udf.toBytes("1a2B", "hex"),
+            is(ByteBuffer.wrap(new byte[]{26, 43})));
```
Comment (spena) [inline ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/ToBytesTest.java:44]: can you add a test with same hex but all uppercase? Just to make sure that both return the same value.

**Review by spena — APPROVED** [review]
I left one minor comment
