### PR TITLE
bug: Improved error message for reserved keywords

### LINKED ISSUE #6083: Bad error message on CREATE with keywords as field names (i.e. SIZE)
Running : CLI v0.11.0, Server v0.11.0
(pulled from confluentinc/ksqldb-server:0.11.0)

Creating a stream with a field named "size" results in the following error : 
extraneous input 'size' expecting {'EMIT'

It seems like size is considered a reserved keyword.
Creating the stream with CREATE STREAM trades ( "size" DOUBLE ) works.

Looks similar to https://github.com/confluentinc/ksql/issues/3746

### PR DESCRIPTION
**Pull request by cprasad1**
### Description 
fixes #6083 
Earlier we used to get error messages like:  `extraneous input 'size' expecting {'EMIT'......` when using keywords as identifiers. Now we get: `"size" is a reserved keyword and it can't be used as an identifier`

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java [hunk 1]
```diff
@@ -130,4 +144,103 @@ private static String getStatementString(final SingleStatementContext singleStat
...
+  private static boolean isKeywordError(final String message, final Object offendingSymbol) {
+    final String tokenName = ((CommonToken) offendingSymbol).getText().toLowerCase();
+
+    final Pattern keywordPattern = Pattern.compile("extraneous input.*expecting.*");
+    final Matcher m = keywordPattern.matcher(message);
+    return reservedKeywords.contains(tokenName) && m.find();
+  }
+
+  //Set of keywords minus the non-reserved ones
+  private static final HashSet<String> reservedKeywords = new HashSet<>(Arrays.asList("advance",
```
Comment (vpapavas) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java:158]: It's better if you create a new class that has a list of the non-reserved keywords and then create there a method that returns all the not-allowed-to-use keywords by using also the `SqlBaseParser.VOCABULARY`. This way, if we ever need to use them in other places, we don't have to hardcode them again. It will make the code reusable and extendable. You can call the class `KsqlParserUtils` and have it public.

**Review by agavra — CHANGES_REQUESTED** [review]
Thanks for taking a stab at this @cprasad1! I think the result is definitely an improvement over what was there previously, but I don't think we should be hardcoding anything (everything should be available programmatically). 

I took a stab at it, since I know that ANTLR can be tough, and got this to work:

```java
  public static void main(String[] args) {
    System.out.println(isReserved("foo"));   // false
    System.out.println(isReserved("show"));  // false
    System.out.println(isReserved("load"));  // true
  }

  private static boolean isReserved(final String token) {

    final SqlBaseLexer sqlBaseLexer = new SqlBaseLexer(
        new CaseInsensitiveStream(CharStreams.fromString(token)));
    final CommonTokenStream tokenStream = new CommonTokenStream(sqlBaseLexer);
    final SqlBaseParser sqlBaseParser = new SqlBaseParser(tokenStream);

    final NonReservedContext nonReservedContext = sqlBaseParser.nonReserved();
    if (nonReservedContext.exception == null) {
      // if the token does not match "nonReserved", then we expect the above
      // method call to throw an exception
      return false;
    }

    // this part was taken directly from FuncitonNameValidator
    final Vocabulary vocabulary = SqlBaseParser.VOCABULARY;
    final int tokens = vocabulary.getMaxTokenType();
    final ImmutableSet.Builder<String> builder = ImmutableSet.builder();

    for (int i = 0; i < tokens; i++) {
      final String symbolicName = vocabulary.getSymbolicName(i);
      if (symbolicName != null) {
        final String keyWord = symbolicName.toLowerCase();
        builder.add(keyWord);
      }
    }

    final ImmutableSet<String> allVocab = builder.build();

    return allVocab.contains(token);
  }
```

I recommend that you take that as a starting point so that we can avoid hardcoding any lists.

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java (hunk 1 above)
Comment (cprasad1) [reply ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java]: added

**Comment by cprasad1** [comment]
Thanks a lot @agavra !!! Amazing code. I have incorporated your changes now.

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+    for (int i = 0; i < tokens; i++) {
+      final String symbolicName = vocabulary.getSymbolicName(i);
+      if (symbolicName != null) {
+        final String keyWord = symbolicName.toLowerCase();
+        builder.add(keyWord);
+      }
+    }
+
+    final ImmutableSet<String> allVocab = builder.build();
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java:55]: we should build this once statically and reuse it - no need to build it every time this method is called. And we should also refactor `FunctionNameValidator` so that this code is reused instead of copy-pasting it

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+
+  public static boolean isReserved(final String token) {
+
+    final SqlBaseLexer sqlBaseLexer = new SqlBaseLexer(
+            new CaseInsensitiveStream(CharStreams.fromString(token)));
+    final CommonTokenStream tokenStream = new CommonTokenStream(sqlBaseLexer);
+    final SqlBaseParser sqlBaseParser = new SqlBaseParser(tokenStream);
+
+    final SqlBaseParser.NonReservedContext nonReservedContext = sqlBaseParser.nonReserved();
+    if (nonReservedContext.exception == null) {
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java:36]: we should make sure to remove the normal error listeners, otherwise whenever we call this (expecting an error) it'll get logged to stdout

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+  }
+
+  public static boolean isReserved(final String token) {
+
+    final SqlBaseLexer sqlBaseLexer = new SqlBaseLexer(
+            new CaseInsensitiveStream(CharStreams.fromString(token)));
+    final CommonTokenStream tokenStream = new CommonTokenStream(sqlBaseLexer);
+    final SqlBaseParser sqlBaseParser = new SqlBaseParser(tokenStream);
+
+    final SqlBaseParser.NonReservedContext nonReservedContext = sqlBaseParser.nonReserved();
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java:35]: I would spend some time with a debugger and see if there's another way we can check if this doesn't match other than if there's an exception. There might be a cleaner way, I just hacked this together really quickly to prove that it was possible. Let me know if you can't find anything

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+import org.antlr.v4.runtime.CharStreams;
+import org.antlr.v4.runtime.CommonTokenStream;
+import org.antlr.v4.runtime.Vocabulary;
+
+public final class KsqlParserUtil {
+
+  private KsqlParserUtil() {
+  }
+
+  public static boolean isReserved(final String token) {
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java:28]: nit: javadoc :)

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+ */
+
+package io.confluent.ksql.parser;
+
+import com.google.common.collect.ImmutableSet;
+import org.antlr.v4.runtime.CharStreams;
+import org.antlr.v4.runtime.CommonTokenStream;
+import org.antlr.v4.runtime.Vocabulary;
+
+public final class KsqlParserUtil {
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java:23]: super nit: I think `ParserUtil` is probably fine (I don't like the pattern of adding `Ksql` in front of everything 😂 )

and in fact, I think there's already a `ParserUtil` class that we can just pop this into

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java [hunk 7]
```diff
@@ -130,4 +142,14 @@ private static String getStatementString(final SingleStatementContext singleStat
         singleStatementContext.stop.getStopIndex()
     ));
   }
+
+  //checks if the error is a reserved keyword error by checking the message and offendingSymbol
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java:146]: nit: should be javadoc, not comment

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java [hunk 8]
```diff
@@ -130,4 +142,14 @@ private static String getStatementString(final SingleStatementContext singleStat
...
+  private static boolean isKeywordError(final String message, final Object offendingSymbol) {
+    final String tokenName = ((CommonToken) offendingSymbol).getText().toLowerCase();
+
+    final Pattern keywordPattern = Pattern.compile("extraneous input.*expecting.*");
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java:150]: nit: this pattern should be compiled once and reused

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java [hunk 9]
```diff
@@ -130,4 +142,14 @@ private static String getStatementString(final SingleStatementContext singleStat
...
+    final Matcher m = keywordPattern.matcher(message);
+    return KsqlParserUtil.isReserved(tokenName) && m.find();
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java:152]: nit: we should flip the order here. `m.find()` is probably significantly cheaper than going through the full blown parser rules
```suggestion
    return m.find() && KsqlParserUtil.isReserved(tokenName);
```

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java [hunk 10]
```diff
@@ -130,4 +142,14 @@ private static String getStatementString(final SingleStatementContext singleStat
         singleStatementContext.stop.getStopIndex()
     ));
   }
+
+  //checks if the error is a reserved keyword error by checking the message and offendingSymbol
+  private static boolean isKeywordError(final String message, final Object offendingSymbol) {
+    final String tokenName = ((CommonToken) offendingSymbol).getText().toLowerCase();
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java:148]: we should have an `instanceOf` check here - are we sure that for all exceptions the `offendingSymbol` is a `CommonToken`? What happens if it's not a `CommonToken`?

Also we should use `Token` instead of `CommonToken` as it's more resilient to underlying implementation changes

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java [hunk 11]
```diff
@@ -47,7 +51,15 @@ public void syntaxError(
         final String message,
         final RecognitionException e
     ) {
-      throw new ParsingException(message, e, line, charPositionInLine);
+      //Checks if the error is a reserved keyword error
+      if (isKeywordError(message, offendingSymbol)) {
+        final String tokenName = ((CommonToken) offendingSymbol).getText();
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java:56]: since we're doing this exact check down inside `isKeywordError` we should just pull it out here and pass in the text directly

**Review by agavra — COMMENTED** [review]
The code LGTM, thanks for making the changes to avoid hardcoding! I have my usual nit-storm (mostly things that are just preference/style, but some things I think are good to implement), but feel free to ask clarifications or challenge any of the comments I put - they're intended as suggestions 😄

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java (hunk 4 above)
Comment (cprasad1) [reply ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParserUtil.java:35]: This seems to be the only way to do it for me. Tried to condense it down (seems to be a lot of work for checking something simple)

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java (hunk 10 above)
Comment (cprasad1) [reply ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java:148]: if it is not a `Token` then we should just return `false` as if the underlying error happens to be a `reservedKeywordError` then it has to be a `Token` so we would just default to the default error handling procedure if that isn't the case

File: ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserKeywordValidatorUtil.java [hunk 12]
```diff
@@ -26,9 +26,10 @@
 /**
```
Comment (vpapavas) [inline ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserKeywordValidatorUtil.java:26]: Could you move the comment to the method used for checking the function name and change the class javadoc to be that the class provides methods for checking whether keywords are java or ksql reserved?

File: ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java [hunk 13]
```diff
@@ -212,4 +220,31 @@ public static JsonObject convertJsonFieldCase(final JsonObject obj) {
...
+
+    final SqlBaseLexer sqlBaseLexer = new SqlBaseLexer(
+            new CaseInsensitiveStream(CharStreams.fromString(token)));
+    final CommonTokenStream tokenStream = new CommonTokenStream(sqlBaseLexer);
+    final SqlBaseParser sqlBaseParser = new SqlBaseParser(tokenStream);
+
+    sqlBaseParser.removeErrorListeners();
+
+    final SqlBaseParser.NonReservedContext nonReservedContext = sqlBaseParser.nonReserved();
+    if (nonReservedContext.exception == null) {
```
Comment (vpapavas) [inline ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java:240]: I am a bit confused about the double negation in the comment :P If the token is a reserved token, then there will be an exception thrown?

**Review by vpapavas — APPROVED** [review]
Great job @cprasad1! Makes the error message much clearer that won't confuse our users anymore, yay! Left a minor comment for the javadoc but other than that LGTM!

File: ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserKeywordValidatorUtil.java (hunk 12 above)
Comment (cprasad1) [reply ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserKeywordValidatorUtil.java:26]: done

File: ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java (hunk 13 above)
Comment (cprasad1) [reply ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java:240]: If we call `nonReservedWord` and if it successfully parses, then we just parsed through a `nonReserved` word as defined in `SqlBase.g4`. if it fails (throws an exception) then it still has the potential to be reserved and we continue checking for that.

Comment (agavra) [reply ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java:240]: yes, your comment here is better written than the way I phrased it originally! I think Vicky is right perhaps we should have the contrapositive of what I wrote:
```
if no exception was "thrown" when calling the nonReserved rule, then this word matches that rule and is not reserved
```

Comment (cprasad1) [reply ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java:240]: ok done

File: ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java [hunk 14]
```diff
@@ -37,11 +39,15 @@
...
 import java.util.Optional;
+import java.util.Set;
 import java.util.regex.Pattern;
+import org.antlr.v4.runtime.CharStreams;
+import org.antlr.v4.runtime.CommonTokenStream;
 import org.antlr.v4.runtime.ParserRuleContext;
 import org.antlr.v4.runtime.Token;
 import org.antlr.v4.runtime.tree.TerminalNode;
 
+@SuppressWarnings("checkstyle:ClassDataAbstractionCoupling")
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java:50]: we usually suppress checkstyle warnings with comments instead of `@SuppressWarnings` for example:
```java
  // CHECKSTYLE_RULES.OFF: ClassDataAbstractionCoupling
  public final class ParserUtil {
    // CHECKSTYLE_RULES.ON: ClassDataAbstractionCoupling
```

File: ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java [hunk 15]
```diff
@@ -47,7 +50,16 @@ public void syntaxError(
         final String message,
         final RecognitionException e
     ) {
-      throw new ParsingException(message, e, line, charPositionInLine);
+      if (offendingSymbol instanceof Token && isKeywordError(
+              message, ((Token) offendingSymbol).getText())) {
+        //Checks if the error is a reserved keyword error
+        final String tokenName = ((Token) offendingSymbol).getText();
+        final String newMessage =
+                "\"" + tokenName + "\" is a reserved keyword and it can't be used as an identifier";
```
Comment (agavra) [inline ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java:58]: maybe also suggest to the user that escaping it will work:
```sql
create stream `size` as select ...
```
that will work

**Review by agavra — APPROVED** [review]
LGTM!
