### PR TITLE
fix(test runner): pass only source topic inputs to topology

### LINKED ISSUE #3018: Testing tool bug with merging streams
I'm trying the testing tool with the following files:

statements.sql:

```sql
CREATE STREAM rock_songs (artist VARCHAR, title VARCHAR)
    WITH (kafka_topic='rock_songs', partitions=1, value_format='avro');

CREATE STREAM classical_songs (artist VARCHAR, title VARCHAR)
    WITH (kafka_topic='classical_songs', partitions=1, value_format='avro');

CREATE STREAM all_songs (artist VARCHAR, title VARCHAR, genre VARCHAR)
    WITH (kafka_topic='all_songs', partitions=1, value_format='avro');

INSERT INTO all_songs SELECT artist, title, 'rock' AS genre FROM rock_songs;

INSERT INTO all_songs SELECT artist, title, 'classical' AS genre FROM classical_songs;
```

input.json:

```json
{
  "inputs": [
    {
      "topic": "rock_songs",
      "key": "Metallica",
      "value": {
        "artist": "Metallica",
        "title": "Fade to Black"
      }
    },
    {
      "topic": "rock_songs",
      "key": "Smashing Pumpkins",
      "value": {
        "artist": "Smashing Pumpkins",
        "title": "Today"
      }
    },
    {
      "topic": "rock_songs",
      "key": "Pink Floyd",
      "value": {
        "artist": "Pink Floyd",
        "title": "Another Brick in the Wall"
      }
    },
    {
      "topic": "rock_songs",
      "key": "Van Halen",
      "value": {
        "artist": "Van Halen",
        "title": "Jump"
      }
    },
    {
      "topic": "rock_songs",
      "key": "Led Zeppelin",
      "value": {
        "artist": "Led Zeppelin",
        "title": "Kashmir"
      }
    },
    {
      "topic": "classical_songs",
      "key": "Wolfgang Amadeus Mozart",
      "value": {
        "artist": "Wolfgang Amadeus Mozart",
        "title": "The Magic Flute"
      }
    },
    {
      "topic": "classical_songs",
      "key": "Johann Pachelbel",
      "value": {
        "artist": "Johann Pachelbel",
        "title": "Canon"
      }
    },
    {
      "topic": "classical_songs",
      "key": "Ludwig van Beethoven",
      "value": {
        "artist": "Ludwig van Beethoven",
        "title": "Symphony No. 5"
      }
    },
    {
      "topic": "classical_songs",
      "key": "Edward Elgar",
      "value": {
        "artist": "Edward Elgar",
        "title": "Pomp and Circumstance"
      }
    }
  ]
}
```

output.json:

```json
{
  "outputs": [
    {
      "topic": "all_songs",
      "key": "Metallica",
      "value": {
        "ARTIST": "Metallica",
        "TITLE": "Fade to Black",
        "GENRE": "rock"
      }
    },
    {
      "topic": "all_songs",
      "key": "Smashing Pumpkins",
      "value": {
        "ARTIST": "Smashing Pumpkins",
        "TITLE": "Today",
        "GENRE": "rock"
      }
    },
    {
      "topic": "all_songs",
      "key": "Pink Floyd",
      "value": {
        "ARTIST": "Pink Floyd",
        "TITLE": "Another Brick in the Wall",
        "GENRE": "rock"
      }
    },
    {
      "topic": "all_songs",
      "key": "Van Halen",
      "value": {
        "ARTIST": "Van Halen",
        "TITLE": "Jump",
        "GENRE": "rock"
      }
    },
    {
      "topic": "all_songs",
      "key": "Led Zeppelin",
      "value": {
        "ARTIST": "Led Zeppelin",
        "TITLE": "Kashmir",
        "GENRE": "rock"
      }
    },
    {
      "topic": "all_songs",
      "key": "Wolfgang Amadeus Mozart",
      "value": {
        "ARTIST": "Wolfgang Amadeus Mozart",
        "TITLE": "The Magic Flute",
        "GENRE": "classical"
      }
    },
    {
      "topic": "all_songs",
      "key": "Johann Pachelbel",
      "value": {
        "ARTIST": "Johann Pachelbel",
        "TITLE": "Canon",
        "GENRE": "classical"
      }
    },
    {
      "topic": "all_songs",
      "key": "Ludwig van Beethoven",
      "value": {
        "ARTIST": "Ludwig van Beethoven",
        "TITLE": "Symphony No. 5",
        "GENRE": "classical"
      }
    },
    {
      "topic": "all_songs",
      "key": "Edward Elgar",
      "value": {
        "ARTIST": "Edward Elgar",
        "TITLE": "Pomp and Circumstance",
        "GENRE": "classical"
      }
    }
  ]
}
```

I'd expect this to run and pass, but instead, I get the following error:

```
ksql-test-runner -i /opt/app/test/input.json -s opt/app/src/statements.sql -o /opt/app/test/output.json
	>>>>> Test failed: Unknown topic: classical_songs
```

It looks like this might be a bug with the testing tool, since I get the reverse error message if I switch the order of the `insert into` statements in the source file:

### PR DESCRIPTION
**Pull request by hjafarpour**
This PR fixes #3018. We now filter the input records and only pipe the ones that belong to the topology source nodes into the topology.
Extra test was added to validate the fix.

### CODE REVIEW

File: ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopologyTestDriverContainer.java [hunk 1]
```diff
@@ -58,4 +60,8 @@ TopologyTestDriver getTopologyTestDriver() {
   public Topic getSinkTopic() {
     return sinkTopic;
   }
+
+  public Set<String> getSourceTopicNames() {
+    return sourceTopics.stream().map(Topic::getName).collect(Collectors.toSet());
```
Comment (agavra) [inline ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopologyTestDriverContainer.java]: nit: do this in the constructor to only create the set once instead of every time we call `getSourceTopicNames`

**Comment by apurvam** [comment]
> the test names (test1, test2 ...) as starting to loose their meaning - can you rename the test directories to describe what they're actually testing? TBH I'm not sure I understand the problem, and someone without context definitely won't. 

Yes, I really don't understand a bug or the fix. This would be good information to put in the PR description rather than just resolving offline.

**Comment by hjafarpour** [comment]
Local build is green but jenkins is failing. I'll merge this.

**Comment by apurvam** [comment]
Looks like the PR build failed with 

‘’’
@jarek @ismael any idea how this failure should be fixed?
>>> [INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[ERROR] Possible null pointer dereference in io.confluent.ksql.test.tools.KsqlTestingToolTest.shouldRunCorrectsTest() due to return value of called method [io.confluent.ksql.test.tools.KsqlTestingToolTest, io.confluent.ksql.test.tools.KsqlTestingToolTest] Dereferenced at KsqlTestingToolTest.java:[line 64]Known null at KsqlTestingToolTest.java:[line 62] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO]
‘’’

Going to revert this
