### PR TITLE
Makes timeout for owner lookup in StaticQueryExecutor and rebalancin…

### LINKED ISSUE #3573: Pull Queries: Make timeouts configurable
The `DEFAULT_TIMEOUT` timeout used in `KsStateStore` when waiting for a store to become available should be configurable and the exception thrown if the store did not become available within the timeout should include details of the new config and its value.

Likewise, the `OWNERSHIP_TIMEOUT` timeout in `StaticQueryExecutor` should be configurable.

### PR DESCRIPTION
**Pull request by AlanConfluent**
…g in KsStateStore configurable

### Description 
Fixes #3573 

Both timeouts in StaticQueryExecutor and KsStateStore have been factored out to a configuration value that can be updated.  

### Testing done 
Ran all unit tests by `mvn clean install checkstyle:check integration-test`

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java [hunk 1]
```diff
@@ -644,10 +645,16 @@ private static SourceName getSourceName(final Analysis analysis) {
...
 
-  private static KsqlNode getOwner(final Struct rowKey, final Materialization mat) {
+  private static KsqlNode getOwner(
+      final KsqlConfig ksqlConfig,
+      final Struct rowKey,
+      final Materialization mat
+  ) {
     final Locator locator = mat.locator();
 
-    final long threshold = System.currentTimeMillis() + OWNERSHIP_TIMEOUT.toMillis();
```
Comment (stevenpyzhang) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java]: `OWNERSHIP_TIMEOUT` isn't used anymore and should be removed

File: ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java [hunk 2]
```diff
@@ -38,29 +39,30 @@
...
   private final Supplier<Long> clock;
 
   KsStateStore(
       final String stateStoreName,
       final KafkaStreams kafkaStreams,
-      final LogicalSchema schema
+      final LogicalSchema schema,
+      final KsqlConfig ksqlConfig
   ) {
-    this(stateStoreName, kafkaStreams, schema, DEFAULT_TIMEOUT, System::currentTimeMillis);
```
Comment (stevenpyzhang) [inline ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java]: `DEFAULT_TIMEOUT` isn't used anymore and should be removed

**Comment by AlanConfluent** [comment]
clabot:check

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java [hunk 3]
```diff
@@ -644,10 +645,16 @@ private static SourceName getSourceName(final Analysis analysis) {
...
+    final long timeoutMs =
+        ksqlConfig.getLong(KsqlConfig.KSQL_STREAMSTORE_REBALANCING_TIMEOUT_MS_CONFIG);
```
Comment (stevenpyzhang) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java]: Shouldn't this be `KSQL_PULL_QUERIES_OWNER_TIMEOUT_MS_CONFIG`?

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java (hunk 1 above)
Comment (AlanConfluent) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java]: Removed.

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java (hunk 3 above)
Comment (AlanConfluent) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java]: Yes, good catch.

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java [hunk 4]
```diff
@@ -201,6 +201,18 @@
       "Config to enable or disable transient pull queries on a specific KSQL server.";
   public static final boolean KSQL_PULL_QUERIES_ENABLE_DEFAULT = true;
 
+  public static final String KSQL_PULL_QUERIES_OWNER_TIMEOUT_MS_CONFIG =
+      "ksql.pull.queries.owner.timeout.ms";
```
Comment (stevenpyzhang) [inline ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: To follow the convention that `KSQL_ACTIVE_PERSISTENT_QUERY_LIMIT_CONFIG` follows
`ksql.query.persistent.active.limit`
```suggestion
      "ksql.query.pull.owner.timeout.ms";
```

File: ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java (hunk 2 above)
Comment (AlanConfluent) [reply ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java]: Removed

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java (hunk 4 above)
Comment (stevenpyzhang) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: Never mind, what you have follows the `KSQL_PULL_QUERIES_ENABLE_CONFIG` naming convention so it should be fine.

Comment (stevenpyzhang) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: @agavra how would you feel about renaming the pull query enable config to 
`ksql.query.pull.enable` to keep all these query configs consistently named

Comment (agavra) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: sounds good to me - just make sure we update our cloud config to reflect the new value

Comment (agavra) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: some context for @AlanConfluent - this config hasn't been released yet so we can change it without worrying about compatibility

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java [hunk 5]
```diff
@@ -196,10 +196,22 @@
           + "whether the Kafka cluster supports the required API, and enables the validator if "
           + "it does.";
 
-  public static final String KSQL_PULL_QUERIES_ENABLE_CONFIG = "ksql.pull.queries.enable";
-  public static final String KSQL_PULL_QUERIES_ENABLE_DOC =
+  public static final String KSQL_QUERY_PULL_ENABLE_CONFIG = "ksql.query.pull.enable";
```
Comment (vinothchandar) [inline ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: +1 seems consistent with other params.

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java [hunk 6]
```diff
@@ -196,10 +196,22 @@
...
+  public static final String KSQL_QUERY_PULL_ENABLE_DOC =
       "Config to enable or disable transient pull queries on a specific KSQL server.";
-  public static final boolean KSQL_PULL_QUERIES_ENABLE_DEFAULT = true;
+  public static final boolean KSQL_QUERY_PULL_ENABLE_DEFAULT = true;
+
+  public static final String KSQL_QUERY_PULL_OWNER_TIMEOUT_MS_CONFIG =
```
Comment (vinothchandar) [inline ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: Naming the method on owner etc internally is okay for now. But, I feel for a public config, we can better standardize the terminology.. 

IMO owner_timeout is not very intuitive.. Can we please name this `ksql.query.pull.routing.timeout.ms`? That's what we are trying to achieve by finding the owner information..

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java [hunk 7]
```diff
@@ -196,10 +196,22 @@
...
+      "ksql.query.pull.owner.timeout.ms";
+  public static final Long KSQL_QUERY_PULL_OWNER_TIMEOUT_MS_DEFAULT = 30000L;
+  public static final String KSQL_QUERY_PULL_OWNER_TIMEOUT_MS_DOC = "Timeout in milliseconds "
+      + "when waiting for the lookup of the owner of a row key";
+
+  public static final String KSQL_STREAMSTORE_REBALANCING_TIMEOUT_MS_CONFIG =
+      "ksql.streamsstore.rebalancing.timeout.ms";
+  public static final Long KSQL_STREAMSTORE_REBALANCING_TIMEOUT_MS_DEFAULT = 10000L;
```
Comment (vinothchandar) [inline ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: Note:  We might not need this param eventually, once KIP-535 on Kafka is implemented and we can query even in rebalancing state. Guess we can back it out later. Good with that.

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java (hunk 4 above)
Comment (AlanConfluent) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: Great, I changed it and made it consistent.

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java (hunk 6 above)
Comment (AlanConfluent) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: Sure, will change the name.

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java (hunk 7 above)
Comment (AlanConfluent) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: Good to know.  I can stick a TODO there, if that's helpful.

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java (hunk 5 above)
Comment (AlanConfluent) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: 👍

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java (hunk 7 above)
Comment (stevenpyzhang) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: I think raising a Github issue (with reference to the KIP) would be better. There was a discussion a while back before you joined about standardizing code standards and we're trying to avoid TODO's 
https://github.com/confluentinc/ksql/pull/3642#discussion_r339044928

Comment (AlanConfluent) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: https://github.com/confluentinc/ksql/issues/3869

File: ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java [hunk 8]
```diff
@@ -196,10 +196,22 @@
...
+      "ksql.query.pull.routing.timeout.ms";
+  public static final Long KSQL_QUERY_PULL_ROUTING_TIMEOUT_MS_DEFAULT = 30000L;
+  public static final String KSQL_QUERY_PULL_ROUTING_TIMEOUT_MS_DOC = "Timeout in milliseconds "
+      + "when waiting for the lookup of the owner of a row key";
+
+  public static final String KSQL_STREAMSTORE_REBALANCING_TIMEOUT_MS_CONFIG =
+      "ksql.streamsstore.rebalancing.timeout.ms";
+  public static final Long KSQL_STREAMSTORE_REBALANCING_TIMEOUT_MS_DEFAULT = 10000L;
+  public static final String KSQL_STREAMSTORE_REBALANCING_TIMEOUT_MS_DOC = "Timeout in "
+      + "milliseconds when waiting for rebalancing of the stream store during a write";
```
Comment (vinothchandar) [inline ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: Please change "during a write"  => "during a pull query". its a read.. Another thing is, do we also want to scope this config to pull queries, since that's where this is used.. `ksql.query.pull.streamsstore.rebalancing.timeout.ms` ? may be its too long. I leave it to your call.

Comment (AlanConfluent) [reply ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java]: Ah, the method call was a little confusing.  I assumed that since it was called "store", it was a write, but it's actually fetching a store.

Changed name to the one you recommend.

**Comment by big-andy-coates** [comment]
> @big-andy-coates what is this line doing if the timeout variable isn't being used in the test?
> 
> ```
>   @Rule
>   public final Timeout timeout = Timeout.seconds(10);
> ```

That will cause the test to fail after 10 seconds if it hasn't completed.
