### PR TITLE
fix: also skip basic authentication for authentication.skip.paths

### LINKED ISSUE #9206: Unable to skip basic authentication for specified paths in ksqldb-server
**Describe the bug**
Use of the config option `authentication.skip.paths` does not actually allow the specified paths to skip basic authentication for ksqldb-server.

**To Reproduce**
Steps to reproduce the behavior, include:
1. Using this [fork](https://github.com/mpistrang/cp-all-in-one/tree/ksqldb-server-basic-auth-example/cp-all-in-one-community) of [confluentinc/cp-all-in-one](https://github.com/confluentinc/cp-all-in-one)
2.  In the `cp-all-in-one-community` directory un `docker-compose -f docker-compose.yml -f docker-compose.ksqldb-server-basic-auth.yml up -d`
3. Note that in the `docker-compose.ksqldb-server-basic-auth.yml` override file basic auth is configured for ksqldb-server along with `/healthcheck` defined in the `authentication.skip.paths` option.

**Expected behavior**
The command `curl localhost:8088/healthcheck` with no basic auth provided returns the health check information

**Actual behavior**
The command `curl localhost:8088/healthcheck` returns an HTTP 401

**Additional context**
I expect there is additional configuration that I am missing here, but so far I have not found what it could be.

### PR DESCRIPTION
**Pull request by lucasbru**
### Description 

There is the KSQL parameter `authentication.skip.paths` that disables authentication for specific paths. Currently, the parameter is ignored for basic authentication, which is probably a bug or at least very confusing to users.

This change moves the handling of `authentication.skip.paths` from specific auth handlers to the `AuthHandlers` class, which allows us to skip _any_ authentication/authorization for paths that match `authentication.skip.paths`.

This change introduces a new Provider called SKIP, that works very similar to the existing SYSTEM Provider - it means that all other authentication / authorization provides. It is enabled for `authentication.skip.paths` and for 3 hard-coded paths. We also slightly simplify the handling of the SYSTEM authorization to bring it in line with SKIP. 

### Testing done 

We port the existing, provider-specic unit tests to `AuthHandlers`. 

I also performed manual testing with the settings
```
authentication.skip.paths=/skippath
authentication.method=BASIC
authentication.realm=KsqlServer-Props
authentication.roles=users
```
and the same JAAS configuration in the ticket #9206
and checking

```
curl localhost:8088/skippath # not found
curl localhost:8088/v1/metadata # works
curl localhost:8088/noskippath # unauthorized
curl -u "my_user:my_password" localhost:8088/skippath # not found
curl -u "my_user:my_password" localhost:8088/v1/metadata # works
curl -u "my_user:my_password" localhost:8088/noskippath # not found
```

Fixes #9206

### Reviewer checklist
- [x] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [x] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PauseResumeIntegrationTest.java [hunk 1]
```diff
@@ -236,7 +236,6 @@ private void createQuery(final String suffix) {
     TEST_HARNESS.getKafkaCluster().waitForTopicsToBePresent(SINK_TOPIC + suffix);
   }
 
-  @NotNull
```
Comment (lucasbru) [inline ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PauseResumeIntegrationTest.java:239]: For some reason, spotbugs kept thinking this can return null. Looks to me like a false alarm, not why I'm getting it.

**Comment by lucasbru** [comment]
@spena and/or @AlanConfluent could you maybe have a look?

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java [hunk 2]
```diff
@@ -58,28 +68,36 @@ static void setupAuthHandlers(final Server server, final Router router,
...
 
       // For authorization use auth provider configured via security extension (if any)
       securityExtension.getAuthorizationProvider()
           .ifPresent(ksqlAuthorizationProvider ->
               registerAuthHandler(
                   router,
-                  new KsqlAuthorizationProviderHandler(server, ksqlAuthorizationProvider)));
+                  selectiveHandler(
+                          new KsqlAuthorizationProviderHandler(server, ksqlAuthorizationProvider),
+                          provider -> provider == Provider.JAAS || provider == Provider.PLUGIN
```
Comment (AlanConfluent) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:99]: Did we just implicitly only fall through to here if it was jaas or plugin and now you're just formally checking that?

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java [hunk 3]
```diff
@@ -103,12 +121,12 @@ private static void registerAuthHandler(
...
 
-  private static Handler<RoutingContext> wrappedHandler(
+  private static Handler<RoutingContext> selectiveHandler(
       final Handler<RoutingContext> handler,
-      final Provider provider
+      final Predicate<Provider> providerTest
   ) {
     return rc -> {
-      if (rc.data().get(PROVIDER_KEY) != provider) {
+      if (!providerTest.test((Provider)rc.data().get(PROVIDER_KEY))) {
```
Comment (AlanConfluent) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:129]: I know you didn't change this part of the logic, but this looks slightly scary that it skips this handler if the particular provider is different from what we expect.  It just seems a little error prone that we decide which auth to use and invoke a handler in two different places.  Maybe this is because we have to statically install all the handers, but only invoke one of them at request-time? Just a general comment -- not sure if you have any ideas.

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java [hunk 4]
```diff
@@ -130,6 +150,11 @@ private static void selectHandler(
       context.next();
       return;
     }
+    if (skipPathsPattern.matcher(context.normalizedPath()).matches()) {
```
Comment (AlanConfluent) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:153]: Nit: Maybe put this first to match the previous order of checks in the plugin.  Shouldn't make any difference, but just to be safe.

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java [hunk 5]
```diff
@@ -58,28 +68,36 @@ static void setupAuthHandlers(final Server server, final Router router,
     systemAuthenticationHandler.ifPresent(handler -> registerAuthHandler(router, handler));
```
Comment (AlanConfluent) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:68]: I don't think it should matter whether they're considered system authenticated before you check the path because it only has the effect of skipping any subsequent checks if they are.

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java [hunk 6]
```diff
@@ -120,8 +138,10 @@ private static Handler<RoutingContext> wrappedHandler(
    * In order of preference, we see if the user is the system user, then we check for
    * JAAS configurations, and finally we check to see if there's a plugin we can use
    */
-  private static void selectHandler(
+  // default visibility for testing
```
Comment (AlanConfluent) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:141]: @VisibleForTesting

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java (hunk 3 above)
Comment (lucasbru) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:130]: Yes, I totally agree. This could be a vertx-ish architectural style, but I'm not sure if it is achieving anything in our setting. It should be possible to have a single wrapping handler to call the sub-handlers -- essentially, merge `selectHandler` and `selectiveHandler` into one, so that you can use plain old control-flow for handler selection instead of passing around `PROVIDER` values. I didn't want to make this too large of a refactoring, but if you want to go down this road with me, I could try.

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java (hunk 6 above)
Comment (lucasbru) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java]: neat! done

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java (hunk 4 above)
Comment (lucasbru) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java]: done

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java (hunk 5 above)
Comment (lucasbru) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:69]: ack

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java (hunk 3 above)
Comment (AlanConfluent) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:130]: No need for anything in this PR, more just thoughts while reading surrounding code.  We can consider that as a followup if you do more changes in this area.

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java (hunk 2 above)
Comment (AlanConfluent) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:100]: That makes sense.  It's better to have it centralized here.

**Review by AlanConfluent — APPROVED** [review]

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java [hunk 7]
```diff
@@ -120,11 +139,18 @@ private static Handler<RoutingContext> wrappedHandler(
    * In order of preference, we see if the user is the system user, then we check for
```
Comment (spena) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java:139]: Can you modify this comment for the order of preference? Btw, wouldn't check for SYSTEM be the step 1, then check for SKIP path?

**Review by spena — APPROVED** [review]
Just one minor comment.
LGTM
