### PR TITLE
fix: append additional fields to row values in `KsqlMaterialization.java` to fix pull query filtering

### LINKED ISSUE #7312: Pull queries return 0 rows when there is a key filter node in the persistent query topology
**Describe the bug**
Pull queries return 0 rows when there is a key filter node in the persistent query topology

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL: `0.17`
2. Any SQL statements you ran:
```
ksql> CREATE TABLE INPUT (ID STRING PRIMARY KEY, GRADE STRING, RANK INT) WITH (kafka_topic='test_topic', value_format='JSON', partitions=1);
ksql> CREATE TABLE NEW_INPUT AS SELECT ID, CONCAT(GRADE, '+'), RANK * 2 AS DOUBLE_RANK FROM INPUT where ID='11';

ksql> insert into INPUT(ID, GRADE, RANK) VALUES ('11', 'A', 1);
ksql> insert into INPUT(ID, GRADE, RANK) VALUES ('10', 'B', 2);
ksql> insert into INPUT(ID, GRADE, RANK) VALUES ('12', 'C', 3);

ksql> SELECT * FROM NEW_INPUT;
```

**Expected behavior**
```
+--------------------------------------------------+--------------------------------------------------+--------------------------------------------------+
|ID                                                |KSQL_COL_0                                        |DOUBLE_RANK                                       |
+--------------------------------------------------+--------------------------------------------------+--------------------------------------------------+
|11                                                |A+                                                |2                                                 |
```
**Actual behaviour**
No rows returned:
```
+--------------------------------------------------+--------------------------------------------------+--------------------------------------------------+
|ID                                                |KSQL_COL_0                                        |DOUBLE_RANK                                       |
+--------------------------------------------------+--------------------------------------------------+--------------------------------------------------+

```

**Additional context**

### PR DESCRIPTION
**Pull request by cprasad1**
### Description 
Fixes #7312 and other similar situations by appending additional fields to row values in `KsqlMaterialization.java`

### Testing done 
- RQTT
- Unit Testing

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java [hunk 1]
```diff
@@ -137,10 +94,69 @@
...
+            A_ROWTIME
+    );
+
+    WINDOWED_ROW2 = WindowedRow.of(
+            SCHEMA,
+            new Windowed<>(A_KEY2, STREAM_WINDOW),
+            A_VALUE2,
+            A_ROWTIME
+    );
+
```
Comment (cprasad1) [inline ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java:155]: These were pulled into the setup layer because `KsqlMaterialization.getIntermediateRow` mutates some of the variables

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java [hunk 2]
```diff
@@ -185,16 +185,38 @@ public MaterializedWindowedTable windowed() {
...
+            return filterAndTransform(row.windowedKey(), getIntermediateRow(row), row.rowTime())
                 .map(v -> row.withValue(v, schema()));
           })
           .filter(Optional::isPresent)
           .map(Optional::get)
           .iterator();
     }
   }
+
+  public static GenericRow getIntermediateRow(final TableRow row) {
```
Comment (cprasad1) [inline ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:199]: This method can be broken down into 2 methods: One for Regular rows, and the other for Windowed rows. Thoughts?

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java [hunk 3]
```diff
@@ -174,7 +174,7 @@ public MaterializedWindowedTable windowed() {
       final Builder<WindowedRow> builder = ImmutableList.builder();
 
       for (final WindowedRow row : result) {
-        filterAndTransform(row.windowedKey(), row.value(), row.rowTime())
+        filterAndTransform(row.windowedKey(), getIntermediateRow(row), row.rowTime())
```
Comment (cprasad1) [inline ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:177]: Unsure if we even need to append the extra columns for windowed rows. Windowed state stores might need more testing

File: ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json [hunk 4]
```diff
@@ -205,6 +205,451 @@
...
+          {"header":{"schema":"`GRADE` STRING KEY, `NUM_STUDENTS` BIGINT"}},
+          {"row":{"columns":["F",4]}}
+
+        ]},
+        {"query": [
+          {"header":{"schema":"`GRADE` STRING KEY"}},
+          {"row":{"columns":["F"]}}
+
+        ]}
+      ]
```
Comment (cprasad1) [inline ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:652]: Currently, there are no additional tests for Windowed materialization. Unsure if we need them right now

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java (hunk 3 above)
Comment (guozhangwang) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:177]: Could you elaborate a bit more here? Is that because the windowed key may have the needed columns for filtering?

**Review by guozhangwang — COMMENTED** [review]
Just wondering what's the difference for windowed stores, for my own education. Otherwise the fix lgtm.

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java (hunk 3 above)
Comment (cprasad1) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:177]: @guozhangwang my understanding is that windowed tables always need an aggregation, so they have a state store backing the aggregated table. If that is the case, then we don't need to append this extra metadata as `KsqlMaterialization` is sophisticated enough to handle those cases (we have test cases for that). I noticed that we follow a similar pattern in `ProjectOperator` and `SelectOperator` of generating intermediate rows on which filters and transformations can be applied. I added these fields as a hedge against potential cases that we might miss (obviously it comes at a cost). That being said, I have a couple of questions for you:
1) Are there any type of Windowed tables that are not queryable today that we want to be able to query?
2) Can Windowed tables be derived without doing any aggregations? (Specifically, `GROUP BY` aggregations)

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java (hunk 2 above)
Comment (AlanConfluent) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:199]: I don't think it's a big deal since it can be figured out by the row itself.  They also share other fields you'd have to otherwise duplicate.

Comment (AlanConfluent) [inline ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:199]: It would be nice to just call https://github.com/confluentinc/ksql/blob/master/ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/PullPhysicalOperatorUtil.java since this is effectively part of the physical layer for pull queries.

File: ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java [hunk 5]
```diff
@@ -53,74 +38,46 @@
...
-      A_ROWTIME
-  );
-
-  private static final WindowedRow WINDOWED_ROW2 = WindowedRow.of(
-      SCHEMA,
-      new Windowed<>(A_KEY2, STREAM_WINDOW),
-      A_VALUE2,
-      A_ROWTIME
-  );
+  private LogicalSchema SCHEMA;
```
Comment (AlanConfluent) [inline ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java:64]: If they're not static, they should have lowercase names.

File: ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java [hunk 6]
```diff
@@ -137,10 +94,69 @@
...
+            new Windowed<>(A_KEY2, STREAM_WINDOW),
+            A_VALUE2,
+            A_ROWTIME
+    );
+
     materialization = new KsqlMaterialization(
         inner,
         SCHEMA,
-        ImmutableList.of(project, filter)
+        ImmutableList.of(filter, project)
```
Comment (AlanConfluent) [inline ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java:159]: Did you swap these because this is a more realistic ordering?

File: ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json (hunk 4 above)
Comment (AlanConfluent) [reply ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:652]: You could always tested a windowed case like 
```
"CREATE TABLE AGGREGATE AS SELECT ID, COUNT(1) AS COUNT FROM INPUT WINDOW TUMBLING(SIZE 1 SECOND) GROUP BY ID HAVING COUNT(1) > 2;",
```
We don't have a lot of tests with the having clause for pull queries and I think it might trigger the `KsqlMaterialization` transform logic to apply the filtering.  Since they can apply for group bys I assume they work for windowed tables as well.  Normal where clauses presumably don't touch `KsqlMaterialization` when a group by is in place since the materialization happens after the filter has been applied, so that might not need additional testing.

But in general, you're right that a lot of windowed logic has already been tested fairly well in https://github.com/confluentinc/ksql/blob/master/ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json since windows require a group by.

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java (hunk 3 above)
Comment (AlanConfluent) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:177]: I haven't tested it by try a windowed query with group by and having clause.  I think that might trigger `KsqlMaterialization`.  In that case, presumably you could say `HAVING WINDOWSTART > 20` and therefore need to have those columns.

Comment (guozhangwang) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:177]: +1 to @AlanConfluent , I think today if you have a `WINDOW BY + GROUP BY + HAVING` you would have a first windowed table from `windowBy+groupBy` aggregations, and then a second windowed table from `having` as a filtering condition. So in that sense not all windowed tables should be generated with aggregations, they can also be generated from table statless operators from other existing windowed tables.

File: ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java (hunk 6 above)
Comment (cprasad1) [reply ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java:159]: yes

File: ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json (hunk 4 above)
Comment (AlanConfluent) [reply ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:652]: These are good cases.  It would be good to do a windowed table + group by + having clause mentioning windowstart.  That's one last case I don't see.

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java (hunk 3 above)
Comment (AlanConfluent) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:177]: It would be good to have this as a RQTT test where the having clause mentions windowstart or windowend

File: ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json (hunk 4 above)
Comment (cprasad1) [reply ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:652]: we don't allow `WINDOWSTART` that at the moment, so it's not a testable case. The specific error message is `Window bounds column WINDOWSTART can only be used in the SELECT clause of windowed aggregations and can not be passed to aggregate functions.`

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java (hunk 2 above)
Comment (AlanConfluent) [inline ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java:199]: If we don't always want to unconditionally add these fields in the future, we should add a comment saying that we need to address this in the future to decide when we need to add these additional fields.

**Review by AlanConfluent — APPROVED** [review]
Nice PR and good test cases

File: ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json (hunk 4 above)
Comment (cprasad1) [reply ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:652]: Related: https://github.com/confluentinc/ksql/issues/4397

**Review by guozhangwang — APPROVED** [review]
Thanks for the added testing coverage!

File: ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json [hunk 7]
```diff
@@ -205,6 +205,613 @@
...
+        {"query": [
+          {"header":{"schema":"`ID` STRING KEY, `GRADE` STRING, `DOUBLE_RANK` INTEGER"}}
+        ]},
+        {"query": [
+          {"header":{"schema":"`ID` STRING KEY, `DOUBLE_RANK` INTEGER"}}
+        ]}
+      ]
+    },
+    {
+      "name": "persistent query with KEY filter and projection +++ pull query table scan and single key lookup ***FAILURE***",
```
Comment (guozhangwang) [inline ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:254]: nit: should we explicitly state the the error root cause here? Since otherwise the name is exactly the same as above except we say it is a `***FAILURE***` case.

File: ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json (hunk 4 above)
Comment (guozhangwang) [reply ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:652]: I'm still wondering, if @AlanConfluent 's query is possible:

```
CREATE TABLE AGGREGATE AS SELECT ID, COUNT(1) AS COUNT FROM INPUT WINDOW TUMBLING(SIZE 1 SECOND) GROUP BY ID HAVING COUNT(1) > 2;
```

note it does not try to group by window-start/end, while we should still be able to pull query it with conditions on other columns?

File: ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json [hunk 8]
```diff
@@ -205,6 +205,613 @@
...
+          {"row":{"columns":["F"]}}
+
+        ]}
+      ]
+    },
+    {
+      "name": "windowed - select star with HAVING filter",
+      "statements": [
+        "CREATE STREAM INPUT (ID STRING KEY, IGNORED INT) WITH (kafka_topic='test_topic', value_format='JSON');",
+        "CREATE TABLE AGGREGATE AS SELECT ID, COUNT(1) AS COUNT FROM INPUT WINDOW TUMBLING(SIZE 1 SECOND) GROUP BY ID HAVING COUNT(1) > 1;",
```
Comment (cprasad1) [inline ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:658]: @guozhangwang is this the test similar to what you are interested in?

Comment (guozhangwang) [reply ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json:658]: Ah yes, thanks!
