### PR TITLE
fix: don't cleanup topics on engine close

### LINKED ISSUE #4654: KSQL sometimes deletes internal topics when the server shuts down
When KSQL shuts down, it closes all the queries in the engine. One of the steps of closing a query is to delete the internal topics.

**To Reproduce**
Start KSQL and run a query, then shut KSQL down (presumably by sending a term signal).

**Expected behavior**
KSQL exits cleanly but leaves all internal topics in tact

**Actual behaviour**
KSQL deletes the internal topics (and therefore their data)

### PR DESCRIPTION
**Pull request by agavra**
Co-authored-by: Rohan <desai.p.rohan@gmail.com>

fixes #4654

### Description 
See the description in the ticket above. This makes it so that we don't cleanup topics for persistent queries on closing the engine (but we do for transient).

### Testing done 
- Unit tests
- Manual testing to ensure we can't reproduce the bug.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java [hunk 1]
```diff
@@ -136,6 +137,15 @@ public void shouldCloseKStreamsAppOnCloseThenCloseCallback() {
     inOrder.verify(closeCallback).accept(query);
   }
 
+  @Test
+  public void shouldNotCallCloseCallbackOnStop() {
+    // When:
+    query.stop();
+
+    // Then:
+    verifyNoMoreInteractions(closeCallback);
```
Comment (big-andy-coates) [inline ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java]: How about?

```suggestion
    verify(kafkaStreams).close(Duration.ofMillis(closeTimeout));
    verify(closeCallback, never()).accept(any());
```

File: ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java [hunk 2]
```diff
@@ -169,14 +169,41 @@ public boolean hasEverBeenStarted() {
...
+   *
+   * <p>NOTE: {@link TransientQueryMetadata} overrides this method
+   * since any time a transient query is stopped the external resources
+   * should be cleaned up.</p>
+   *
+   * @see #close()
+   */
+  public void stop() {
+    close(false);
+  }
```
Comment (big-andy-coates) [inline ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java]: I'd be tempted to make this abstract and move this impl to `PersistentQuery`.

No biggie, just feels cleaner to me.

Comment (agavra) [reply ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java]: I wanted to do that, but there's a place where `QueryMetadata` is actually being instantiated directly. Not sure if that's a bug, but I didn't want to deal with it now.

File: ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java (hunk 1 above)
Comment (agavra) [reply ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java]: Added an additional test

File: ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java [hunk 3]
```diff
@@ -676,6 +677,64 @@ public void shouldCleanUpInternalTopicsOnClose() {
...
+        KSQL_CONFIG, Collections.emptyMap()
+    );
+
+    query.get(0).start();
+
+    // When:
+    ksqlEngine.close();
+
+    // Then (there are no transient queries, so no internal topics should be deleted):
+    verify(topicClient, times(0)).deleteInternalTopics(any());
```
Comment (big-andy-coates) [inline ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java]: nit:

```suggestion
    verify(topicClient, never()).deleteInternalTopics(any());
```

File: ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java [hunk 4]
```diff
@@ -676,6 +677,64 @@ public void shouldCleanUpInternalTopicsOnClose() {
...
+    );
+
+    query.start();
+
+    // When:
+    ksqlEngine.close();
+
+    // Then:
+    verify(topicClient).deleteInternalTopics(query.getQueryApplicationId());
+    verifyNoMoreInteractions(topicClient);
```
Comment (big-andy-coates) [inline ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java]: nit: not necessary.

File: ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java [hunk 5]
```diff
@@ -147,6 +167,15 @@ public void shouldCleanUpKStreamsAppAfterCloseOnClose() {
     inOrder.verify(kafkaStreams).cleanUp();
   }
 
+  @Test
+  public void shouldNotCleanUpKStreamsAppOnStop() {
+    // When:
+    query.stop();
+
+    // Then:
+    verify(kafkaStreams, times(0)).cleanUp();
```
Comment (big-andy-coates) [inline ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java]: nit:

```suggestion
    verify(kafkaStreams, never()).cleanUp();
```

File: ksql-engine/src/test/java/io/confluent/ksql/util/TransientQueryMetadataTest.java [hunk 6]
```diff
@@ -87,4 +88,22 @@ public void shouldCloseQueueBeforeTopologyToAvoidDeadLock() {
...
+  }
+
+  @Test
+  public void shouldCallCallbackOnStop() {
+    // When:
+    query.stop();
+
+    // Then:
+    verify(closeCallback).accept(query);
+  }
```
Comment (big-andy-coates) [inline ksql-engine/src/test/java/io/confluent/ksql/util/TransientQueryMetadataTest.java]: If the order is important, then I'd test the order too...

File: ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java (hunk 2 above)
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java]: Really? Sounds like a bug!

Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java]: Looks like this is used from the new code: for transient queries. So this should default to cleaning up internal topics.

Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java]: so we should switch this to `close(true)` as we want transient queries to delete internal state.

This will also mean we need to remove the overloaded version from `TransientQueryMetadata` and add the following overload to `PersistentQueryMetadata`

```java
@Override
public void stop() {
    close(false);
  }
```
