### PR TITLE
Fix concurrent mod exception on shutting down

### LINKED ISSUE #2339: ConcurrentModificationException when shutting down KSQL
```
[2019-01-11 17:44:23,981] ERROR Exception while waiting for CommandRunner thread to complete (io.confluent.ksql.rest.server.KsqlRestApplication:191)
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2214)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2103)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2058)
	at io.confluent.ksql.rest.server.CommandTopic.close(CommandTopic.java:137)
	at io.confluent.ksql.rest.server.computation.CommandStore.close(CommandStore.java:79)
	at io.confluent.ksql.rest.server.computation.CommandRunner.close(CommandRunner.java:110)
	at io.confluent.ksql.rest.server.KsqlRestApplication.stop(KsqlRestApplication.java:188)
	at io.confluent.ksql.test.util.TestKsqlRestApp.after(TestKsqlRestApp.java:163)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 
This PR fixes a potential concurrent modification exception when shutting down the RESTful server. The exception is thrown when shutting down the command runner because the command runner thread is still active and can be using the consumer.  Attempting to `wakeup`/`close` the consumer results in a concurrent mod exception if it is being used from the command runner thread.

Fixes #2339

Reviewing notes:

- the command runner thread is now managed by the command runner, so that it can ensure things shutdown in the right order to avoid concurrent mod exceptions.
- to allow things to shutdown I've changed the `CommandQueue.getNewCommands` to take a timeout. This allows control to pass back to the command runner's internal thread, allowing it to check if it should shutdown.
- added a couple of 'early outs' at various points in the processing & retry logic to ensure timely exiting of the thread.

### Testing done 
Added more unit testing around shutdown.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java [hunk 1]
```diff
@@ -126,13 +138,45 @@ public void processPriorCommands() {
     ksqlEngine.getPersistentQueries().forEach(PersistentQueryMetadata::start);
   }
 
+  void fetchAndRunCommands() {
+    final List<QueuedCommand> commands = commandStore.getNewCommands(NEW_CMDS_TIMEOUT);
+    if (commands.isEmpty()) {
```
Comment (rodesai) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java]: nit: unnecessary check

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java [hunk 2]
```diff
@@ -56,51 +64,55 @@ public CommandRunner(
...
-
-  void fetchAndRunCommands() {
-    final List<QueuedCommand> commands = commandStore.getNewCommands();
-    final Optional<QueuedCommand> terminateCmd = findTerminateCommand(commands);
-    if (terminateCmd.isPresent()) {
-      terminateCluster(terminateCmd.get().getCommand());
-      return;
+    try {
+      closed = true;
+      executor.awaitTermination(SHUTDOWN_TIMEOUT_MS, TimeUnit.MILLISECONDS);
```
Comment (rodesai) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java]: It would be nice to do a wakeup of the consumer here before calling awaitTermination. Also, CommandStore.close has an unnecessary wakeup we can clean up.

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java (hunk 1 above)
Comment (big-andy-coates) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java]: Well, it avoids an unnecessary trace message which, given the `getNewCommands` message has a timeout and doesn't just block indefinitely, has some benefit.  Though I admit, not much.

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java (hunk 2 above)
Comment (big-andy-coates) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java]: Tis true. Done.
