### PR TITLE
fix: update Concat UDF to new framework and make variadic

### LINKED ISSUE #5078: CONCAT should be a variadic function
Concatenating more than 2 columns, especially with some separator is difficult. The CONCAT function should be variadic, to easily concatenate multiple values.

`SELECT CONCAT(COL1, COL2, '-', COL3) AS SOME_NAME FROM TABLE...`

### PR DESCRIPTION
**Pull request by blueedgenick**
### Description 
As per title. Tests and docs updated too.

Fixes #5078 

### Testing done 
Unit tests, QTT, and manual testing all ok.

### CODE REVIEW

File: ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Concat.java [hunk 1]
```diff
@@ -16,23 +16,31 @@
...
-      throw new KsqlFunctionException(NAME + " should have at least two input argument.");
+  @Udf
+  public String concat(@UdfParameter(
+      description = "The varchar fields to concatenate") final String... inputs) {
+    if (inputs == null) {
+      return null;
+    }
+    if (inputs.length < 2) {
+      throw new KsqlFunctionException("Concat should have at least two input arguments.");
     }
```
Comment (agavra) [inline ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Concat.java:39]: I know this isn't your original code, but does this limitation makes sense? I feel like `CONCAT('foo')` could reasonably return just `'foo'`. I can imagine passing in an array of values and expect it to work (now that we support variadic) even for the cases where there's fewer than 2 (or even if the array is empty, so `CONCAT([])` would return `""`)

Comment (blueedgenick) [reply ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Concat.java:39]: You make a fair point - and the same thought went through my head while going through the code but i decided not to disturb the status quo too much (for once!).Happy to change it though, i think what you are suggesting makes more intuitive sense, as it would bring the behavior into line with what happens if you pass more than 2 inputs but less than 2 of them are non-null - e.g. `concat(null, 'foo', null)` is already processed without complaint and returns `foo`.  WDYT ?

Comment (agavra) [reply ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Concat.java:39]: +1 that makes a lot of sense (and in line with what we would do today even before this PR if we had `CONCAT(null, 'foo')`)

Comment (blueedgenick) [reply ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Concat.java]: Done!
