### PR TITLE
Handle 'RUN SCRIPT' directly in CLI, rather than post it to KSQL.

### LINKED ISSUE #1031: Avro limitation for commands in RUN SCRIPT vs. interactive KSQL usage
When you create a new stream by reading from a Kafka topic with Avro-formatted messages, you don't have to define columns or data types in the CREATE statement....if you are interacting via the CLI.

However, if you are putting these commands in a script that you then pass in via queries-file, then I think you do.

These commands passed in via `RUN SCRIPT` work:

```
CREATE STREAM ksqlplayevents (SONG_ID BIGINT, DURATION BIGINT) WITH (KAFKA_TOPIC='play-events', VALUE_FORMAT='AVRO');
CREATE STREAM ksqlplayevents_min_duration AS SELECT * FROM ksqlplayevents WHERE DURATION > 30000;
```

These commands passed in via `RUN SCRIPT` do not work:

```
CREATE STREAM ksqlplayevents WITH (KAFKA_TOPIC='play-events', VALUE_FORMAT='AVRO');
CREATE STREAM ksqlplayevents_min_duration AS SELECT * FROM ksqlplayevents WHERE DURATION > 30000;
```

Error:

```
io.confluent.ksql.parser.exception.ParseFailedException: Parsing failed on KsqlEngine msg:Field DURATION is ambiguous.
	at io.confluent.ksql.KsqlEngine.parseQueries(KsqlEngine.java:278)
	at io.confluent.ksql.KsqlEngine.buildMultipleQueries(KsqlEngine.java:182)
	at io.confluent.ksql.rest.server.computation.StatementExecutor.handleRunScript(StatementExecutor.java:273)
	at io.confluent.ksql.rest.server.computation.StatementExecutor.executeStatement(StatementExecutor.java:252)
	at io.confluent.ksql.rest.server.computation.StatementExecutor.handleStatementWithTerminatedQueries(StatementExecutor.java:203)
	at io.confluent.ksql.rest.server.computation.StatementExecutor.handleStatement(StatementExecutor.java:108)
	at io.confluent.ksql.rest.server.computation.CommandRunner.executeStatement(CommandRunner.java:105)
	at io.confluent.ksql.rest.server.computation.CommandRunner.fetchAndRunCommands(CommandRunner.java:88)
	at io.confluent.ksql.rest.server.computation.CommandRunner.run(CommandRunner.java:63)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.confluent.ksql.parser.AstBuilder$InvalidColumnReferenceException: Field DURATION is ambiguous.
	at io.confluent.ksql.parser.AstBuilder.visitColumnReference(AstBuilder.java:1147)
	at io.confluent.ksql.parser.AstBuilder.visitColumnReference(AstBuilder.java:142)
	at io.confluent.ksql.parser.SqlBaseParser$ColumnReferenceContext.accept(SqlBaseParser.java:5500)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:531)
	at io.confluent.ksql.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:5054)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.parser.AstBuilder.visitPredicated(AstBuilder.java:866)
	at io.confluent.ksql.parser.AstBuilder.visitPredicated(AstBuilder.java:142)
	at io.confluent.ksql.parser.SqlBaseParser$PredicatedContext.accept(SqlBaseParser.java:4616)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitBooleanDefault(SqlBaseBaseVisitor.java:461)
	at io.confluent.ksql.parser.SqlBaseParser$BooleanDefaultContext.accept(SqlBaseParser.java:4355)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitExpression(SqlBaseBaseVisitor.java:447)
	at io.confluent.ksql.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:4283)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.parser.AstBuilder.visitSelectSingle(AstBuilder.java:559)
	at io.confluent.ksql.parser.AstBuilder.visitSelectSingle(AstBuilder.java:142)
	at io.confluent.ksql.parser.SqlBaseParser$SelectSingleContext.accept(SqlBaseParser.java:3406)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.confluent.ksql.parser.AstBuilder.visit(AstBuilder.java:1358)
	at io.confluent.ksql.parser.AstBuilder.visitQuerySpecification(AstBuilder.java:362)
	at io.confluent.ksql.parser.AstBuilder.visitQuerySpecification(AstBuilder.java:142)
	at io.confluent.ksql.parser.SqlBaseParser$QuerySpecificationContext.accept(SqlBaseParser.java:2416)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitQueryPrimaryDefault(SqlBaseBaseVisitor.java:251)
	at io.confluent.ksql.parser.SqlBaseParser$QueryPrimaryDefaultContext.accept(SqlBaseParser.java:2234)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitQueryTermDefault(SqlBaseBaseVisitor.java:244)
	at io.confluent.ksql.parser.SqlBaseParser$QueryTermDefaultContext.accept(SqlBaseParser.java:2162)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.parser.AstBuilder.visitQueryNoWith(AstBuilder.java:312)
	at io.confluent.ksql.parser.AstBuilder.visitQueryNoWith(AstBuilder.java:142)
	at io.confluent.ksql.parser.SqlBaseParser$QueryNoWithContext.accept(SqlBaseParser.java:2088)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.parser.AstBuilder.visitQuery(AstBuilder.java:289)
	at io.confluent.ksql.parser.AstBuilder.visitCreateStreamAs(AstBuilder.java:240)
	at io.confluent.ksql.parser.AstBuilder.visitCreateStreamAs(AstBuilder.java:142)
	at io.confluent.ksql.parser.SqlBaseParser$CreateStreamAsContext.accept(SqlBaseParser.java:710)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:166)
	at io.confluent.ksql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:142)
	at io.confluent.ksql.parser.SqlBaseParser$SingleStatementContext.accept(SqlBaseParser.java:293)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.parser.KsqlParser.prepareStatement(KsqlParser.java:82)
	at io.confluent.ksql.KsqlEngine.parseQueries(KsqlEngine.java:257)
```

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 
This is the CLI side of the work for #2179.

Fixed #1031 by deprecating the run script functionality.

The CLI can now handle `RUN SCRIPT` commands by loading the contents of the script and posting it to KSQL as a request containing multiple lines of SQL, rather than as a special 'run script' command.

i.e. this change means the CLI is no longer reliant on the server's 'run script' functionality. Meaning it can be removed in a later PR.  The CLI now handles run script by loading the script content and posting it to the server as a single multi-statement request.  This means the rest-server will parse and 'tryExecute' the set of statements, (rather than use the server side run-script functionality which dumbly posts the script contents to the command topic without any validation). If the tryexecute succeeds, then each statement will sequentially be posted to the command topic.

While I was working on a new CLI command I took the opportunity to refactor the interface to decouple it more from the `Console`.
- Instances now take `Supplier`, `Consumer` and `Runnable` interfaces in their constructors. These are wired back to the necessary methods on the `Console` in the true CLI app.
- The console can handle commands with more than one word in their name, e.g. 'run script'.
- The console can handle commands that take multiple args.
- Dealing with parsing arguments and removing quotes etc is done in one place: in Console.
- Cli commands will now ignore any trailing semi-colon, e.g. entering 'version;' will no longer result in an error.

The PR looks to maintain backwards compatibility with existing run script functionality. So you can still type:

```
ksql>run script '/path/to/my/script';
```

Though the trailing semi-colon is optional.

With this change, `RUN SCRIPT` commands entered in the CLI are no longer written to the command topic as a `RUN SCRIPT` command. Instead, the server will parse the contents of the script, validate, and then write each executable statement to the command topic separately. 

There will be follow on PRs to improve the server side handling of multi-statement requests.

### Testing done 
Manual testing of all existing commands and the new command.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by big-andy-coates** [comment]
Ah.... interesting.  Not sure how to handle SET/UNSET.  Any suggestions welcome.  Otherwise, I'll have a think.

File: ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java [hunk 1]
```diff
@@ -259,7 +273,7 @@ private void registerTopic(
   private void runScript(
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java]: Yep, good call.

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/RunScript.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+import java.io.IOException;
+import java.io.PrintWriter;
+import java.nio.charset.StandardCharsets;
+import java.util.List;
+import java.util.Objects;
+import java.util.stream.Collectors;
+
+class RunScript implements CliSpecificCommand {
+
+  private static final String HELP = "run <path_to_sql_file>:" + System.lineSeparator()
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/RunScript.java]: good catch!

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/Help.java [hunk 3]
```diff
@@ -31,58 +37,59 @@ public String getName() {
...
+    terminal.println();
+    terminal.println(
         "    Lines are read one at a time and are sent to the "
             + "server as KSQL unless one of the following is true:"
     );
-    console.writer().println();
-    console.writer().println(
+    terminal.println();
+    terminal.println(
         "    1. The line is empty or entirely whitespace. In this"
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/Help.java]: Yeah, it should indeed. I've updated.

File: ksql-cli/src/test/java/io/confluent/ksql/cli/console/cmd/RunScriptTest.java [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+
+  @Test
+  public void shouldGetName() {
+    assertThat(cmd.getName(), is("run script"));
+  }
+
+  @Test
+  public void shouldGetHelp() {
+    assertThat(cmd.getHelpMessage(), is(
+        "run <path_to_sql_file>:" + System.lineSeparator()
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-cli/src/test/java/io/confluent/ksql/cli/console/cmd/RunScriptTest.java]: done.

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java [hunk 5]
```diff
@@ -14,12 +14,15 @@
 
 package io.confluent.ksql.cli.console;
 
+import static io.confluent.ksql.util.CmdLineUtil.splitByUnquotedWhitespace;
+import static io.confluent.ksql.util.CmdLineUtil.trimTrailingSemiColon;
```
Comment (agavra) [inline ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java]: are there any style guidelines around static imports? IMO, it makes it a little harder to review code (I see it inline and I scroll around a little bit looking for the new method, get confused, then realize it's a static import)

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java [hunk 6]
```diff
@@ -0,0 +1,199 @@
...
+  public static List<String> splitByUnquotedWhitespace(final String string) {
+    return new WhitespaceParser().parse(string);
+  }
+
+  /**
+   * Remove any matched, i.e. closed, single quotes from the supplied {@code string}.
+   *
+   * <p>Works in a similar way to a unix command line would.
+   *
+   * <p>A quote can be escaped using a second single quote, e.g. {@code "'escaped '' quote'"}.
```
Comment (agavra) [inline ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: to me, this escaping behavior is a little unclear. It took me a while to understand why it doesn't pair `'escaped '` and `' quote'`. Unless this is already part of the public API, thoughts on using `\` to escape instead of another `'`? (Same applies above)

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java [hunk 7]
```diff
@@ -0,0 +1,199 @@
...
+    return new QuoteRemover().parse(string);
+  }
+
+  /**
+   * Removes any trailing semi colon(s).
+   *
+   * @param s the string to trim.
+   * @return the trimmed string
+   */
+  public static String trimTrailingSemiColon(final String s) {
```
Comment (agavra) [inline ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: this is equivalent to `StringUtils#stripEnd(s, ";")` if I understand correctly

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliSpecificCommand.java [hunk 8]
```diff
@@ -14,10 +14,34 @@
 
 package io.confluent.ksql.cli.console.cmd;
 
+import java.io.PrintWriter;
+import java.util.List;
+
 public interface CliSpecificCommand {
+
+  /**
```
Comment (agavra) [inline ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliSpecificCommand.java]: Thanks for adding javadocs 👍 helps me ramp up faster!

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/History.java [hunk 9]
```diff
@@ -31,18 +36,13 @@ public String getName() {
...
+    return HELP;
   }
 
   @Override
-  public void execute(final String commandStrippedLine) {
-    console.printHistory();
-    console.flush();
+  public void execute(final List<String> args, final PrintWriter terminal) {
+    CliCmdUtil.ensureArgCountBounds(args, 0, 0, () -> HELP);
+    historyPrinter.run();
```
Comment (agavra) [inline ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/History.java]: something here seems off to me, we're passing in `terminal`, but we're not printing to that one when we run the history. is there any way to resolve this, or is this intentional?

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliCmdUtil.java [hunk 10]
```diff
@@ -0,0 +1,44 @@
...
+final class CliCmdUtil {
+
+  private CliCmdUtil() {
+  }
+
+  static void ensureArgCountBounds(
+      final Collection<String> args,
+      final int minArgCount,
+      final int maxArgCount,
+      final Supplier<String> helpSupplier
```
Comment (agavra) [inline ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliCmdUtil.java]: a quick scan through this PR shows that we always just pass in `() -> literal`. Why make this a Supplier?

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java [hunk 11]
```diff
@@ -0,0 +1,199 @@
...
+          ++returnPos;
+        } else {
+          inQuotes = false;
+        }
+      }
+      return returnPos;
+    }
+  }
+
+  private static final class QuoteRemover {
```
Comment (agavra) [inline ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: I think that this and `WhitespaceParser` are both sufficiently complex to justify dedicated classes (and corresponding unit tests). I still need to go through and review them, but I'll do that with a fresh pair of eyes tomorrow morning :D

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java (hunk 5 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java]: We don't AFAIK.  I generally review PRs in my IDE if they're of a decent size.   Makes it much easier to navigate around.

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliSpecificCommand.java (hunk 8 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliSpecificCommand.java]: No problem. :D

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliCmdUtil.java (hunk 10 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliCmdUtil.java]: Probably an artefact of the refactoring I did. I was originally a method. I'll take a look...

Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/CliCmdUtil.java]: Sorted.

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/History.java (hunk 9 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/History.java]: Small steps.  There are definitely other improvements that can be made to these classes, but one thing at a time ;)

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java (hunk 6 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: The use of a `'` to escape a `'` is an ugly thing IMHO, but its standard SQL...

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java (hunk 7 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: nice. Wasn't aware of this method. Updated.

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java (hunk 11 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: IMHO they are implementation details of the methods that use them, and they are tested extensively through those methods. 

I'm not saying they've not got bugs ;) . Just that we gain nothing by promoting these to top level classes and testing them independently of the only place they are intended to be used.

**Comment by big-andy-coates** [comment]
Thanks for the review @hjafarpour and welcome @agavra!

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/History.java (hunk 9 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/History.java]: But.. now that you're raised it... I'll fix this too! ;)

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java (hunk 11 above)
Comment (agavra) [reply ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: `(''[^'\s]*)|'(?<esc>([^']|'')*)'|(\S+)` This (kinda crazy) Regex seems to do the job pretty well, though at this point I'm not sure if I prefer this "magic" over the original:

```
    String text = "''t0 t1 'quoted string' 'quoted '' string'";

    final String NOT_DOUBLE = "''[^'\\s]*";
    final String ESCAPED = "([^']|'')*";
    final String NOT_WHITESPACE = "\\S+";

    String regex = String.format("(%s)|'(?<esc>%s)'|(%s)", NOT_DOUBLE, ESCAPED, NOT_WHITESPACE);

    Matcher m = Pattern.compile(regex).matcher(text);
    while (m.find()) {
      System.out.println(ObjectUtils.defaultIfNull(m.group("esc"), m.group()).replace("''","'"));
    }
```

This outputs
```
't0
t1
quoted string
quoted ' string
```

Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: Interesting!

Does the above regex work for all the test cases? I didn't think it was possible to match quotes with regex in the presence of escaped quotes.

File: ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/RunScript.java [hunk 12]
```diff
@@ -0,0 +1,67 @@
...
+    CliCmdUtil.ensureArgCountBounds(args, 1, 1, () -> HELP);
+
+    final String filePath = args.get(0);
+    final String content = loadScript(filePath);
+    requestExecutor.makeKsqlRequest(content);
+  }
+
+  private static String loadScript(final String filePath) {
+    try {
+      return Files.readLines(new File(filePath), StandardCharsets.UTF_8).stream()
```
[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/RunScript.java]: Because its deprecated :)

Mind you, I wasn't intending to use Guava here at all, so you highlighting this has at least sorted that. It now uses Java NIO `Files`.

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java (hunk 11 above)
Comment (agavra) [reply ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: I have not checked - after you push the current code maybe I'll play around with it a little bit, time permitting.

File: ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java [hunk 13]
```diff
@@ -0,0 +1,199 @@
...
+   * Split the supplied line by unquoted whitespace.
+   *
+   * <p>White space within an open single quote will be ignored
+   *
+   * <p>A quote can be escaped using a second single quote, e.g. {@code "'escaped '' quote'"}.
+   *
+   * <ul>
+   * <li>{@code "t0 t1"} becomes {@code ["t0", "t1"]}</li>
+   * <li>{@code "'quoted string'"} becomes {@code ["quoted string"]}</li>
+   * <li>{@code "'quoted'connected'quoted'"} becomes {@code ["quotedconnectedquoted"]}</li>
```
[the remark this answers is not in the document]
Comment (rodesai) [reply ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: I meant you should fix the example in the comment. The result for `'quoted'connected'quoted'` is `'quoted'connected'quoted'`, right? This function isn't stripping quotes.

[the remark this answers is not in the document]
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java]: Ah, yeah, you're right. I've updated and also added tests covering the javadocs of both the split and strip functions.

**Comment by big-andy-coates** [comment]
Thanks all for the reviews!
