### PR TITLE
Ksql 1217 optionally delete kafka topic with drop statement

### LINKED ISSUE #1217: Optionally delete the underlying kafka topic when dropping a stream/table.
When we drop a stream or table, currently we don't delete the underlying kafka topic. While this may be desirable in most of the cases, in many cases we would like to also delete the corresponding topic when dropping a stream or table. For instance, consider the following statement:

`CREATE STREAM foo AS SELECT col1, col2 FROM bar;`

now if we have a mistake in this query and want to change it to the following:

`CREATE STREAM foo AS SELECT col1+10, col2 FROM bar;`

We should drop terminate the first query, drop the sink stream and run the corrected query. User should delete the topic with incorrect data if she does not want to have them in the result and this can be done from kafka now. We can extend the `DROP` statement to include hint about if user wants to delete the underlying topic too. So we can have the following:

`DROP STRAEM foo WITH TOPIC:`

This will indicate that the user wants the underlying topic to be deleted too. If the topic format is avro we should also delete the corresponding avro schema from schema registry.
`DROP` statement will behave the same as current behavior if `WITH TOPIC` is not present and won't delete t he topic.

### PR DESCRIPTION
**Pull request by hjafarpour**
### Description 
This PR adds the ability to delete the underlying kafka topic when dropping a stream or table. If the format is Avro, along with deleting kafka topic we also delete the corresponding avro schema from the schema registry.
`DROP STREAM` and `DROP TABLE` statements will have an optional prefix `DELETE TOPIC` which indicate the user intention to delete the topic. If `DELETE TOPIC` is not present in the `DROP` statement it will behave as now and won't delete the topic(and the avro schema).
Here is an example:
`-- this will not delete the topic or avro schema`
`DROP STREAM foo;`

`-- this will delete the topic and avro schema if the format is avro`
`DROP STRAEM foo DELETE TOPIC;`

This fixes #1217 

### Testing done 
Integration test was added for both deleting and not deleting topic and avro schema.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [x] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java [hunk 1]
```diff
@@ -58,14 +67,22 @@ public DdlCommandResult run(MetaStore metaStore, boolean isValidatePhase) {
         new DropTopicCommand(dataSource.getKsqlTopic().getTopicName());
     metaStore.deleteSource(sourceName);
     dropTopicCommand.run(metaStore, isValidatePhase);
-    if (!isValidatePhase && dataSource.getKsqlTopic().getKsqlTopicSerDe().getSerDe()
-                            == DataSource.DataSourceSerDe.AVRO) {
+    if (!isValidatePhase && withTopic) {
       try {
-        schemaRegistryClient
-            .deleteSubject(sourceName + KsqlConstants.SCHEMA_REGISTRY_VALUE_SUFFIX);
+        kafkaTopicClient.deleteTopics(Arrays.asList(dataSource.getKsqlTopic().getKafkaTopicName()));
```
Comment (dguy) [inline ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: Collections.singletonList(..)

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java [hunk 2]
```diff
@@ -58,14 +67,22 @@ public DdlCommandResult run(MetaStore metaStore, boolean isValidatePhase) {
         new DropTopicCommand(dataSource.getKsqlTopic().getTopicName());
     metaStore.deleteSource(sourceName);
     dropTopicCommand.run(metaStore, isValidatePhase);
-    if (!isValidatePhase && dataSource.getKsqlTopic().getKsqlTopicSerDe().getSerDe()
-                            == DataSource.DataSourceSerDe.AVRO) {
+    if (!isValidatePhase && withTopic) {
```
Comment (dguy) [inline ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: readability would be better if this block was extracted into a method

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java [hunk 3]
```diff
@@ -58,14 +67,22 @@ public DdlCommandResult run(MetaStore metaStore, boolean isValidatePhase) {
...
       try {
-        schemaRegistryClient
-            .deleteSubject(sourceName + KsqlConstants.SCHEMA_REGISTRY_VALUE_SUFFIX);
+        kafkaTopicClient.deleteTopics(Arrays.asList(dataSource.getKsqlTopic().getKafkaTopicName()));
       } catch (Exception e) {
-        throw new KsqlException("Could not clean up the schema registry for topic: " + sourceName,
-                                e);
+        throw new KsqlException("Could not delete the corresponding kafka topic: "
```
Comment (dguy) [inline ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: If this fails maybe we should save the exception and still try and delete from the schema registry?
Maybe we should retry, too? I guess it is hard to tell from the Exception if it is retryable

File: ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java [hunk 4]
```diff
@@ -180,10 +180,30 @@ public void shouldCleanUpSchemaRegistry() throws Exception {
...
+        .record("Test").fields()
+        .name("clientHash").type().fixed("MD5").size(16).noDefault()
+        .endRecord();
+    ksqlEngine.getSchemaRegistryClient().register("BAR-value", schema);
+
+    assertThat(schemaRegistryClient.getAllSubjects(), hasItem("BAR-value"));
+    ksqlEngine.terminateQuery(new QueryId("CTAS_BAR"), true);
+    ksqlEngine.buildMultipleQueries("DROP TABLE bar;", Collections.emptyMap());
+    assertThat(topicClient.isTopicExists("BAR"), equalTo(true));
+    assertThat(schemaRegistryClient.getAllSubjects().contains("BAR-value"), equalTo(true));
```
Comment (dguy) [inline ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java]: `assertThat(..., containsString(...))`;

File: ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4 [hunk 5]
```diff
@@ -62,8 +62,8 @@ statement
     | CREATE TABLE (IF NOT EXISTS)? qualifiedName
             (WITH tableProperties)? AS query                                #createTableAs
     | DROP TOPIC (IF EXISTS)? qualifiedName                                 #dropTopic
-    | DROP STREAM (IF EXISTS)? qualifiedName                                #dropStream
-    | DROP TABLE (IF EXISTS)? qualifiedName                                 #dropTable
+    | DROP STREAM (IF EXISTS)? qualifiedName (WITH TOPIC)?                  #dropStream
```
Comment (dguy) [inline ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4]: I wonder if `WITH` is right here? The topic already gets dropped from the metastore. Perhaps it should be `DELETE`?

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java (hunk 2 above)
Comment (hjafarpour) [reply ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: Moved it into a method.

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java (hunk 3 above)
Comment (hjafarpour) [reply ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: Good point, added retry block for both delete topic and delete schema.

File: ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java (hunk 4 above)
Comment (hjafarpour) [reply ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java]: Actually subjects is a collection. Changed it into `hasItem()`.

File: ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4 (hunk 5 above)
Comment (hjafarpour) [reply ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4]: We have KSQL topic and kafka topic. You are right, the KSQL topic is dropped from the metastore but this is for Kafka topic. Can you elaborate on how using `DELETE` would look like?

**Comment by blueedgenick** [comment]
agree with @dguy that (over)-using the WITH construct here feels kinda clumsy and not intuitively the "most SQL-y way" we could do this.
Perhaps `DELETE STREAM foo` is an option - although that seems sufficiently similar to DROP that it could be too easy to use one when you meant the other?
Maybe combine both DROP and DELETE keywords together (as that's really the functionality we are trying to enable) - something like `DROP STREAM foo DELETE`.
Another choice, more database-y, could be to introduce a CASCADE keyword  - so `DROP STREAM foo CASCADE` would mean to remove the physical Kafka topic along with the metastore stream definition. Downside of this one is that it's not _quite_ the same meaning of CASCADE in RDBMS but perhaps it feels closer than the other choices.

**Comment by xvrl** [comment]
agree with @blueedgenick  `WITH TOPIC` is not explicit enough, it doesn't convey the fact that the topic will be deleted.  From reading the issue, we only intend to do this for topics that were created by ksql, but in this case people might accidentally delete their source topics, which they probably never intend to do.
Also, you will have to consider the fact that the topic is only marked for deletion and will not disappear right away, so you won't be able to re-create your stream immediately, so this doesn't completely solve the issue. 
BTW, this is the reason we haven't implemented topic deletion in C3 yet, because the way it behaves is counter-intuitive.

**Comment by hjafarpour** [comment]
How about `DROP STREAM foo AND DELETE TOPIC`? This is more explicit. I'm open for more suggestions too! :)

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java [hunk 6]
```diff
@@ -58,16 +70,57 @@ public DdlCommandResult run(MetaStore metaStore, boolean isValidatePhase) {
...
+                                                    + dataSource.getKsqlTopic().getTopicName()
+                                                    + "' was marked for deletion. Actual deletion "
+                                                    + "and removal from brokers may take some time "
+                                                    + "to complete." : ""));
+  }
+
+  private void deleteTopicIfNeeded(StructuredDataSource dataSource, boolean isValidatePhase) {
+    if (!isValidatePhase && withTopic) {
+      int retries = 0;
+      while (retries < NUM_RETRIES) {
```
Comment (dguy) [inline ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: We can extract the retry logic into a method and use it in both places here, i.e, 

```
private void executeWithRetries(Callable<Void> callable, String errorMessage) {
    int retries = 0;
    while(retries < NUM_RETRIES) {
      try {
        callable.call();
      } catch (Exception e) {
        retries++;
      }
    }

    if (retries == NUM_RETRIES) {
      throw new KsqlException(errorMessage);
    }
}

Comment (hjafarpour) [reply ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: Made the change.

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java [hunk 7]
```diff
@@ -58,16 +71,60 @@ public DdlCommandResult run(MetaStore metaStore, boolean isValidatePhase) {
...
+            schemaRegistryClient
+                .deleteSubject(sourceName + KsqlConstants.SCHEMA_REGISTRY_VALUE_SUFFIX);
+            return null;
+          }
+        }, "Could not clean up the schema registry for topic: " + sourceName);
+      }
+    }
+  }
+
+  private void executeWithRetries(Callable<Void> callable, String errorMessage) {
```
Comment (apurvam) [inline ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: Hmm. THis looks like a dup of https://github.com/confluentinc/ksql/blob/master/ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java#L337

It might be better to just have a singular `deleteTopic` method in `KafkaTopicClient`, have that execute with retries, and call the singular version here. Would be a good simplification.

File: ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropTable.java [hunk 8]
```diff
@@ -68,14 +84,16 @@ public boolean equals(Object obj) {
...
+           && (exists == o.exists)
+           && (withTopic == o.withTopic);
   }
 
   @Override
   public String toString() {
     return toStringHelper(this)
         .add("tableName", tableName)
         .add("exists", exists)
+        .add("withTopic", withTopic)
```
Comment (apurvam) [inline ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropTable.java]: Should this be `deleteTopic`?

File: ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropStream.java [hunk 9]
```diff
@@ -69,14 +85,16 @@ public boolean equals(Object obj) {
...
+           && (exists == o.exists)
+           && (withTopic == o.withTopic);
   }
 
   @Override
   public String toString() {
     return toStringHelper(this)
         .add("tableName", streamName)
         .add("exists", exists)
+        .add("withTopic", withTopic)
```
Comment (apurvam) [inline ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropStream.java]: Should this be `deleteTopic`?

File: ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java [hunk 10]
```diff
@@ -186,10 +187,30 @@ public void shouldCleanUpSchemaRegistry() throws Exception {
...
     assertThat(schemaRegistryClient.getAllSubjects(), hasItem("BAR-value"));
     ksqlEngine.terminateQuery(new QueryId("CTAS_BAR_0"), true);
-    ksqlEngine.buildMultipleQueries("DROP TABLE bar;", Collections.emptyMap());
+    ksqlEngine.buildMultipleQueries("DROP TABLE bar DELETE TOPIC;", Collections.emptyMap());
+    assertThat(topicClient.isTopicExists("BAR"), equalTo(false));
     assertThat(schemaRegistryClient.getAllSubjects().contains("BAR-value"), equalTo(false));
   }
 
+  @Test
+  public void shouldNotDeleteSchemaFromSchemaRegistry() throws Exception {
```
Comment (apurvam) [inline ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java]: This should be renamed to `shouldNotDeleteSchemaNorTopic`. Also add separate tests for `drop stream`.

File: ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java [hunk 11]
```diff
@@ -186,10 +187,30 @@ public void shouldCleanUpSchemaRegistry() throws Exception {
 
     assertThat(schemaRegistryClient.getAllSubjects(), hasItem("BAR-value"));
     ksqlEngine.terminateQuery(new QueryId("CTAS_BAR_0"), true);
-    ksqlEngine.buildMultipleQueries("DROP TABLE bar;", Collections.emptyMap());
+    ksqlEngine.buildMultipleQueries("DROP TABLE bar DELETE TOPIC;", Collections.emptyMap());
+    assertThat(topicClient.isTopicExists("BAR"), equalTo(false));
```
Comment (apurvam) [inline ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java]: This test sholud be renamed to something like `shouldCleanupSchemaAndTopic`. Also, we should add cases for the `drop stream` path as well.

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java (hunk 7 above)
Comment (dguy) [reply ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: One way to do this would be to try and generalize the `executeWithRetries` such that it can be used in all places, i.e., perhaps by making changing the function signature to:
`<T> T executeWithRetries(Callable<T> callable, String errorMessage)`

You can then maybe refactor into a single function that is called from both places

Comment (apurvam) [reply ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: This seems like a good change for a followup. I recommend capturing these details in a new issue and labeling them 'good first issue' and 'help wanted'. Then github will help new potential contributors find these issues and hence make useful and manageable first patches. See: https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

Comment (xvrl) [reply ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: @apurvam those kinds of things should probably live in common and not be project-specific

File: ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java [hunk 12]
```diff
@@ -173,7 +174,26 @@ public void shouldNotEnforceTopicExistanceWhileParsing() throws Exception {
...
+    Schema schema = SchemaBuilder
+        .record("Test").fields()
+        .name("clientHash").type().fixed("MD5").size(16).noDefault()
+        .endRecord();
+    ksqlEngine.getSchemaRegistryClient().register("BAR-value", schema);
+
+    assertThat(schemaRegistryClient.getAllSubjects(), hasItem("BAR-value"));
+    ksqlEngine.terminateQuery(new QueryId("CSAS_BAR_0"), true);
+    ksqlEngine.buildMultipleQueries("DROP STREAM bar DELETE TOPIC;", Collections.emptyMap());
+    assertThat(topicClient.isTopicExists("BAR"), equalTo(false));
```
Comment (apurvam) [inline ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java]: nit: here and elsewhere, you can do `assertTrue` and `assertFalse` instead.

Comment (hjafarpour) [reply ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java]: Yes, but @dguy likes `assertThat` :)

File: ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java (hunk 7 above)
Comment (hjafarpour) [reply ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java]: I like the @apurvam 's suggestion. This can be a good follow up change and can be used as a way to engage the community more!

File: ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java (hunk 12 above)
Comment (dguy) [reply ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java]: in this case i'd use `assertFalse`, i.e., it is testing a boolean
