### PR TITLE
fix(ksql): allow migrations tool to run connector commands with IF [NOT] EXISTS clauses

### LINKED ISSUE #8014: Migrations fails when using `create connector if not exists`
**Describe the bug**
KSQL Migration with `CREATE CONNECTOR IF NOT EXISTS` fails if the connector already exists.

**To Reproduce**
1. Apply migration file containing `CREATE CONNECTOR IF NOT EXISTS` statement
2. Reset migration metadata: `ksql-migrations destroy-metadata`
3. Apply migration file again

**Expected behavior**
Migration should apply with no error

**Actual behaviour**
Migration fails:
```
"errorMessage":"{\"error_code\":409,\"message\":\"Connector SQS_SOURCE_DELIVERY_ENQUEUED already exists\"}","warnings":[]}
```

### PR DESCRIPTION
**Pull request by jzaralim**
### Description 
Fixes #8014 

Requires #8851 to be merged for the build to pass.

### Testing done 
Unit + integration testing

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java [hunk 1]
```diff
@@ -61,8 +61,8 @@
       Pattern.CASE_INSENSITIVE);
   private static final Pattern UNSET_PROPERTY = Pattern.compile(
       "\\s*UNSET\\s+'((?:[^']*|(?:''))*)'\\s*;\\s*", Pattern.CASE_INSENSITIVE);
-  private static final Pattern DROP_CONNECTOR =
-      Pattern.compile("\\s*DROP\\s+CONNECTOR\\s+(.*?)\\s*;\\s*", Pattern.CASE_INSENSITIVE);
+  private static final Pattern DROP_CONNECTOR = Pattern.compile(
+      "\\s*DROP\\s+CONNECTOR\\s+(IF\\s+EXISTS\\s+)?(.*?)\\s*;\\s*", Pattern.CASE_INSENSITIVE);
```
Comment (jnh5y) [inline ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java:65]: For my own understanding, should there be a similar update for a regex for the create connector change?

**Review by jnh5y — APPROVED** [review]

File: ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java (hunk 1 above)
Comment (jzaralim) [reply ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java:65]: Because `CREATE CONNECTOR` statements have so many components in it, we just use the ksql parser to extract the class name/properties etc instead of using regex.

File: ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/CommandParserTest.java [hunk 2]
```diff
@@ -403,6 +434,24 @@ public void shouldParseDropConnectorStatement() {
...
+    final String dropConnector = "DRoP CONNEcTOR IF EXISTS `jdbc-connector` ;";
+
+    // When:
+    List<SqlCommand> commands = parse(dropConnector);
+
+    // Then:
+    assertThat(commands.size(), is(1));
+    assertThat(commands.get(0).getCommand(), is(dropConnector));
+    assertThat(commands.get(0), instanceOf(SqlDropConnectorStatement.class));
+    assertThat(commands.get(0).getCommand(), is(dropConnector));
```
[the remark this answers is not in the document]
Comment (jzaralim) [reply ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/CommandParserTest.java]: Yeah, copy paste error
