### PR TITLE
[bugfix] Fix TOPK ArrayStore Exception

### LINKED ISSUE #686: TOPK throws ArrayStoreException
```
ksql> CREATE stream logs (request varchar, agent varchar, response int, TIMESTAMP varchar) WITH (kafka_topic='logstash_logs_json' , value_format='json');

ksql> SET 'auto.offset.reset' = 'earliest';

ksql> SELECT REQUEST, RESPONSE FROM LOGS LIMIT 10;
/rss/ | 304
/rss/ | 301
/rss/ | 200
/assets/css/screen.css?v=80778902a6 | 200
/ | 301
/ | 200
/2016/05/24/lifting-the-lid-on-obiee-12c-web-services-part-1/amp/ | 301
/2016/05/24/lifting-the-lid-on-obiee-12c-web-services-part-1/amp/ | 200
/ | 301
/robots.txt | 301
LIMIT reached for the partition.
Query terminated
ksql>
```

Using `TOPK` throws an error: 

```
ksql> SELECT REQUEST,TOPK(RESPONSE,5) FROM LOGS GROUP BY REQUEST;
/rss/ | [304.0, 0.0, 0.0, 0.0, 0.0]
 ServerError:java.lang.ArrayStoreException
Query terminated
ksql>
```

### PR DESCRIPTION
**Pull request by satybald**
Fixes #686

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkAggFunctionDeterminer.java [hunk 1]
```diff
@@ -24,30 +24,57 @@
...
 public class TopkAggFunctionDeterminer extends KsqlAggFunctionDeterminer {
+  private int topKSize = 0;
 
   public TopkAggFunctionDeterminer() {
     super("TOPK", Arrays.asList());
   }
 
+  public TopkAggFunctionDeterminer(int topKSize) {
+    this();
+    this.topKSize = topKSize;
```
Comment (satybald) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkAggFunctionDeterminer.java]: Introduce `topKSize` mainly for testing reason. To be able to specify size of the window. KSQL engine initialize this variable via `TopkKudaf#getInstance`

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java [hunk 2]
```diff
@@ -26,35 +29,33 @@
...
 
   TopkKudaf(int argIndexInValue,
-            Integer tkVal,
-            Class<T> ttClass) {
+            int topKSize,
+            Schema initialValue,
+            List<Schema> arguments,
+            Class<T> clazz) {
     super(argIndexInValue,
-          (T[]) Array.newInstance(ttClass,tkVal),
```
Comment (satybald) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java]: `Array.newInstance` is only able to allocate array at most 255 size, which is quite a small limit for streaming application.

**Comment by apurvam** [comment]
Thanks for the patch @satybald . No sure you can see the results of the CI built, but it failed with the following check style issues:

```
[INFO] Starting audit...
[ERROR] /home/****/workspace/confluentinc-pr_ksql_PR-695-4UIYU2EWL6YDJTR5ZRM2NWMSCKF2J5ATRQBDLMAAWMKHERSC2CYQ/ksql-engine/src/main/java/io/confluent/ksql/function/FunctionRegistry.java:211: Line is longer than 100 characters (found 103). [LineLength]
[ERROR] /home/****/workspace/confluentinc-pr_ksql_PR-695-4UIYU2EWL6YDJTR5ZRM2NWMSCKF2J5ATRQBDLMAAWMKHERSC2CYQ/ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java:79: Line is longer than 100 characters (found 104). [LineLength]
[ERROR] /home/****/workspace/confluentinc-pr_ksql_PR-695-4UIYU2EWL6YDJTR5ZRM2NWMSCKF2J5ATRQBDLMAAWMKHERSC2CYQ/ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java:80: Line is longer than 100 characters (found 104). [LineLength]
```

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java [hunk 3]
```diff
@@ -26,35 +29,33 @@
...
-          SchemaBuilder.array(Schema.FLOAT64_SCHEMA).build(),
```
Comment (satybald) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java]: this line caused `ArrayStoreException` as Ksql engine implicitly converted `currentAggVal` variable to Double.

**Comment by satybald** [comment]
thanks @apurvam for getting back to me promptly. No, I don't see an output of the Jenkins. But I've already fixed the code style issues. With the recent commit, the branch complies for me.

**Comment by satybald** [comment]
@apurvam @hjafarpour @rodesai @dguy I've finished the PR. Looking forward to your feedback.

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkAggFunctionDeterminer.java [hunk 4]
```diff
@@ -24,30 +24,57 @@
 import io.confluent.ksql.function.KsqlAggFunctionDeterminer;
 import io.confluent.ksql.function.KsqlAggregateFunction;
 import io.confluent.ksql.util.KsqlException;
+import org.apache.kafka.connect.data.SchemaBuilder;
 
 public class TopkAggFunctionDeterminer extends KsqlAggFunctionDeterminer {
+  private int topKSize = 0;
 
   public TopkAggFunctionDeterminer() {
     super("TOPK", Arrays.asList());
```
Comment (dguy) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkAggFunctionDeterminer.java]: Would be better if this ctor delegates to the new one you have added. And then the new one calls `super`

File: ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/TopKKudafBaseTest.java [hunk 5]
```diff
@@ -0,0 +1,16 @@
+package io.confluent.ksql.function.udaf.topk;
+
+import io.confluent.ksql.function.KsqlAggregateFunction;
+import org.apache.kafka.connect.data.Schema;
+
+import java.util.List;
+
+public abstract class TopKKudafBaseTest {
```
Comment (dguy) [inline ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/TopKKudafBaseTest.java]: I don't see the point of this abstract class. It isn't adding anything

File: ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/DoubleTopkKudafTest.java [hunk 6]
```diff
@@ -16,68 +16,72 @@
...
-public class DoubleTopkKudafTest {
+public class DoubleTopkKudafTest extends TopKKudafBaseTest {
 
-  Double[] valueArray;
   @Before
   public void setup() {
     valueArray = new Double[]{10.0, 30.0, 45.0, 10.0, 50.0, 60.0, 20.0, 60.0, 80.0, 35.0, 25.0};
-
+    topKFactory = new TopkAggFunctionDeterminer(3);
+    argumentType = Arrays.asList(Schema.FLOAT64_SCHEMA);
```
Comment (dguy) [inline ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/DoubleTopkKudafTest.java]: `Collections.singletonList(..)` elsewhere, too

File: ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/TopKKudafBaseTest.java (hunk 5 above)
Comment (satybald) [reply ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/TopKKudafBaseTest.java]: The current test is quite limited tests only small size arrays. The idea is to introduce array random generators arbitrary length and test TOPK and TOPKDISTINCT on larger arrays.

**Comment by satybald** [comment]
@dguy thanks for the review. I've applied your feedback.

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkAggFunctionDeterminer.java [hunk 7]
```diff
@@ -19,35 +19,63 @@
...
 import java.util.Arrays;
+import java.util.Collections;
 import java.util.List;
 
 import io.confluent.ksql.function.KsqlAggFunctionDeterminer;
 import io.confluent.ksql.function.KsqlAggregateFunction;
 import io.confluent.ksql.util.KsqlException;
+import org.apache.kafka.connect.data.SchemaBuilder;
 
 public class TopkAggFunctionDeterminer extends KsqlAggFunctionDeterminer {
```
Comment (satybald) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkAggFunctionDeterminer.java]: @hjafarpour what do you think if I rename `TopkAggFunctionDeterminer` to `TopKAggFunctionFactory`? I think that factory better communicates functionality of this class.

Comment (hjafarpour) [reply ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkAggFunctionDeterminer.java]: @satybald sounds good. please go ahead and rename it along with the other ones.

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java (hunk 2 above)
Comment (hjafarpour) [reply ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java]: @satybald `Array.newInstance` can create array with bigger than 255 size. The 255 limit is for the number of dimensions in the array not the size of each dimension. Here we have one dimension only.

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java [hunk 8]
```diff
@@ -26,35 +29,33 @@
...
+  private final Class<T> clazz;
+  private final Schema initialValue;
+  private final List<Schema> arguments;
 
   TopkKudaf(int argIndexInValue,
-            Integer tkVal,
-            Class<T> ttClass) {
+            int topKSize,
+            Schema initialValue,
+            List<Schema> arguments,
```
Comment (hjafarpour) [inline ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java]: Maybe rename this to `argumentTypes`.

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java (hunk 2 above)
Comment (satybald) [reply ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java]: @hjafarpour my bad, you're right. Array.newInstance can create array up to Int.MAX_VALUE for one dimension. Thought, `Array.newInstance` uses reflection to create a new instance. The rule of thumb is to avoid reflection calls as it incurs performance overhead.


> Reflection is powerful, but should not be used indiscriminately. If it is possible to perform an operation without using reflection, then it is preferable to avoid using it. The following concerns should be kept in mind when accessing code via reflection.

[https://docs.oracle.com/javase/tutorial/reflect/index.html](https://docs.oracle.com/javase/tutorial/reflect/index.html)

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java (hunk 8 above)
Comment (satybald) [reply ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java]: yup, done.

File: ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/TopKKudafBaseTest.java (hunk 5 above)
Comment (dguy) [reply ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/TopKKudafBaseTest.java]: I'd just fold this into the other tests.  I don't think it is adding any value

Comment (satybald) [reply ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/TopKKudafBaseTest.java]: I've removed this class from the PR. @dguy

**Comment by satybald** [comment]
@dguy @hjafarpour I've applied your feedback. could you please take a look?

File: ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java (hunk 2 above)
Comment (satybald) [reply ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java]: @hjafarpour good catch. I've removed it.

**Comment by miguno** [comment]
Thanks @satybald ! 👍
