### PR TITLE
fix: properly handle restore on CREATE OR REPLACE

### LINKED ISSUE #6078: Enable ksql.create.or.replace.enabled by default
Title says it all :) we probably want to wait for a few more PRs to come in before enabling this, but adding this ticket as a blocker for 0.12 to make sure we don't ship without it!

### PR DESCRIPTION
**Pull request by agavra**
(also) fixes #6078 

### Description 

In the existing code, `CREATE OR REPLACE` statements aren't handled correctly by the compactor because it did not account for the possibility of multiple queries with the same (valid) query ID existing.

This PR changes the algorithm to make it resilient to these types of changes.

### Testing done 

Added tests to `RecoveryTest`, manual testing.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java [hunk 1]
```diff
@@ -50,73 +45,92 @@ private RestoreCommandsCompactor() {
...
-        final QueuedCommand terminated = queries.remove(queryId);
-        if (terminated != null) {
-          terminatedQueries.add(terminated);
-          it.remove();
-        }
-      }
-    }
+      final QueryId queryId = plan.get().getQueryPlan().get().getQueryId();
+      markShouldSkip(queryId, latestNodeWithId);
+      final CompactedNode node = new CompactedNode(prev, queued, command);
```
Comment (vpapavas) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java:101]: So, you create a compacted node even for the previous queries that have been replaced?

Comment (agavra) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java:101]: yes, we create the node when we hit the command because we don't know at the time whether or not it will be compacted. later, when we see another node with the same queryId, we mark the older one as compacted (`shouldSkip`)

Comment (vpapavas) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java:101]: Ah, but every time you replace it when you find a new one. OK.

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java [hunk 2]
```diff
@@ -50,73 +45,92 @@ private RestoreCommandsCompactor() {
...
-        queries.putIfAbsent(queryId, cmd);
+  private static final class CompactedNode {
+
+    final CompactedNode prev;
+    final QueuedCommand queued;
+    final Command command;
+
+    boolean shouldSkip = false;
+
+    public static CompactedNode of(
```
Comment (rodesai) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java:76]: nit: consider renaming to something like `maybeAppend` - I usually read `of` as constructing a new object

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java [hunk 3]
```diff
@@ -50,73 +45,92 @@ private RestoreCommandsCompactor() {
...
+      if (queued.getAndDeserializeCommandId().getType() == Type.TERMINATE) {
+        final QueryId queryId = new QueryId(queued.getAndDeserializeCommandId().getEntity());
+        markShouldSkip(queryId, latestNodeWithId);
+
+        // terminate commands don't get added to the list of commands to execute
+        // because we "execute" them in this class by removing query plans from
+        // terminated queries
+        return prev;
+      } else if (!plan.isPresent() || !plan.get().getQueryPlan().isPresent()) {
+        // DDL
```
Comment (rodesai) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java:95]: consider asserting that if there is a previous stream/table with this ID, that it doesn't have a query associated with it?

Comment (agavra) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java:95]: I don't know how that would be possible? DDL commands don't have any associated queryID, so even though there might be sources with the same name previously, they wouldn't be the same query
