### PR TITLE
Post fix udf instance names to ensure they are unique.

### LINKED ISSUE #1328: EXTRACTJSONFIELD Doesn't work if used as args in scalar function
Sample kafka message
``` 
{
  "key1": "value1",
  "source": {
    "name": "cdc",
    "version": "0.8.0-SNAPSHOT"
  }
}
```
Created STREAM as
 ```ksql> CREATE STREAM KSQL_STREAM (key1 varchar,  source varchar) WITH (value_format = 'json', kafka_topic='mytopic');```

Running a query - 
```
SELECT EXTRACTJSONFIELD(source, '$.name'),
       EXTRACTJSONFIELD(source, '$.version'), 
       CONCAT(EXTRACTJSONFIELD(source, '$.name'), EXTRACTJSONFIELD(source, '$.version')) 
from KSQL_STREAM limit 5;
cdc | 0.8.0-SNAPSHOT | cdccdc
cdc | 0.8.0-SNAPSHOT | cdccdc
cdc | 0.8.0-SNAPSHOT | cdccdc
cdc | 0.8.0-SNAPSHOT | cdccdc
cdc | 0.8.0-SNAPSHOT | cdccdc
```

CONCAT(arg1, arg2) result as `arg1 + arg1`  if arg1 & arg1 both EXTRACTJSONFIELD.
It's working fine if one of args is not `EXTRACTJSONFIELD`.

So multiple calls of EXTRACTJSONFIELD results in the same values. (First value will return again)

I tried with code also in a udf, 
 ```
import io.confluent.ksql.function.udf.json.JsonExtractStringKudf;
JsonExtractStringKudf udf  = new JsonExtractStringKudf();
String arg1 = udf.evaluate(source, "$.name").toString() 
String arg2 = udf.evaluate(jsonString, "$.version")
```
It's return arg2 value same as arg1.

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 

Without the postfixing the code generator shares UDF instances, causing for strange results. e.g. #1328.

So, for example, without this change an expression such as:
```
CONCAT(EXTRACTJSONFIELD(source, '$.name'), EXTRACTJSONFIELD(source, '$.version')) 
```

Will be converted the following approx Java code (casts removed for readability):
```
CONCAT.evaluate(
   EXTRACTJSONFIELD.evaluate(TEST_SOURCE, "$.name"), 
   EXTRACTJSONFIELD.evaluate(TEST_SOURCE, "$.version")
);
```
Where the same `EXTRACTJSONFIELD` usf instance is called twice, meaning it can't cache results of, for example, parsing the json path.  With the change the java code looks like this:
```
CONCAT_0.evaluate(
   EXTRACTJSONFIELD_1.evaluate(TEST_SOURCE, "$.name"), 
   EXTRACTJSONFIELD_2.evaluate(TEST_SOURCE, "$.version")
);
```
Meaning there are two separate UDF instances.

Fixes #1328

### Testing done 
Suitable unit tests added.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java [hunk 1]
```diff
@@ -528,4 +535,20 @@ public void testStringUDFExpr() throws Exception {
...
+
+        ExpressionMetadata expressionEvaluator0 = codeGenRunner.buildCodeGenFromParseTree(
+            analysis.getSelectExpressions().get(0));
+
+        final Kudf[] udfs = expressionEvaluator0.getUdfs();
+
+        Object result0 = expressionEvaluator0.getExpressionEvaluator()
+                .evaluate(new Object[]{udfs[0], udfs[1], udfs[2], udfs[3], "Hello"});
+
+        assertThat(result0, equalTo("el-o"));
```
Comment (apurvam) [inline ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java]: For my understanding, what's happening is that when the same UDF is called twice in the same expression, both invocations share the same instance, and hence evaluate to the same value. So without this bugfix, `result0` would have been `el-el`?

File: ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java [hunk 2]
```diff
@@ -129,7 +130,7 @@ protected Object visitFunctionCall(FunctionCall node, Object context) {
       String functionName = node.getName().getSuffix();
       KsqlFunction ksqlFunction = functionRegistry.getFunction(functionName);
       parameterMap.put(
-          node.getName().getSuffix(),
+          node.getName().getSuffix() + "_" + functionCounter++,
```
Comment (rodesai) [inline ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java]: It's important that the name generated by this Visitor match the name generated by SqlToJavaVisitor, which feels brittle to me. I think a better way of doing this might be to move building the parameter map into SqlToJavaVisitor so that it returns code and a spec of the expected parameters. What do you think?

Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java]: I agree, but I wanted to keep this change small. The work I've got coming up on quoted identifiers will see big changes in this area of the code, so I figured I'd learn the code now and make the bigger changes later.

Comment (rodesai) [reply ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java]: Sounds good to me.

File: ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java (hunk 1 above)
Comment (big-andy-coates) [reply ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java]: Without the bug fix the same instance is shared. How this affects the outcome depends on the UDF in question. If the UDF stores any state, e.g. `EXTRACTJSONFIELD` only parsers the JSON path on the first invocation, then the stored state is only valid for the first invocation. Subsequent invocations are executing with the wrong state.
