### PR TITLE
fix: Ignore schema id when creating internal topics #9163 

### LINKED ISSUE #9163: Cannot execute a JOIN when one of the sources uses a schema referenced by ID
**Describe the bug**
ksqlDB cannot execute a JOIN when one of the sources uses a schema referenced by ID. This is because of the interaction of these 2 behaviors:

1. When a join requires a repartition, ksqlDB will try to use the physical schema of the source being repartitioned to write to the repartition topic, if the source has a schema ID

2. For joins, ksqlDB first does a projection to a new schema that prefixes each column with the source name. So, for example if I do:
```
CREATE STREAM SOURCE (A STRING, B STRING) WITH ...
CREATE STREAM SOURCE2 (A STRING, B STRING) WITH ...
CREATE STREAM OUT AS SELECT SOURCE.*, SOURCE2.* FROM SOURCE JOIN SOURCE 2 ...
```
Then, the repartition schema has columns like `SOURCE_A STRING, SOURCE_B STRING, SOURCE2_A STRING, SOURCE2_B STRING`

The problem here is that the source schema referenced by ID does not have fields that are prefixed with the source name. So when ksqlDB goes to serialize the records for writing to the repartition topic, the serializer complains that there is no field in the schema that matches the field name in the record:

```
Caused by: org.apache.kafka.streams.errors.StreamsException: Error encountered sending record to topic _confluent-ksql-some.ksql.service.idquery_CSAS_OUT_0-Join-repartition for task 0_0 due to:
org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: _confluent-ksql-some.ksql.service.idquery_CSAS_OUT_0-Join-repartition. Schema from Schema Registry misses field with name: S_A
```

**To Reproduce**
Here's a QTT:
```
{
      "statements": [
        "CREATE STREAM SOURCE WITH (kafka_topic='source', format='PROTOBUF', KEY_SCHEMA_ID=1, KEY_SCHEMA_FULL_NAME='ProtobufKey2', VALUE_SCHEMA_ID=2, VALUE_SCHEMA_FULL_NAME='ProtobufValue2');",
        "CREATE TABLE SINK WITH (kafka_topic='source2', format='PROTOBUF', KEY_SCHEMA_FULL_NAME='ProtobufKey2', VALUE_SCHEMA_FULL_NAME='ProtobufValue2');",
        "CREATE STREAM OUT AS SELECT S.*, SS.* FROM SOURCE S JOIN SINK SS ON S.B=SS.K;"
      ],
      "topics": [
        {
          "name": "source",
          "keyFormat": "PROTOBUF",
          "keySchema": "syntax = \"proto3\"; message ProtobufKey1 {uint32 k1 = 1;} message ProtobufKey2 {string K = 1;}",
          "valueFormat": "PROTOBUF",
          "valueSchema": "syntax = \"proto3\"; message ProtobufValue1 {float c1 = 1; uint32 c2 = 2;} message ProtobufValue2 {uint64 A = 1; string B = 2;}"
        },
        {
          "name": "source2",
          "keyFormat": "PROTOBUF",
          "keySchema": "syntax = \"proto3\"; message ProtobufKey1 {uint32 k1 = 1;} message ProtobufKey2 {string K = 1;}",
          "valueFormat": "PROTOBUF",
          "valueSchema": "syntax = \"proto3\"; message ProtobufValue1 {float c1 = 1; uint32 c2 = 2;} message ProtobufValue2 {uint64 A = 1; string B = 2;}"
        }
      ],
      "inputs": [
        {"topic": "source", "key": {"K": "0"}, "value": {"A": 123, "B": "falcon"}, "timestamp": 0},
        {"topic": "source", "key": {"K": "0"}, "value": {"A": 456, "B": "giraffe"}, "timestamp": 0},
        {"topic": "source", "key": {"K": "0"}, "value": {"A": 789, "B": "turtle"}, "timestamp": 0},
        {"topic": "source2", "key": {"K": "0"}, "value": {"A": 123, "B": "falcon"}, "timestamp": 0},
        {"topic": "source2", "key": {"K": "0"}, "value": {"A": 456, "B": "giraffe"}, "timestamp": 0},
        {"topic": "source2", "key": {"K": "0"}, "value": {"A": 789, "B": "turtle"}, "timestamp": 0}
      ],
      "outputs": [
          // doesn't matter
      ]
}
```

**Expected behavior**
The join should execute correctly

**Additional context**
I think the right approach here is not to forward the schema id along to the repartition serdes. They should just generate their own schema to use for the repartition topic.

### PR DESCRIPTION
**Pull request by bvarghese1**
### Description
- Fixes #9163 
- Previously, if schema_id was passed in the left/right schema during create
  eg: CREATE STREAM SOURCE
        WITH (KAFKA_TOPIC='source', KEY_SCHEMA_ID=1, VALUE_SCHEMA_ID=2)
  and if the user tried to perform a  join, the join would fail with a serialization 
  exception because it would try to lookup the schema based on the schema id
- When a join is performed, we repartition the data by creating a repartition topic
  and changing the repartition key. This commit therefore ignores the schema id
  and force creates a repartition schema thus allowing the join to be performed
- Additionally, the fix also fixes schema ids used in group-by, partition-by, and
  table-table key join
- Foreign key joins are not fixed with this PR and a separate issue will be created
   for the same

### Testing done 
Added QTTs
Manually tested on CP using CLI/UI

### CODE REVIEW

File: ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoiningNode.java [hunk 1]
```diff
@@ -40,11 +45,30 @@ public interface JoiningNode {
    */
   void setKeyFormat(KeyFormat format);
 
+  static ImmutableMap<String, String> getProperties(FormatInfo formatInfo) {
```
Comment (vcrfxia) [inline ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoiningNode.java:48]: Rename to be more informative: `getPropertiesWithoutSchemaId()` or similar. 

Also, I think it'd be cleaner to have this be a method on `KeyFormat`/`ValueFormat` (e.g., `copyWithoutSchemaId()`) which can then delegate to an analogous method for `FormatInfo`, rather than having `JoiningNode` be responsible for maintaining this. If someone updates either `KeyFormat` or `FormatInfo` to contain a new property in the future, and doesn't realize that the copy in this file needs to add the new property as well, then that's easy room for introducing bugs.

File: ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoiningNode.java [hunk 2]
```diff
@@ -40,11 +45,30 @@ public interface JoiningNode {
...
+        formatInfo
+            .getProperties()
+            .entrySet()
+            .stream()
+            .filter(x -> !x.getKey().equals(ConnectProperties.SCHEMA_ID))
+            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue))
+    ).build();
+  }
+
   static ValueFormat getValueFormatForSource(final PlanNode sourceNode) {
```
Comment (vcrfxia) [inline ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoiningNode.java:61]: This change is interesting. I think what's happening is that this method name is confusing -- it makes it sound like it returns value formats for source streams/tables (which it does today) but its usage is for internal topics used as part of joins (which is why it's correct to update the format away from what the source format is, to what we want to use for internal topics instead). Is that your understanding of this method as well?

If so, I think I cleaner way to implement this change is to update `InternalFormats.of()` to strip out the schema ID format property (if present) from both key and value formats. If my understanding of the changes in this PR is correct, that should have the same effect and means we can make the changes in this PR in just one place instead of two (JoiningNode for values, and PreJoinRepartitionNode for keys).

A consequence of my suggestion, though, is that other types of operations which require internal topics (group by, aggregate, etc) will also pick up the change to remove schema ID, and not just joins. I think that's a good thing but it'd be good to check -- do you know if group bys and aggregates are affected by the same bug as the join bug that you're trying to resolve? I can't think of a reason that they wouldn't be, but I probably haven't given it as much thought as you have.

File: ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PreJoinRepartitionNode.java [hunk 3]
```diff
@@ -143,25 +144,33 @@ private Optional<KeyFormat> maybeForceInternalKeyFormat(final KeyFormat format)
 
     if (requiresRepartition() || forceRepartition) {
       // Node is repartitioning already:
-      forcedInternalKeyFormat = Optional.of(format);
+      forcedInternalKeyFormat = Optional.of(removeSchemaIdIfPresent(format));
```
Comment (vcrfxia) [inline ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PreJoinRepartitionNode.java:147]: Rather than applying the helper method in four different places in this method, it'd be better to apply it once upfront and then use the modified format throughout. That minimizes the risk that someone will add another usage of `format` into this method later and forget to apply the helper method (thereby introducing a bug).

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json [hunk 4]
```diff
@@ -3754,6 +3754,246 @@
         "type": "io.confluent.ksql.util.KsqlStatementException",
         "message": "Implicit repartitioning of windowed sources is not supported. See https://github.com/confluentinc/ksql/issues/4385."
       }
+    },
+    {
```
Comment (vcrfxia) [inline ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json:3758]: The PR description makes it sound like this fix is for foreign key joins but none of these new test cases are for FK joins. Your fix is for all types of joins, right? Let's update the PR description (and title) to make that clear, and add a test case for an FK join as well (see `fk-joins.json`).

**Review by vcrfxia — COMMENTED** [review]
Thanks @bvarghese1 , left some comments inline. I worry that the current fix is a bit brittle and made an alternative suggestion inline. I'm not 100% sure that the alternative suggestion works yet, since I don't fully understand the scope of the bug (whether it impacts more than just joins), but if it does then I think it will be a much cleaner approach.

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json (hunk 4 above)
Comment (bvarghese1) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json:3758]: Yes, the fix applies to all types of joins. I will update the description and add the the test in `fk-joins.json` as suggested.

File: ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoiningNode.java (hunk 2 above)
Comment (bvarghese1) [reply ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoiningNode.java]: Yes, I was looking to update the format only for internal topics and found this method being used during joins.

I agree updating the `InternalFormats.of` is a cleaner way to do it.

Looking at the code, it looks like groupbys and aggregates are affected by the same bug since they are also using the same `InternalFormats.of` method. Will add a test for groupby.

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json (hunk 4 above)
Comment (bvarghese1) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json:3758]: After investigating, foriegn-key joins with schema ids are not working with the fix in this PR. The error is also different as compared to other joins. I will open a new issue for fk-joins.

Comment (bvarghese1) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json:3758]: Create issue - https://github.com/confluentinc/ksql/issues/9516

File: ksqldb-common/src/main/java/io/confluent/ksql/serde/FormatInfo.java [hunk 5]
```diff
@@ -33,6 +34,8 @@ public final class FormatInfo {
   private final String format;
   private final ImmutableMap<String, String> properties;
 
+  private static final String SCHEMA_ID = "schemaId";
```
Comment (vcrfxia) [inline ksqldb-common/src/main/java/io/confluent/ksql/serde/FormatInfo.java:37]: Ah I see, this constant is currently defined in the ksqldb-serde package but you need it from ksqldb-common here. I think it's best to avoid duplication, in case one evolves without the other in the future (unlikely but possible). What do you think about changing `copyWithoutSchemaId()` to take the string key to filter out as an argument? For example, `copyWithoutProperty(String propName)`

File: ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java [hunk 6]
```diff
@@ -164,7 +165,7 @@ public void shouldBuildStepForAggregate() {
             ExecutionStepFactory.streamAggregate(
                 queryContext,
                 schemaGroupedStream.getSourceStep(),
-                Formats.of(keyFormatInfo, valueformatInfo, SerdeFeatures.of(), SerdeFeatures.of()),
+                InternalFormats.of(keyFormat, valueformatInfo),
```
Comment (vcrfxia) [inline ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java:168]: Let's not update these tests to use `InternalFormats.of()` -- the purpose of these tests is to (indirectly) verify that `InternalFormats.of()` behaves as expected in all these different cases. (There's no dedicated unit-test coverage for `InternalFormats.of()` AFAIA.) In fact, this could be a good place for you to add unit test coverage for your case (schema ID) as well.

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json [hunk 7]
```diff
@@ -2921,6 +2921,90 @@
         {"topic": "OUTPUT", "key": {"F1": 1}, "value": {"SUM": 1}},
         {"topic": "OUTPUT", "key": {"F1": 1}, "value": {"SUM": 2}}
       ]
+    },
+    {
+      "name": "stream-table with PROTOBUF schema and schema_id",
```
Comment (vcrfxia) [inline ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json:2926]: This name makes it sound like the test is for a join. How about simply "PROTOBUF schema with schema_id" instead? And similar for the other new GROUP BY test.

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json [hunk 8]
```diff
@@ -3754,6 +3754,246 @@
...
+      "post": {
+        "sources": [
+          {
+            "name": "OUT",
+            "type": "stream",
+            "keyFormat": {"format": "AVRO", "properties": {"fullSchemaName": "io.confluent.ksql.avro_schemas.OutKey"}, "features": ["UNWRAP_SINGLES"]},
+            "schema": "SS_ROWKEY STRUCT<K STRING> KEY, S_ROWKEY STRUCT<K STRING>, S_A INTEGER , S_B STRING, SS_A INTEGER, SS_B STRING"
+          }
+        ]
+      }
```
Comment (vcrfxia) [inline ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json:3996]: Thanks for the test coverage! Can we add a quick test for stream-stream joins, too, for completeness? Also, you can add a test with JSON_SR (the third SR-enabled key format supported today) in the process. (No need to go back and add JSON_SR coverage for all the other test cases you've already added, though, since I don't think it should be fundamentally different from Avro.)

**Review by vcrfxia — COMMENTED** [review]
Thanks @bvarghese1 . This is looking great! A few more minor comments inline but afterwards we'll be ready to merge.

File: ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java (hunk 6 above)
Comment (bvarghese1) [reply ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java:168]: https://github.com/confluentinc/ksql/blob/master/ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java#L97
The SchemaKGroupedStream calls the `streamAggregate` method with `InternalFormats.of()` method and therefore I updated the test to reflect the same.

Comment (vcrfxia) [reply ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java:168]: Right but if you look at the different tests that you've modified in this file, the assertions are now all the same even though they're meant to be different test cases. These changes would be fine if we had separate unit tests for `SchemaKGroupedStream` and `InternalFormats` but we don't. As the test situation currently stands, these changes have removed test coverage for `InternalFormats`.

File: ksqldb-common/src/main/java/io/confluent/ksql/serde/FormatInfo.java (hunk 5 above)
Comment (bvarghese1) [reply ksqldb-common/src/main/java/io/confluent/ksql/serde/FormatInfo.java:37]: Adding dependency introduces a circular dependency between `ksqldb-serde` and `ksqldb-common` modules.

`copyWithoutProperty(String propName)` will resolve that dependency issue since the constant will be passed from the `InternalFormats` class from ksqldb-engine

File: ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java (hunk 6 above)
Comment (bvarghese1) [reply ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java:168]: Got it. Thanks

File: ksqldb-engine/src/main/java/io/confluent/ksql/serde/InternalFormats.java [hunk 9]
```diff
@@ -45,22 +46,23 @@ private InternalFormats() {
...
+  public static Formats of(final KeyFormat keyFormat, final FormatInfo valueFormatInfo) {
     // Do not use NONE format for internal topics:
     if (keyFormat.getFormatInfo().getFormat().equals(NoneFormat.NAME)) {
       throw new IllegalArgumentException(NoneFormat.NAME + " can not be used for internal topics");
     }
 
     return Formats.of(
-        keyFormat.getFormatInfo(),
-        valueFormat,
+        keyFormat.getFormatInfo().copyWithoutProperty(ConnectProperties.SCHEMA_ID),
```
Comment (vcrfxia) [inline ksqldb-engine/src/main/java/io/confluent/ksql/serde/InternalFormats.java:61]: It'd be good to add a quick comment here to explain why SCHEMA_ID is being removed. Something like "Internal formats should not use user-specified schema IDs" (or whatever you think it clearest).

File: ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java [hunk 10]
```diff
@@ -118,8 +119,10 @@ public void setUp() {
     when(keyFormatInfo.getFormat()).thenReturn(FormatFactory.KAFKA.name());
     when(keyFormat.getFormatInfo()).thenReturn(keyFormatInfo);
     when(keyFormat.withSerdeFeatures(any())).thenReturn(keyFormat);
+    when(keyFormat.getFormatInfo().copyWithoutProperty(Mockito.anyString())).thenReturn(keyFormatInfo);
```
Comment (vcrfxia) [inline ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java:122]: It'd be good to have test coverage for SCHEMA_ID removal. You can achieve that without significant changes by updating this to:
* specify the SCHEMA_ID property instead of `anyString()`
* returning a different mock format info (e.g., `keyFormatInfoWithoutSchemaId`) from the mocked call, and updating the tests to expect this new mock instead.

**Review by vcrfxia — APPROVED** [review]
Thanks @bvarghese1 ! LGTM with two minor comments inline.

File: ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java (hunk 10 above)
Comment (bvarghese1) [reply ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java:122]: I have added a unit test to validate SCHEMA_ID removal in `FormatInfoTest.java` but I don't mind adding another test here as suggested.

Comment (vcrfxia) [reply ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java:128]: The test you added to `FormatInfoTest.java` validates that SCHEMA_ID is properly removed when the helper method is called, but there was no unit test coverage that the helper method was ever called. The new unit test to added (into `SchemaKGroupedStreamTest.java` just now) validates that.

Comment (bvarghese1) [reply ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java:128]: Ah ok!
