### PR TITLE
Fix the way `LIMIT` clauses are handled

### LINKED ISSUE #697: LIMIT is not documented in Syntax Guide
We should document `LIMIT` notably because its current behavior is per-partition, so a `LIMIT 5` on topic with 2 partitions might actually show you 10 output results.

### LINKED ISSUE #1215: "LIMIT reached for the partition" should not generate ERROR
Operators never want to see WARN/ERROR, and definitely not when the underlying behavior is valid and working as designed from customer perspective.

Therefore, when using "LIMIT", it should not generate an error in the logs:

```
[2018-04-26 09:32:58,438] ERROR stream-thread [_confluent-ksql-default_transient_125079666238829150_1524749569292-30d1d562-4cc2-41de-a909-2480b5aa2e7f-StreamThread-13] Failed to process stream task 0_7 due to the following error: (org.apache.kafka.streams.processor.internals.AssignedStreamsTasks:105)
org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_7, processor=KSTREAM-SOURCE-0000000000, topic=users, partition=7, offset=3
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:240)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:411)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:923)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:803)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
Caused by: io.confluent.ksql.util.KsqlException: LIMIT reached for the partition.
	at io.confluent.ksql.structured.QueuedSchemaKStream$QueuePopulator.apply(QueuedSchemaKStream.java:184)
	at io.confluent.ksql.structured.QueuedSchemaKStream$QueuePopulator.apply(QueuedSchemaKStream.java:161)
	at org.apache.kafka.streams.kstream.internals.KStreamPeek$KStreamPeekProcessor.process(KStreamPeek.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KTableMapValues$KTableMapValuesProcessor.process(KTableMapValues.java:106)
	at org.apache.kafka.streams.kstream.internals.KTableMapValues$KTableMapValuesProcessor.process(KTableMapValues.java:83)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.ForwardingCacheFlushListener.apply(ForwardingCacheFlushListener.java:42)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.putAndMaybeForward(CachingKeyValueStore.java:101)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.access$000(CachingKeyValueStore.java:38)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore$1.apply(CachingKeyValueStore.java:83)
	at org.apache.kafka.streams.state.internals.NamedCache.flush(NamedCache.java:142)
	at org.apache.kafka.streams.state.internals.NamedCache.evict(NamedCache.java:233)
	at org.apache.kafka.streams.state.internals.ThreadCache.maybeEvict(ThreadCache.java:243)
	at org.apache.kafka.streams.state.internals.ThreadCache.put(ThreadCache.java:153)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.putInternal(CachingKeyValueStore.java:228)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.put(CachingKeyValueStore.java:221)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.put(CachingKeyValueStore.java:38)
	at org.apache.kafka.streams.state.internals.InnerMeteredKeyValueStore.put(InnerMeteredKeyValueStore.java:198)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueBytesStore.put(MeteredKeyValueBytesStore.java:117)
	at org.apache.kafka.streams.kstream.internals.KStreamReduce$KStreamReduceProcessor.process(KStreamReduce.java:80)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:169)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:224)
	... 6 more
[2018-04-26 09:32:58,438] INFO stream-thread [_confluent-ksql-default_transient_125079666238829150_1524749569292-30d1d562-4cc2-41de-a909-2480b5aa2e7f-StreamThread-13] State transition from RUNNING to PENDING_SHUTDOWN (org.apache.kafka.streams.processor.internals.StreamThread:200)
[2018-04-26 09:32:58,438] INFO stream-thread [_confluent-ksql-default_transient_125079666238829150_1524749569292-30d1d562-4cc2-41de-a909-2480b5aa2e7f-StreamThread-13] Shutting down (org.apache.kafka.streams.processor.internals.StreamThread:1109)
```

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 
Limit clauses spam the logs with errors and warnings (#1215), is tracked per-partition, and is not documented (#697).

This PR addresses these issues.
- no longer spams the logs with errors, (fixes #1215)
- limit is now _across_ partitions, not _per_ partition.
- server can now send a 'final message' to the CLI, e.g. 'Limit Reached', (rather than using an error message to terminate the receive loop).
- LIMIT added to the docs, (fixes #697)

### Testing done 
- Added suitable unit tests.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [x] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by xvrl** [comment]
@big-andy-coates we'll also have to update the websockets endpoint to close the socket when the limit is reached. I can do this as part of #1285 though, since it refactors the code quite bit.

File: ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java [hunk 1]
```diff
@@ -85,14 +86,23 @@ public void after() {
...
 
   @Test
   public void testPrintErrorStreamedRow() throws IOException {
-    StreamedRow row = new StreamedRow(new FakeException());
-    terminal.printStreamedRow(row);
+    final FakeException exception = new FakeException();
+
+    terminal.printStreamedRow(StreamedRow.error(exception));
+
+    assertThat(terminal.getOutputString(), is(exception.getMessage() + "\n"));
```
Comment (dguy) [inline ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java]: nit: `equalTo(...)` 
same below

File: ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java [hunk 2]
```diff
@@ -67,4 +74,12 @@ public boolean equals(Object o) {
   public int hashCode() {
     return Objects.hash(rowQueue, super.hashCode());
   }
+
+  private class StateListener implements KafkaStreams.StateListener {
+    @Override
+    public void onChange(final KafkaStreams.State newState, final KafkaStreams.State oldState) {
+      isRunning.set(newState == KafkaStreams.State.RUNNING
```
Comment (dguy) [inline ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java]: if you really want to know when it is actually `RUNNING` you need to check that `oldState` was `REBALANCING` depends on what you are trying to achieve.
i.e., when the stream is started it transitions to `RUNNING`, but isn't really doing anything apart from subscribing, then goes to `REBALANCING`, then `RUNNING`

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java [hunk 3]
```diff
@@ -70,16 +72,16 @@
 
     this.disconnectCheckInterval = disconnectCheckInterval;
     this.queryMetadata = ((QueuedQueryMetadata) queryMetadata);
-
+    this.queryMetadata.getOutputNode().setLimitHandler(new LimitHandler());
```
Comment (dguy) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java]: could we put a similar method on `QueryMetadata` so we can avoid the chaining?

File: ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java (hunk 1 above)
Comment (big-andy-coates) [reply ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java]: Not sure I follow. Are you saying change to `is(equalTo(...))` or just `equalTo(...)` - IMHO `is(...)` is also perfectly valid and less key strokes :D

File: ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java (hunk 2 above)
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java]: Really, the main point is detect when its shutting down, so maybe just checking for newState being `NOT_RUNNING` would be best?

I'll switch to that.

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java (hunk 3 above)
Comment (big-andy-coates) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java]: Sure thing. Cost is 1 🍺 .

**Comment by ybyzek** [comment]
Wonderful news!!  Great PR -- thank you!

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java [hunk 4]
```diff
@@ -94,24 +96,24 @@ public void write(OutputStream out) throws IOException {
...
+        out.flush();
+      }
+    } catch (final EOFException exception) {
       // The user has terminated the connection; we can stop writing
       log.warn("Query terminated due to exception:" + exception.toString());
-    } catch (InterruptedException exception) {
+    } catch (final InterruptedException exception) {
       // The most likely cause of this is the server shutting down. Should just try to close
       // gracefully, without writing any more to the connection stream.
       log.warn("Interrupted while writing to connection stream");
```
Comment (apurvam) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java]: Should we also try to send this message to the user? Something like "Server shut down, stopping query".

File: ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java [hunk 5]
```diff
@@ -67,4 +74,15 @@ public boolean equals(Object o) {
   public int hashCode() {
     return Objects.hash(rowQueue, super.hashCode());
   }
+
+  public void setLimitHandler(final OutputNode.LimitHandler limitHandler) {
+    getOutputNode().setLimitHandler(limitHandler);
+  }
+
+  private class StateListener implements KafkaStreams.StateListener {
```
Comment (apurvam) [inline ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java]: Not for this PR, but this may be worth implementing for the `PersistentQueryMetadata` as well, and then update the metrics for the number of persistent queries, if a query stops running all of a sudden.

File: ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java [hunk 6]
```diff
@@ -428,13 +428,7 @@ public void run() {
               try {
                 StreamedRow row = queryStream.next();
                 terminal.printStreamedRow(row);
-                if (row.getErrorMessage() != null) {
-                  // got an error in the stream, which means we have reached the end.
-                  // the stream interface that queryStream uses isn't smart enough to figure
-                  // out when the socket is closed, so just break here since we know there will
-                  // be nothing more to read.
-                  LOGGER.debug("Going to stop reading results for row {} since there was an error"
```
Comment (apurvam) [inline ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java]: This was the log spam, right?

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java (hunk 4 above)
Comment (big-andy-coates) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java]: Maybe - but in a different PR...

File: ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java (hunk 5 above)
Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java]: Agreed.

File: ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java (hunk 6 above)
Comment (big-andy-coates) [reply ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java]: No, the log spam was lots of ERROR and WARNING lines, both from the Streams lib and KSQL code, because an exception was thrown by a processor node.

**Comment by big-andy-coates** [comment]
@apurvam docs updated - good catch! :D

File: ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java (hunk 2 above)
Comment (dguy) [reply ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java]: yeah - `NOT_RUNNING` in that case is better

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java (hunk 3 above)
Comment (dguy) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java]: lol

File: docs/api.rst [hunk 7]
```diff
@@ -194,7 +194,8 @@ The query resource lets you stream the output records of a ``SELECT`` statement
    :>json object row: A single row being returned. This will be null if an error is being returned.
    :>json array  row.columns: The values contained in the row.
    :>json ?      row.columns[i]: The value contained in a single column for the row. The value type depends on the type of the column.
-   :>json string errorMessage: If this field is non-null, an error has been encountered while running the statement. No additional rows are returned and the server will end the response. Note that when the limit is reached for a query that specified a limit in the LIMIT clause, the server returns a row with error message "LIMIT reached for the partition."
+   :>json string finalMessage: If this field is non-null, it contains a final message from the server. No additional rows will be returned and the server will end the response.
```
Comment (xvrl) [inline docs/api.rst]: might be worthwhile for the cli to switch to websockets as well, since this would remove the need for explicit boundary messages
