### PR TITLE
fix: delete zombie consumer groups 🧟

### LINKED ISSUE #1283: Delete consumer groups when a query is terminated
Right now, when a query is terminated, we use the streams reset tool which just resets the committed offsets for the consumer group used by the application id. 

However, for KSQL, the consumer group should really be deleted. 

Now that KIP-222 is available (https://cwiki.apache.org/confluence/display/KAFKA/KIP-222+-+Add+Consumer+Group+operations+to+Admin+API), we can delete  the consumer group once terminate is called using the Java AdminClient.

### PR DESCRIPTION
**Pull request by agavra**
fixes #1283

### Description 

Before this PR, we don't clean up consumer groups that are leftover which makes it really annoying for users to look into their existing consumer groups. This PR adds cleanup on close for persistent and transient queries.

The unfortunate part, is that the consumer group API takes a while to update when the last consumer has left the group (specifically, the `heartbeat.interval.ms` which is default to 3 seconds, needs to pass after the last consumer leaves the group). To account for this, I've taken the external resource cleanup out of the main execution path so that the UI doesn't hang when we terminate a query.

### Testing done 

Unit testing, and manual testing to make sure the resources are cleaned up.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+        .map(QueryCleanupTask.class::cast)
+        .map(t -> t.appId).collect(ImmutableSet.toImmutableSet());
+  }
+
+  public void addCleanupTask(final QueryCleanupTask task) {
+    cleanupTasks.add(task);
+  }
+
+  @VisibleForTesting
+  void awaitAllPreviousProcessed() {
```
Comment (vpapavas) [inline ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java:85]: If this is only used for testing, isn't it safer/better to move it to the testing code? You already have a method for adding tasks, all you need is a getter and then you can achieve the same, no?

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+        final boolean isTransient
+    ) {
+      this.appId = appId;
+      this.isTransient = isTransient;
+      this.serviceContext = serviceContext;
+    }
+
+    @Override
+    public void run() {
+      tryRun(
```
Comment (vpapavas) [inline ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java:116]: Do we want these three cleanups to happen atomically, i.e all or nothing?

File: ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClientImpl.java [hunk 3]
```diff
@@ -100,4 +105,23 @@ public ConsumerGroupSummary describeConsumerGroup(final String group) {
...
+    try {
+      // it takes heartbeat.interval.ms after a consumer is closed for the broker
+      // to recognize that there are no more consumers in the consumer group - for
+      // that reason, we retry after 3 seconds (the default heartbeat.interval.ms)
+      // in the case that we get a GroupNotEmptyException
+      ExecutorUtil.executeWithRetries(
+          () -> adminClient.get().deleteConsumerGroups(groups).all().get(),
+          e -> (e instanceof RetriableException)
+              || (e instanceof GroupNotEmptyException && retryCount.getAndIncrement() < 5),
+          () -> Duration.of(3, ChronoUnit.SECONDS)
```
Comment (vpapavas) [inline ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClientImpl.java:121]: Why not use the actual value of `heartbeat.interval.ms`? Why hardcode it to 3 seconds?

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java (hunk 1 above)
Comment (agavra) [reply ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java:85]: I tried this, but it's hard to do it without breaking the synchronization guarantees. Though maybe you gave me another idea I'll try out.

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java (hunk 2 above)
Comment (agavra) [reply ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java:116]: no, if one of them fails we should still try to clean the others

File: ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClientImpl.java (hunk 3 above)
Comment (agavra) [reply ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClientImpl.java:121]: it's a consumer config so it can be different for each consumer (and unfortunately this isn't a constant in the kafka code, so I can't just use a constant from that class directly)

**Review by vpapavas — APPROVED** [review]
LGTM!
