### PR TITLE
fix: do not throw error if VALUE_DELIMITER is set on non-DELIMITED topic

### LINKED ISSUE #4200: Converting DELIMITED stream to another format fails when VALUE_DELIMITER is specified
**Describe the bug**

When creating a new stream in `AVRO` or `JSON` format from a source stream defined as `DELIMITED` with an explicit delimiter set with `VALUE_DELIMITER`, the CSAS statement fails with error `Delimeter only supported with DELIMITED format`

**To Reproduce**

Problem occurs in ksqlDB 0.6.0 and newer CP 5.4.0-SNAPSHOT versions.

Step 1: Create source stream as `DELIMITED` with an explicit `VALUE_DELIMITER`:

```sql
create stream csv_stream (val1 string, val2 string) with (kafka_topic='csv-data', value_format='delimited', value_delimiter=',', partitions=1);
```

Step 2: Insert a record into the source topic:

```sql
insert into csv_stream (val1, val2) values ('v1', 'v2');
```

Step 3: Try to create a new derived stream in JSON format from `csv_stream`:

```sql
create stream json_stream with (value_format='json') as select * from csv_stream;
```

**Expected behavior**

In the example above, `json_stream` should successfully be created and convert records from CSV to JSON format in the output stream.

**Actual behaviour**

Exception occurs when executing the CSAS statement:

```
Delimeter only supported with DELIMITED format
```

Note: there's also a typo in the error message. Should say `Delimiter` instead of `Delimeter`.

### PR DESCRIPTION
**Pull request by agavra**
fixes #4200

### Description 

The `VALUE_DELIMITER` only makes sense in the context of `DELIMITED` format and today we throw an error if it is set in any other format. This PR removes that error and just ignores it if it is set on a non-delimited stream. This way:

1. users can issue commands that take a delimited topic and turn it into another format
2. if they go back to delimited (e.g. delimited->json->delimited) it will maintain the original source delimiter

Alternatively, we can just not pipe the delimiter and use the default if going from a non-delimited format back to delimited.

### Testing done 

- updated unit tests
- updated qtt
- local end-to-end testing

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java [hunk 1]
```diff
@@ -261,6 +261,7 @@ private Format getValueFormat(final Sink sink) {
       if (sink.getProperties().getValueDelimiter().isPresent()) {
         return sink.getProperties().getValueDelimiter();
       }
+
```
Comment (stevenpyzhang) [inline ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java]: extra new line?

Comment (agavra) [reply ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java]: it's intentional - I thought it was cleaner to read with a new line than without

**Comment by agavra** [comment]
This is correct, I had thought about that (see the description) - it no longer fails, and I think that's OK. It _does_ do something, it indicates that any `DELIMITED` format down the line will use this delimiter. The alternative would be to have the delimiter change when going between formats and back to delimited. Thoughts?
