### PR TITLE
Don't clobber columns when executing partition by

### LINKED ISSUE #799: Using PARTITION BY with SELECT on certain columns stores the wrong data in the output topic
We have a SYSLOG stream which is backed by a Kafka topic `log.syslog`. This is a JSON topic with the following schema: 

```json
[
  {
    "description": {
     ...
      "schema": [
        {
          "name": "ROWTIME",
          "type": "BIGINT"
        },
        {
          "name": "ROWKEY",
          "type": "VARCHAR(STRING)"
        },
        {
          "name": "NODENAME",
          "type": "VARCHAR(STRING)"
        },
        {
          "name": "META",
          "type": "VARCHAR(STRING)"
        },
        {
          "name": "K8SID",
          "type": "VARCHAR(STRING)"
        }
      ],
     ...
    }
  }
]
```

The `meta` field is nested. Here are what messages in the syslog topic look like:

```json
{
  "row": {
    "columns": [
      1519689018385,
      null,
      "ip-10-12-17-142.us-west-2.compute.internal",
      "{\"cloud\":{\"machine_type\":\"r4.xlarge\",\"region\":\"us-west-2\",\"availability_zone\":\"us-west-2a\",\"instance_id\":\"i-0e4f8ffa729d113d4\",\"provider\":\"ec2\"}}",
      "k8s2"
    ]
  },
  "errorMessage": null
}
```

Here we can see that the key is null, the third column is the node name, and the fourth is the `meta` field, with a nested structure.

Now, say we want to to partition by node name with the following query:
```sql
CREATE STREAM SYSLOG_BY_NODENAME as SELECT nodename, meta from SYSLOG PARTITION BY NODENAME;
```

We get the following output: 
```
 1519688071070 | ip-10-10-81-115.us-west-2.compute.internal | ip-10-10-81-115.us-west-2.compute.internal | ip-10-10-81-115.us-west-2.compute.internal 
```

Here we see the row time, the key is the `nodename`, the `nodename` again as part of the select, and then the `nodename` yet again instead of the`meta` field.

If we instead try to partition with the following query (note the *): 
```sql
CREATE STREAM SYSLOG_BY_NODENAME_ALL AS SELECT * FROM SYSLOG PARTITION BY NODENAME;   
```

then the `meta` column is stored correctly:
```
1519688222102 | ip-10-12-17-142.us-west-2.compute.internal | ip-10-12-17-142.us-west-2.compute.internal | {"cloud":{"region":"us-west-2","availability_zone":"us-west-2a","instance_id":"i-0e4f8ffa729d113d4","provider":"ec2","machine_type":"r4.xlarge"}} | k8s2 
```

It seems that the `PARTITION BY` clause in conjunction with `SELECT` on particular fields doesn't pick the right fields.

### PR DESCRIPTION
**Pull request by apurvam**
Fixes #799 

I have been able to reproduce the bug with the query validation test as well as the integration test. Both are included here, though we probably should remove the integration test before merge.

The problem is that when you select specific fields with a partition by, the new key clobbers the second field of the output. The reason is that the schema passed to the `KStream` object in `KsqlStructuredDataOutputNode` has the `ROWKEY`, and `ROWTIME` fields removed. However, inside the `KStream.selectKey` method that's executed due to the `PARTITION BY` clause, we write the new key at column 1 of the value (where the `ROWKEY` would be), hence clobbering it.  

We should not overwrite the key field since it doesn't always exist in the schema. 

I am still trying to figure out why the `SELECT *` statement with a `PARTITION BY` clause never had a problem, and why it continues to work with my patch (there are tests which prove that `SELECT *` still works).

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java [hunk 1]
```diff
@@ -248,7 +248,9 @@ public SchemaKStream selectKey(final Field newKeyField) {
               .toString();
       return newKey;
     }).mapValues((key, row) -> {
-      row.getColumns().set(SchemaUtil.ROWKEY_NAME_INDEX, key);
+      if (updateRowKey) {
```
Comment (dguy) [inline ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: we can probably just change this to use `map` instead of `selectKey(..).mapValues()`, i.e,
```
map((key, value) -> {
   // key selection code from above
  // updateRowKey from here
 return KeyValue.pair(newKey, value)
}
```

File: ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java [hunk 2]
```diff
@@ -116,6 +116,48 @@ public void testKSQLFromEndToEnd() throws Exception {
...
+                                                 + "viewtime, pageid, userid from "
+                                                 + "pageviews_original "
+                                                 + "partition by "
+                                                 + "viewtime;");
+
+    List<QueryMetadata> queries = ksqlEngine.buildMultipleQueries(createStreamStatement,
+                                                                  Collections.emptyMap());
+
+    assertEquals(1, queries.size());
+    assertTrue(queries.get(0) instanceof PersistentQueryMetadata);
```
Comment (dguy) [inline ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java]: `assertThat(queries.get(0), instanceOf(PersistentQueryMetadata.class)`

File: ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java [hunk 3]
```diff
@@ -116,6 +116,48 @@ public void testKSQLFromEndToEnd() throws Exception {
...
+
+    PersistentQueryMetadata persistentQueryMetadata = (PersistentQueryMetadata) queries.get(0);
+    persistentQueryMetadata.getKafkaStreams().start();
+
+    String query = String.format("SELECT * from pageviews_by_viewtime;");
+
+    queries = ksqlEngine.buildMultipleQueries(query, Collections.emptyMap());
+
+    assertEquals(1, queries.size());
+    assertTrue(queries.get(0) instanceof QueuedQueryMetadata);
```
Comment (dguy) [inline ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java]: ditto

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java (hunk 1 above)
Comment (apurvam) [reply ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: done.

Comment (apurvam) [reply ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: I had to back this suggestion out since it was causing the `JoinNodeTest` to fail with an NPE for some reason.
