### PR TITLE
fix: Ignore schema id while generating materialized serdes #9516

### LINKED ISSUE #9516: Foreign key joins dont work when schema id is specified in source schemas
**Describe the bug**
Foreign key joins fail when schema id is specified in the CREATE TABLE statements

**To Reproduce**
QTT
```
    {
      "name": "table-table foreign key join with protobuf schema and schema id",
      "statements": [
        "CREATE TABLE left_table WITH (kafka_topic='left_topic', partitions=128, format='PROTOBUF', KEY_SCHEMA_ID=101, KEY_SCHEMA_FULL_NAME='ProtobufLeftKey2', VALUE_SCHEMA_ID=102, VALUE_SCHEMA_FULL_NAME='ProtobufLeftValue2');",
        "CREATE TABLE right_table WITH (kafka_topic='right_topic', partitions=128, format='PROTOBUF', KEY_SCHEMA_ID=201, KEY_SCHEMA_FULL_NAME='ProtobufRightKey2', VALUE_SCHEMA_ID=202, VALUE_SCHEMA_FULL_NAME='ProtobufRightValue2');",
        "CREATE TABLE output AS SELECT L.K, L.NAME, L.FOREIGN_KEY, R.F1 FROM left_table L JOIN right_table R ON L.FOREIGN_KEY = R.K;"
      ],
      "topics": [
        {
          "name": "left_topic",
          "keyFormat": "PROTOBUF",
          "keySchemaId": 101,
          "keySchema": "syntax = \"proto3\"; message ProtobufLeftKey1 {uint32 k1 = 1;} message ProtobufLeftKey2 {int32 K = 1;}",
          "valueFormat": "PROTOBUF",
          "valueSchemaId": 102,
          "valueSchema": "syntax = \"proto3\"; message ProtobufLeftValue1 {float c1 = 1; uint32 c2 = 2;} message ProtobufLeftValue2 {string NAME = 1; int32 FOREIGN_KEY = 2;}"
        },
        {
          "name": "right_topic",
          "keyFormat": "PROTOBUF",
          "keySchemaId": 201,
          "keySchema": "syntax = \"proto3\"; message ProtobufRightKey1 {uint32 k1 = 1;} message ProtobufRightKey2 {int32 K = 1;}",
          "valueFormat": "PROTOBUF",
          "valueSchemaId": 202,
          "valueSchema": "syntax = \"proto3\"; message ProtobufRightValue1 {float c1 = 1; uint32 c2 = 2;} message ProtobufRightValue2 {uint64 F1 = 1;}"
        }
      ],
      "inputs": [
        {"topic": "right_topic", "key": {"K": 0}, "value": {"F1": 0}, "timestamp": 10000},
        {"topic": "right_topic", "key": {"K": 1}, "value": {"F1": 1}, "timestamp": 10000},
        {"topic": "right_topic", "key": {"K": 2}, "value": {"F1": 2}, "timestamp": 10000},
        {"topic": "left_topic", "key": {"K": 0}, "value": {"NAME": "zero", "FOREIGN_KEY": 0}, "timestamp": 11000},
        {"topic": "left_topic", "key": {"K": 1}, "value": {"NAME": "bar", "FOREIGN_KEY": 1}, "timestamp": 11000},
        {"topic": "left_topic", "key": {"K": 2}, "value": {"NAME": "foo", "FOREIGN_KEY": 2}, "timestamp": 11000}
      ],
      "outputs": [
        {"topic": "OUTPUT", "key": {"L_K": 0}, "value": {"FOREIGN_KEY": 0, "NAME": "zero", "F1": 0}, "timestamp": 11000},
        {"topic": "OUTPUT", "key": {"L_K": 1}, "value": {"FOREIGN_KEY": 1, "NAME": "bar", "F1": 1}, "timestamp": 11000},
        {"topic": "OUTPUT", "key": {"L_K": 2}, "value": {"FOREIGN_KEY": 2, "NAME": "foo", "F1": 2}, "timestamp": 11000}
      ]
    }
```

**Expected behavior**
Foreign key joins should work with or without schema ids in the CREATE statements

**Actual behaviour**
```
Caused by: io.confluent.ksql.serde.KsqlSerializationException: Error serializing message to topic: _confluent-ksql-some.ksql.service.idquery_CTAS_OUTPUT_0-KafkaTopic_Right-Reduce-changelog. Schema from Schema Registry misses field with name: ROWPARTITION
	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:56)
	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:188)
	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:151)
	at io.confluent.ksql.serde.GenericSerializer.serialize(GenericSerializer.java:62)
	at io.confluent.ksql.logging.processing.LoggingSerializer.serialize(LoggingSerializer.java:47)
	at io.confluent.ksql.serde.tracked.TrackedSerializer.serialize(TrackedSerializer.java:47)
	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:83)
	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:74)
	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:31)
	at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:195)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.lambda$put$6(MeteredKeyValueStore.java:330)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.put(MeteredKeyValueStore.java:330)
	at org.apache.kafka.streams.processor.internals.AbstractReadWriteDecorator$KeyValueStoreReadWriteDecorator.put(AbstractReadWriteDecorator.java:127)
	at org.apache.kafka.streams.kstream.internals.KTableTransformValues$KTableTransformValuesProcessor.process(KTableTransformValues.java:124)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.kstream.internals.KTableSource$KTableSourceProcessor.process(KTableSource.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:791)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)
	at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:791)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:722)
	... 44 more
Caused by: io.confluent.ksql.util.KsqlException: Schema from Schema Registry misses field with name: ROWPARTITION
	at io.confluent.ksql.serde.connect.ConnectSRSchemaDataTranslator.validate(ConnectSRSchemaDataTranslator.java:48)
	at io.confluent.ksql.serde.protobuf.ProtobufSRSchemaDataTranslator.convertStruct(ProtobufSRSchemaDataTranslator.java:44)
	at io.confluent.ksql.serde.protobuf.ProtobufSRSchemaDataTranslator.toConnectRow(ProtobufSRSchemaDataTranslator.java:37)
	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:52)
	... 73 more
```

**Additional context**
Related issue - https://github.com/confluentinc/ksql/issues/9163

### PR DESCRIPTION
**Pull request by bvarghese1**
### Description 
Fixes #9516 

- Remove schema id from keyFormatInfo and valueFormatInfo while creating
  materialized schema which is applied to changelog topics
- This fixes the issue related to fk-joins with schema id

### Testing done 
- Added QTTs in fk-join.json for PROTOBUF, AVRO, and JSON_SR schemas with schema ids
- Updated historical plans
- Manually tested on CP

### CODE REVIEW

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java [hunk 1]
```diff
@@ -83,14 +84,20 @@ static LogicalSchema buildSchema(
...
+
   static Serde<GenericRow> getValueSerde(
       final RuntimeBuildContext buildContext,
       final SourceStep<?> streamSource,
       final PhysicalSchema physicalSchema,
       final QueryContext queryContext
   ) {
     return buildContext.buildValueSerde(
-        streamSource.getFormats().getValueFormat(),
+        getFormatInfo(streamSource.getFormats().getValueFormat(), queryContext),
```
Comment (vcrfxia) [inline ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java:100]: Hey @bvarghese1 I'm confused about this change. This `getValueSerde()` helper method is being used everywhere in SourceBuilder, including where we specify the serdes to be used to deserialize from the source topic. If we strip SCHEMA_ID from there, doesn't that mean the deserializing isn't taking SCHEMA_ID into consideration any more?

Either my understanding is wrong, or this change breaks the SCHEMA_ID feature, or something else is going on that I'm missing. If you could help reconcile my confusion, that'd be much appreciated.

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java [hunk 2]
```diff
@@ -83,14 +84,20 @@ static LogicalSchema buildSchema(
         .withPseudoAndKeyColsInValue(windowed, source.getPseudoColumnVersion());
   }
 
+  static FormatInfo getFormatInfo(final FormatInfo formatInfo, final QueryContext queryContext) {
```
Comment (vcrfxia) [inline ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java:87]: Any reason this can't be private?

**Review by vcrfxia — COMMENTED** [review]
Hey @bvarghese1 , thanks for the changes -- left a question inline. I didn't take a detailed look at the new QTT coverage yet but I did notice that there's no unit test coverage. If it's not too much trouble to add, it'd be good to have unit test coverage in addition to the QTT.

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java (hunk 1 above)
Comment (bvarghese1) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java:100]: The SCHEMA_ID is removed only if the QueryContext contains MATERIALIZED. Eg: if the the QueryContext contains "Left/Source" the SCHEMA_ID is not removed because we want to honor the user specified SCHEMA_ID.

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java (hunk 2 above)
Comment (bvarghese1) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java:87]: Oh my bad.. Will make the change.

File: ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java (hunk 1 above)
Comment (vcrfxia) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java:100]: I see... I don't think we should overload this method like this, for a number of reasons. For one, I would not expect this method to modify formats from the method name, so it makes reading the code much less intuitive. It's also not guaranteed that the only time we will need to remove SCHEMA_ID (from SourceBuilder) is when materializing. That happens to be true today, but it's very easy for someone to modify SourceBuilder and blindly call this method without realizing that it needs to be modified. 

Instead of conditionally removing SCHEMA_ID from this method (which is called everywhere from SourceBuilder), can you just remove it (and call it explicitly) from the method which builds serdes for the materialized instance instead?

Comment (bvarghese1) [reply ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java:100]: Good point.

**Review by vcrfxia — COMMENTED** [review]
Thanks @bvarghese1 -- LGTM pending unit test coverage, as long as that's not too difficult to add. This fix is interesting because it's actually nothing to do with FK joins -- the fix suggests that any table with VALUE_SCHEMA_ID specified that gets materialized at the source is broken. If my understanding is correct, this PR of yours is fixing more than just FK joins. I think the following should also broken before your PR (Can you run a quick test to check, and add the relevant test coverage? Feel free to add test coverage in a separate PR if that's easier.):
* Create TABLE with VALUE_SCHEMA_ID specified.
* Create a new table with `CREATE TABLE ... AS SELECT * FROM ...;`
* Issue a pull query against the new table.
I expect either step 2 or 3 to fail (before the changes in your PR) because the table cannot be materialized, due to the same schema mismatch which is failing FK joins.

The fact that in your PR you only had to generate new QTT historic plans for FK joins (and no other existing QTTs) makes me think that we don't have QTT coverage for the case I mentioned above (even without the pull query). This makes me think that test coverage for SCHEMA_ID is lacking in general... it'd be good to get this added but it doesn't have to be in this PR.

**Comment by bvarghese1** [comment]
> Thanks @bvarghese1 -- LGTM pending unit test coverage, as long as that's not too difficult to add. This fix is interesting because it's actually nothing to do with FK joins -- the fix suggests that any table with VALUE_SCHEMA_ID specified that gets materialized at the source is broken. If my understanding is correct, this PR of yours is fixing more than just FK joins. I think the following should also broken before your PR (Can you run a quick test to check, and add the relevant test coverage? Feel free to add test coverage in a separate PR if that's easier.):
> 
> * Create TABLE with VALUE_SCHEMA_ID specified.
> * Create a new table with `CREATE TABLE ... AS SELECT * FROM ...;`
> * Issue a pull query against the new table.
>   I expect either step 2 or 3 to fail (before the changes in your PR) because the table cannot be materialized, due to the same schema mismatch which is failing FK joins.
> 
> The fact that in your PR you only had to generate new QTT historic plans for FK joins (and no other existing QTTs) makes me think that we don't have QTT coverage for the case I mentioned above (even without the pull query). This makes me think that test coverage for SCHEMA_ID is lacking in general... it'd be good to get this added but it doesn't have to be in this PR.

**Comment by bvarghese1** [comment]
> Thanks @bvarghese1 -- LGTM pending unit test coverage, as long as that's not too difficult to add. This fix is interesting because it's actually nothing to do with FK joins -- the fix suggests that any table with VALUE_SCHEMA_ID specified that gets materialized at the source is broken. If my understanding is correct, this PR of yours is fixing more than just FK joins. I think the following should also broken before your PR (Can you run a quick test to check, and add the relevant test coverage? Feel free to add test coverage in a separate PR if that's easier.):
> 
> * Create TABLE with VALUE_SCHEMA_ID specified.
> * Create a new table with `CREATE TABLE ... AS SELECT * FROM ...;`
> * Issue a pull query against the new table.
>   I expect either step 2 or 3 to fail (before the changes in your PR) because the table cannot be materialized, due to the same schema mismatch which is failing FK joins.
> 
> The fact that in your PR you only had to generate new QTT historic plans for FK joins (and no other existing QTTs) makes me think that we don't have QTT coverage for the case I mentioned above (even without the pull query). This makes me think that test coverage for SCHEMA_ID is lacking in general... it'd be good to get this added but it doesn't have to be in this PR.

Without the fix, I get the same error for CTAS
QTT:
```
  {
    "name": "update with PROTOBUF schema and schema id",
    "statements": [
      "CREATE TABLE TEST WITH (kafka_topic='test_topic', format='PROTOBUF', KEY_SCHEMA_ID=101, KEY_SCHEMA_FULL_NAME='ProtobufKey2', VALUE_SCHEMA_ID=102, VALUE_SCHEMA_FULL_NAME='ProtobufValue2');",
      "CREATE TABLE T1 as SELECT K, NAME, VALUE FROM test;"
    ],
    "topics": [
      {
        "name": "test_topic",
        "keyFormat": "PROTOBUF",
        "keySchemaId": 101,
        "keySchema": "syntax = \"proto3\"; message ProtobufKey1 {uint32 k1 = 1;} message ProtobufKey2 {string K = 1;}",
        "valueFormat": "PROTOBUF",
        "valueSchemaId": 102,
        "valueSchema": "syntax = \"proto3\"; message ProtobufValue1 {float c1 = 1; uint32 c2 = 2;} message ProtobufValue2 {uint64 ID = 1; string NAME = 2; uint32 VALUE = 3;}"
      }
    ],
    "inputs": [
      {"topic": "test_topic", "key": {"K":"1"}, "value": {"ID":1, "NAME":"one", "VALUE": 100}, "timestamp":  10},
      {"topic": "test_topic", "key": {"K":"1"}, "value": {"ID":2, "NAME":"two", "VALUE": 200}, "timestamp":  20},
      {"topic": "test_topic", "key": {"K":"1"}, "value": {"ID":3, "NAME":"three", "VALUE": 300}, "timestamp":  30}
    ],
    "outputs": [
      {"topic": "T1", "key": {"K":"1"}, "value": {"NAME":"one", "VALUE":100}},
      {"topic": "T1", "key": {"K":"1"}, "value": {"NAME":"two", "VALUE":200}},
      {"topic": "T1", "key": {"K":"1"}, "value": {"NAME":"three", "VALUE":300}}
    ]
  }
```

Exception:
```
java.lang.AssertionError: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000001, topic=test_topic, partition=0, offset=0, stacktrace=io.confluent.ksql.serde.KsqlSerializationException: Error serializing message to topic: _confluent-ksql-some.ksql.service.idquery_CTAS_T1_0-KsqlTopic-Reduce-changelog. Schema from Schema Registry misses field with name: ROWPARTITION
	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:56)
	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:188)
	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:151)
	at io.confluent.ksql.serde.GenericSerializer.serialize(GenericSerializer.java:62)
	at io.confluent.ksql.logging.processing.LoggingSerializer.serialize(LoggingSerializer.java:47)
	at io.confluent.ksql.serde.tracked.TrackedSerializer.serialize(TrackedSerializer.java:47)
	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:83)
	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:74)
	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:31)
	at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:195)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.lambda$put$6(MeteredKeyValueStore.java:330)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.put(MeteredKeyValueStore.java:330)
	at org.apache.kafka.streams.processor.internals.AbstractReadWriteDecorator$KeyValueStoreReadWriteDecorator.put(AbstractReadWriteDecorator.java:127)
	at org.apache.kafka.streams.kstream.internals.KTableTransformValues$KTableTransformValuesProcessor.process(KTableTransformValues.java:124)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.kstream.internals.KTableSource$KTableSourceProcessor.process(KTableSource.java:152)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:791)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)
	at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:791)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:722)
	at org.apache.kafka.streams.TopologyTestDriver.completeAllProcessableWork(TopologyTestDriver.java:600)
	at org.apache.kafka.streams.TopologyTestDriver.pipeRecord(TopologyTestDriver.java:557)
	at org.apache.kafka.streams.TopologyTestDriver.pipeRecord(TopologyTestDriver.java:846)
	at org.apache.kafka.streams.TestInputTopic.pipeInput(TestInputTopic.java:115)
	at io.confluent.ksql.test.tools.TestExecutor.processSingleRecord(TestExecutor.java:558)
	at io.confluent.ksql.test.tools.TestExecutor.pipeRecordsFromProvidedInput(TestExecutor.java:531)
	at io.confluent.ksql.test.tools.TestExecutor.buildAndExecuteQuery(TestExecutor.java:206)
	at io.confluent.ksql.test.EndToEndEngineTestUtil.shouldBuildAndExecuteQuery(EndToEndEngineTestUtil.java:42)
	at io.confluent.ksql.test.QueryTranslationTest.shouldBuildAndExecuteQueries(QueryTranslationTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

File: ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java [hunk 3]
```diff
@@ -464,6 +469,41 @@ public void shouldUseCorrectSerdeForUnwindowedKey() {
     );
   }
 
+  @Test
+  public void shouldNotContainSchemaIdInMaterializedSchema() {
+    when(keyFormatInfo.copyWithoutProperty("schemaId")).thenReturn(keyFormatInfoWithoutProps);
+    when(valueFormatInfo.copyWithoutProperty("schemaId")).thenReturn(valueFormatInfoWithoutProps);
```
Comment (vcrfxia) [inline ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java:475]: Can you move these two lines into the `setup()` method? This way the other tests which check for the regular `keyFormatInfo` or `valueFormatInfo` get coverage from the changes in this PR too (i.e., the other tests help verify that the changes in this PR are _only_ applied to materialization and not any of the source consumeds).

File: ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java [hunk 4]
```diff
@@ -464,6 +469,41 @@ public void shouldUseCorrectSerdeForUnwindowedKey() {
...
+
+    tableSource = new TableSource(
+        new ExecutionStepPropertiesV1(ctx),
+        TOPIC_NAME,
+        formats,
+        TIMESTAMP_COLUMN,
+        SOURCE_SCHEMA,
+        SystemColumns.ROWPARTITION_ROWOFFSET_PSEUDOCOLUMN_VERSION,
+        formats
+    );
```
Comment (vcrfxia) [inline ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java:488]: Replace this with `givenUnwindowedSourceTable()`. The helper methods are there to de-dup code and make the tests easier to read.

**Review by vcrfxia — APPROVED** [review]
LGTM with some minor refactor changes requested on the new unit test. Also, thanks for verifying that a regular CTAS with VALUE_SCHEMA_ID is indeed broken as well. If you do not have time to add increased test coverage for the SCHEMA_ID feature, let's definitely file a ticket and get it assigned. It concerns me that each time we fix a bug with this feature we uncover another one. I think we need to step back and review the test plan from when this feature was implemented more broadly.

File: ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java (hunk 3 above)
Comment (bvarghese1) [reply ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java:475]: Sure

File: ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java (hunk 4 above)
Comment (bvarghese1) [reply ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java:488]: Ah.. I was testing something and I created this. I forgot to undo this change. Thanks for catching this.

**Comment by bvarghese1** [comment]
> LGTM with some minor refactor changes requested on the new unit test. Also, thanks for verifying that a regular CTAS with VALUE_SCHEMA_ID is indeed broken as well. If you do not have time to add increased test coverage for the SCHEMA_ID feature, let's definitely file a ticket and get it assigned. It concerns me that each time we fix a bug with this feature we uncover another one. I think we need to step back and review the test plan from when this feature was implemented more broadly.

I have added QTT's for CTAS with schema ids.

**Comment by jchambondynadmic** [comment]
Do we known when this will included in a 7.3.x release or 7.4.0 ?

**Comment by vcrfxia** [comment]
> Do we known when this will included in a 7.3.x release or 7.4.0 ?

7.4.0

**Comment by jchambondynadmic** [comment]
Do we have an idea when it'll be released ?

**Comment by bvarghese1** [comment]
It should be available in the first quarter of 2023
