### PR TITLE
fix: Removes orphaned topics from transient queries

### LINKED ISSUE #4009: Restarting KSQL with active transient queries can leave orphaned internal topics
**Describe the bug**
It may be the case that restarting KSQL, while there are running push/transient query that uses internal changelog or repartition topics, results in the internal topics not being deleted

This has been removed on the community slack: 

https://confluentcommunity.slack.com/archives/C6UJNMY67/p1574980967041200

If this is the case, it's probably because we're not `close()`ing transient queries on shutdown, which would clean up these internal topics.  This would fix half the problem.

Of course, we may still have transient topics left around if a node _crashes_ or is killed while there are transient queries.  At the moment, a specific node would not be able to clean these up on restart as they could belong to another node.  We'd need to encode a node identify into the topic name to allow a restarted node to clean up orphaned topics.

### PR DESCRIPTION
**Pull request by AlanConfluent**
### Description 
Fixes #4009 

When a server is uncleanly shutdown or killed, it may leave orphaned topics from transient queries.  This PR attempts to clean up these topic when the server starts up.

This is accomplished by writing transient query application ids to disk of the local node.  This ensures that any topics are only attempted to be deleted by one node, the one that created it.  The data isn't durable in that a node can shutdown and not restart, potentially leaving state uncleaned up.

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by agavra** [comment]
There are some drawbacks with this approach:

- users have to carefully set the node.id for each of their nodes. this isn't always trivial in cloud environments (perhaps we could use k8s pod name - e.g. ksql-0?) when auto-scaling is enabled
- this approach makes nodes no longer interchangeable. if a customer scales down their cluster, a node.id would permanently disappear (leaving us open to having orphaned topics for that orphaned node.id)
- this opens the door to other features leveraging node.id, which is a double-edged sword (I've been arguing that we should have leader election and only have the leader write to the command topic, for example) because asymmetrical systems tend to be more difficult to operate, deploy and debug

I don't have any other alternatives off the top of my head, I'll give it some thought, but I think this merits further discussion. If we do decide to go down this path, might make sense to document this in a quick KLIP (I promise I'd review it promptly!).

**Comment by AlanConfluent** [comment]
> * users have to carefully set the node.id for each of their nodes. this isn't always trivial in cloud environments (perhaps we could use k8s pod name - e.g. ksql-0?) when auto-scaling is enabled

That's pretty much what I had in mind.  You effectively are delegating sticky id generation (and enforcing id uniqueness) to whatever configures ksql -- in a cloud environment, it could be Kubernetes.  In a more static environment, it would just be a one-time generated id.

> * this approach makes nodes no longer interchangeable. if a customer scales down their cluster, a node.id would permanently disappear (leaving us open to having orphaned topics for that orphaned node.id)

That's true.  Given that this was being used for GCing, imperfect cleanup was considered acceptable, but I agree this isn't ideal.  I was trying to keep this somewhat simple since it's about cleanup rather than an essential part of functionality.

> * this opens the door to other features leveraging node.id, which is a double-edged sword (I've been arguing that we should have leader election and only have the leader write to the command topic, for example) because asymmetrical systems tend to be more difficult to operate, deploy and debug

That's fair.  People might not fully understand the limitations of how I had intended for this to be used and could misuse it.
 
> I don't have any other alternatives off the top of my head, I'll give it some thought, but I think this merits further discussion. If we do decide to go down this path, might make sense to document this in a quick KLIP (I promise I'd review it promptly!). (EDIT: or at least get multiple eyes on this)

I agree, I think that's fair.  Most of the alternatives I thought of for issuing/registering ids are a fair bit more complex.  For example:
 - You could use a consensus mechanism to try to take claim to an id on startup, knowing that an id is only issued to a single node.
 - Similarly, you could elect a coordinator and have it issue ids
 - We could do something similar to the way the command topic currently works (if my understanding is correct) and start a transaction and then do a read followed by a write (ensuring exclusive access) to the topic, allowing a test and set mechanism to be created.  Then you can effectively find the next id and claim it by writing to the topic.

Of course, in order to clean things up, you have to decide that the owner of some id is dead or been restarted and a similar protocol must then exist for a coordinator marking that id as dead, waiting a bit, and then GCing the topic.  We already do heartbeating for pull queries and could utilize that.

I actually thought of using the advertised listener instead of this since it's effectively the same idea (a unique address for each node) and already something we support.  The only issue is that not every configuration people seem to set up allows for inter-node communication.  If we assumed that were the case, then the problem is solved.

**Comment by agavra** [comment]
> I agree, I think that's fair. Most of the alternatives I thought of for issuing/registering ids are a fair bit more complex.

Ideally, we'd have an alternative that doesn't involve ID generation at all. I think if we are going down that path, what you have here is the best for what we need. We can always make the ID generation more flexible (i.e. the suggestions you have) but we'll never be able to make it less - so it makes sense to start with static ID generation.

What do you think of a stupid-simple approach of just committing a list of transient queries to disk? That way we can track them and on start-up we can just delete all the ones that we were handling. It still has the potential to leak if a node goes down and never comes up, but that was a problem in either approach.

**Comment by rodesai** [comment]
I agree that going the route of adding a per-node ID should have a KLIP. Adding this would be useful for more than just this type of garbage collection, but at the same time requires some care from an operator and has potential compatibility concerns. We should define:
    - how can the id be used. I think it's important to think ahead about what having an ID could buy us, because it will help us better think through any constraints it needs to have, and assess whether it's worth the compatibility issues raised below. Currently the proposal is to use it for resource tracking and garbage collection. But we could also use the id for:
        - static group membership in streams 
        - does it help our HA story to have predictable ids?
        - it could also be useful to store some metadata about each node, for example what it's last executed command is, so we can perform first-time-only initialization tasks for a query.
    - what are the requirements when setting these IDs
    - compatibility - what happens if the id is not specified? It would be simplest to just require it, but I think that's actually a pretty big requirement to add. But if we support not specifying the ID we need 2 behaviours every time the id is used.

That said, if we do have to set an ID it's trivial to set a unique predictable ID in CCloud, so that's not a concern, at least for us.

I do like the idea of keeping a registry of running queries on the local disk. It's expected that ksqlDB should have access to stable storage to function optimally, so we're not adding a new requirement here.

**Comment by AlanConfluent** [comment]
> I agree that going the route of adding a per-node ID should have a KLIP. Adding this would be useful for more than just this type of garbage collection, but at the same time requires some care from an operator and has potential compatibility concerns. 

I agree that defining such a thing would require answering a lot of the questions you stated above.  I think that it's probably out of the scope of this GC case to try and tackle, since GC is much simpler potentially.


> I do like the idea of keeping a registry of running queries on the local disk as an alternative to the above. It's expected that ksqlDB should have access to stable storage to function optimally, so we're not adding a new requirement here.

I considered this and I think it's a reasonable approach. There's one drawback to only using local disk and that's if the same logical node gets restarted on a new machine, then cleanup isn't possible since there will be nothing saved to local disk.  Not sure how often that happens in various cloud environments, but it's certainly possible.  That said, if we're aiming to take care of the common case and this covers it, then that's fine by me.

**Comment by agavra** [comment]
> That said, if we're aiming to take care of the common case and this covers it, then that's fine by me.

+1 I think that's what we should be aiming for - like you said earlier, it's mostly to GC things so if we miss it a few times in exceptional cases that's alright, the user can always cleanup these topics on their own (and there were exceptional cases in both proposals). It also makes life easier by avoiding thinking about the hard(er) problems 😅

**Comment by AlanConfluent** [comment]
I've attempted to address your comments @rodesai @agavra and now write the query ids to disk.  Pleas take another look.

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommands.java [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+    return currentLocalCommands.getFile();
+  }
+
+  public void processLocalCommandFiles(
+      final ServiceContext serviceContext
+  ) {
+    final FilenameFilter filter = (dir, fileName) -> fileName.endsWith(LOCAL_COMMANDS_FILE_SUFFIX);
+    final File[] files = directory.listFiles(filter);
+    if (files == null) {
+      throw new KsqlServerException("Bad directory " + directory.getAbsolutePath());
```
Comment (agavra) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommands.java:76]:
```suggestion
      throw new KsqlServerException("Bad local commands directory " + directory.getAbsolutePath() + ". Please check your configuration for " + KsqlConfig.KSQL_LOCAL_COMMANDS_LOCATION_CONFIG);
```

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommands.java [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+  }
+
+  public void write(final TransientQueryMetadata queryMetadata) {
+    try {
+      currentLocalCommands.write(
+          new LocalCommand(Type.TRANSIENT_QUERY, queryMetadata.getQueryApplicationId()));
+    } catch (IOException e) {
+      // Just log an error since not catching it would likely cause more cleanup work than this
+      // aims to fix.
+      LOG.error("Failed to write local command", e);
```
Comment (agavra) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommands.java:101]:
```suggestion
      LOG.error("Failed to write local command for transient query:" + queryMetadata.getQueryApplicationId(), e);
```

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommands.java [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+          + "' config in the properties file."
+      );
+    }
+    final File file = new File(directory, String.format("local_commands_%d_%s%s",
+        System.currentTimeMillis(), Integer.toHexString(RANDOM.nextInt()),
+        LOCAL_COMMANDS_FILE_SUFFIX));
+    return new LocalCommands(directory, ksqlEngine, LocalCommandsFile.createWriteable(file));
+  }
+
+  private void markFileAsProcessed(final File file) {
```
Comment (agavra) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommands.java:158]: why not just delete the file? Do we every use these?

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommandsFile.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+  public static LocalCommandsFile createWriteable(final File file) {
+    return new LocalCommandsFile(file, true);
+  }
+
+  public void write(final LocalCommand localCommand) throws IOException {
+    if (writer == null) {
+      throw new IOException("Write permission denied.");
+    }
+
+    final byte[] bytes = MAPPER.writeValueAsBytes(localCommand);
```
Comment (agavra) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommandsFile.java:67]: just making sure, this writes it in UTF8 so it's human readable json, right? I think it would be nice to make these files human readble

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+      return;
+    }
+    // Find any transient query topics
+    final Set<String> orphanedQueryApplicationIds = topicNames.stream()
+        .map(topicName -> queryApplicationIds.stream().filter(topicName::startsWith).findFirst())
+        .filter(Optional::isPresent)
+        .map(Optional::get)
+        .collect(Collectors.toSet());
+    for (final String queryApplicationId : orphanedQueryApplicationIds) {
+      cleanupService.addCleanupTask(
```
Comment (agavra) [inline ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java:58]: since the file is only relevant on a new startup, does it need to be added to the cleanup service or can we just have it do this cleanup on startup?

**Review by agavra — COMMENTED** [review]
overall lgtm, some inline comments

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+    final Set<String> topicNames;
+    try {
+      topicNames = topicClient.listTopicNames();
+    } catch (KafkaResponseGetFailedException e) {
+      LOG.error("Couldn't fetch topic names", e);
+      return;
+    }
+    // Find any transient query topics
+    final Set<String> orphanedQueryApplicationIds = topicNames.stream()
+        .map(topicName -> queryApplicationIds.stream().filter(topicName::startsWith).findFirst())
```
[the remark this answers is not in the document]
Comment (AlanConfluent) [reply ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java:53]: So far as I can tell, nothing is very different in the cloud beyond setting some configs differently for making the query application id.  After all, so far as I can tell it's streams that is creating these topics and they just append to the query application id. 

I verified this manually with the transient topic names, so I'm pretty confident startsWith should work.

[the remark this answers is not in the document]
Comment (agavra) [reply ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java:53]: ack

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+  }
+
+  public void cleanupOrphanedInternalTopics(
+      final ServiceContext serviceContext,
+      final Set<String> queryApplicationIds
+  ) {
+    final KafkaTopicClient topicClient = serviceContext.getTopicClient();
+    final Set<String> topicNames;
+    try {
+      topicNames = topicClient.listTopicNames();
```
[the remark this answers is not in the document]
Comment (AlanConfluent) [reply ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java:46]: In theory, it should process just one set of commands at a time during startup (it shouldn't be possible for there to be more than one unprocessed file).  When it does that, it should call this just once.  So it does this list call on node startup and uses that list of topics to compare with all of the application query ids in the commands file.  It would seem to be more expensive to say for every queryApplicationId, check the existence of a given topic.  Not only is that more rpcs, it also might check plenty of completed transient queries the cleaned up with no issue.  I considered adding a "done cleaning" entry to the commands so I could find the set of only orphaned queries, but that seems potentially error prone as well and requires writing another entry.  This seemed a little simpler.

Tell me if you'd prefer the "done cleaning" approach.

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+    } catch (KafkaResponseGetFailedException e) {
+      LOG.error("Couldn't fetch topic names", e);
+      return;
+    }
+    // Find any transient query topics
+    final Set<String> orphanedQueryApplicationIds = topicNames.stream()
```
[the remark this answers is not in the document]
Comment (AlanConfluent) [reply ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java:52]: Yeah, I think we're on the same page now.  This is only ever run on startup and so by definition, the query application ids, if found as topic prefixes, would be orphaned.  Of course, that list is all transient queries run, not technically just the orphaned ones.

I'll improve the documentation.

File: ksqldb-engine/src/test/java/io/confluent/ksql/engine/OrphanedTransientQueryCleanerTest.java [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+
+  @Before
+  public void setUp() {
+    when(serviceContext.getTopicClient()).thenReturn(topicClient);
+    cleaner = new OrphanedTransientQueryCleaner(queryCleanupService);
+  }
+
+  @Test
+  public void shouldCleanup_allApplicationIds() {
+    when(topicClient.listTopicNames()).thenReturn(ImmutableSet.of(TOPIC1, TOPIC2, TOPIC3));
```
[the remark this answers is not in the document]
Comment (AlanConfluent) [reply ksqldb-engine/src/test/java/io/confluent/ksql/engine/OrphanedTransientQueryCleanerTest.java:78]: Done

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (agavra) [reply ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java:46]: Yeah I agree the existing PR approach is better. At first, I didn't realize it happens just once on startup but since that's the case this is easier and less error-prone.

**Review by agavra — APPROVED** [review]
hitting the big green button

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommandsFile.java (hunk 4 above)
Comment (AlanConfluent) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommandsFile.java:67]: Yep, it's UTF8: https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html#writeValueAsBytes(java.lang.Object)

File: ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java (hunk 5 above)
Comment (AlanConfluent) [reply ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java:58]: We chatted about this offline.  This takes advantage of the other cleanup routines done by `QueryCleanupService`, so needs access to it.  It does this cleanup once on startup
