### PR TITLE
Filter out nulls before group by and select key operations to avoid NPE

### LINKED ISSUE #521: NullPointerException during count aggregation
```
Caused by: java.lang.NullPointerException
at io.confluent.ksql.planner.plan.AggregateNode.lambda$aggregateReKey$1(AggregateNode.java:272)
at org.apache.kafka.streams.kstream.internals.KStreamImpl$2.apply(KStreamImpl.java:157)
at org.apache.kafka.streams.kstream.internals.KStreamImpl$2.apply(KStreamImpl.java:154)
at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:41)
at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
at
```

### PR DESCRIPTION
**Pull request by dguy**
Fixes #521

### CODE REVIEW

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java [hunk 1]
```diff
@@ -240,7 +240,7 @@ public SchemaKStream selectKey(final Field newKeyField, boolean updateRowKey) {
     }
 
 
-    KStream keyedKStream = kstream.selectKey((key, value) -> {
+    KStream keyedKStream = kstream.filter((key, value) -> value != null).selectKey((key, value) -> {
```
Comment (rodesai) [inline ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: While we're at it should we fix the NPE that I think would get thrown on line 248 if the value in the key column is null?

Comment (apurvam) [reply ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: Good catch @rodesai , I agree that it would be nice to fix it as part of this patch.

Comment (dguy) [reply ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: sure. will do

**Comment by dguy** [comment]
@hjafarpour the `null` is returned from the Deserializers. The issue is that `null` is a valid value, i.e., for a compacted topic it signifies a delete for the key. So I think we should stick with filtering them for now and put some more thought into how we handle this post GA

File: ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java [hunk 2]
```diff
@@ -133,7 +133,7 @@ public SchemaKStream select(final Schema selectSchema) {
           List<Object> newColumns = new ArrayList<>();
           for (Field schemaField : selectSchema.fields()) {
             newColumns.add(
-                row.getColumns().get(SchemaUtil.getFieldIndexByName(schema, schemaField.name()))
+                extractColumn(schemaField, row)
```
Comment (big-andy-coates) [inline ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java]: nit: all on a single line?
