### PR TITLE
Fix flakey CliTest and issue with LIMIT clause not being honoured.

### LINKED ISSUE #656: LIMIT clause is not honoured accurately
Using `LIMIT 5` I get one row, four rows, five rows when I run the same query three times. I'd expect five rows, each time. 

```
ksql> select * from parsed_logs_ts_a where response = 404 limit 5;
1516786508000 | null | 1516786508000 | /wp-login.php/ | "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1" | 404
LIMIT reached for the partition.
Query terminated
ksql>
ksql> select * from parsed_logs_ts_a where response = 404 limit 5;
1516822859000 | null | 1516822859000 | /apple-touch-icon.png/ | "MobileSafari/604.1 CFNetwork/894 Darwin/17.4.0" | 404
1516830777000 | null | 1516830777000 | /wp-login.php/ | "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1" | 404
1516801415000 | null | 1516801415000 | /atom.xml/ | "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36" | 404
1516801416000 | null | 1516801416000 | /rss.xml/ | "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36" | 404
LIMIT reached for the partition.
Query terminated
ksql> select * from parsed_logs_ts_a where response = 404 limit 5;
1516780518000 | null | 1516780518000 | /spa112.cfg/ | "PolycomVVX-VVX_500-UA/5.2.2.1522" | 404
1516801416000 | null | 1516801416000 | /index.php/?format=feed&type=rss | "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36" | 404
1516809252000 | null | 1516809252000 | /wp-login.php/ | "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1" | 404
1516777623000 | null | 1516777623000 | /2016/07/19/kafka-connect-hdfs-with-hive-integration-schemaprojectorexception-schema-version-required/docs.confluent.io/3.0.0/connect/connect-hdfs/docs/hdfs_connector.html/ | "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" | 404
1516778285000 | null | 1516778285000 | /2016/05/12/monitoring-logstash-ingest-rates-with-influxdb-and-grafana/&wd=&eqid=d6295480000248ba000000045a64c376 | "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0" | 404
LIMIT reached for the partition.
Query terminated
```

### PR DESCRIPTION
**Pull request by big-andy-coates**
Fix race condition when limit statements are used. The exception thrown when limit is reached causes the QueryStreamWriter to exit its loop, even if more rows available on the queue.

Causes: Test Failed: CliTest.testSelectLimit
Causes #656: LIMIT clause is not honoured accurately

Fixed so that any pending rows are drained before handling the exception.

Fixes #656

### CODE REVIEW

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java [hunk 1]
```diff
@@ -124,6 +125,21 @@ private void write(OutputStream output, GenericRow row) throws IOException {
...
+  private void drainAndThrowOnError(final OutputStream out) throws Throwable {
+    if (streamsException == null) {
+      return;
+    }
+
+    final List<KeyValue<String, GenericRow>> rows = Lists.newArrayList();
+    queryMetadata.getRowQueue().drainTo(rows);
+
+    for (final KeyValue<String, GenericRow> row : rows) {
+      write(out, row.value);
```
Comment (rodesai) [inline ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java]: We might get a null GenericRow here. We should check for that and skip those rows in the output.

**Comment by apurvam** [comment]
Since this just

**Comment by big-andy-coates** [comment]
Thanks for the reviews all. Amusingly, the build for this failed... due to another flakey test - doh!  Another fix raised: #1177

File: ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java (hunk 1 above)
Comment (rodesai) [reply ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java]: Ah I see now. I was worried about the case where a query legitimately produces null output (e.g. a HAVING clause evaluates to false, or a basic projection has a null record in the source). But looks like those are filtered out by QueuedSchemaKStream. So we're all good here!
