### PR TITLE
fix: unify behavior for PARTITION BY and GROUP BY

### LINKED ISSUE #2701: Breaking Change: Inconsistency between GROUP BY and PARTITION BY's handling of aliases
There is currently an inconsistency between `GROUP BY`'s and `PARTITION BY`'s handling of aliases:
 - `PARTITION BY` requires the statement to use the name of the column as it is in the output schema, i.e. the alias, e.g.

```sql
SELECT field AS alias FROM whatever PARTITION BY alias;
```

- `GROUP BY` requires the statement to use the name of the column as it is in the source schema, e.g.

```sql
SELECT field AS alias FROM whatever GROUP BY field;
```

This is inconsistent and we should look to standardize on one.

### PR DESCRIPTION
**Pull request by agavra**
BREAKING CHANGE: this change makes it so that PARTITION BY statements
use the _source_ schema, not the value/projection schema, when selecting
the value to partition by. This is consistent with GROUP BY, and
standard SQL for GROUP by. Any statement that previously used PARTITION
BY may need to be reworked.

Fixes #2701 

### Description 
This change does two things: (1) it pulls `PARTITION BY` into the Query object so that it mimics the `GROUP BY` behavior and makes it clear that it is a function of the source data (not something post-projection) and (2) introduced a `RepartitionNode` in the Logical Plan that handles partitions before anything else, instead of using the projection schema.

A nice side effect is that the syntax is now `... PARTITION BY FOO EMIT CHANGES` instead of `... EMIT CHANGES PARTITION BY FOO`

### Testing done 

Updated existing test coverage to reflect the new behavior.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by hjafarpour** [comment]
@agavra it seems that the reason for this change is more because of implementation details than user experience! It's more intuitive to partition by one of the columns in the current schema rather than a field that may not exist in the result schema! Consider the following example:

```sql
CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
FROM bar 
PARTITION BY new_col1;
```
We know that the result schema is `new_col1, new_col2` and it is partitioned by the first column, `new_col1`.
But if you make the proposed change, the query would be the following:
```sql
CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
FROM bar 
PARTITION BY col1;
 ```
and the result would be partitioned based on a column that no longer exist!

**Comment by agavra** [comment]
@hjafarpour - originally, I thought the same thing, but this isn't motivated by implementation. Your argument would stand for `GROUP BY` as well yet databases don't have that (if I `SELECT COUNT(*) GROUP BY foo` it isn't necessary that `foo` appears in the result schema). It's not that the value doesn't exist anymore, it's just the `ROWKEY` column in ksqlDB. And I think it makes sense to follow the lead of other databases in this example.

Also, @big-andy-coates convinced me: `GROUP BY` defines what the key is set to, similarly `PARTITION BY` defines what the key is set to. A `GROUP BY` is implicitly also a `PARTITION BY` (because of the nature of setting the key). This means they should have behavior. Andy's https://github.com/confluentinc/ksql/issues/2701#issuecomment-558307871 here makes a lot of sense as a way of thinking about it.

**Comment by hjafarpour** [comment]
@agavra I'm still not convinced with making `PARTITION BY` behave like `GROUP BY`. These are different operations for different purposes. `GROUP BY` is used to indicate grouping on the data source to perform aggregation on. On the other hand, `PARTITION BY` is used to repartition the result of a query. 
In addition, now you remove the ability of repartitioning based on the result columns unless you add the support for complex expressions in the partition by clause. For instance, now we won't be able to have the following query:

 ```sql
CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
FROM bar 
PARTITION BY new_col1;
```
and it should be written as the following:
 ```sql
CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
FROM bar 
PARTITION BY col1*col2;
```
which we don't support it yet!

**Comment by big-andy-coates** [comment]
> A nice side effect is that the syntax is now ... PARTITION BY FOO EMIT CHANGES instead of ... EMIT CHANGES PARTITION BY FOO

@agavra work calling ^^^ out in the breaking change description?

**Comment by big-andy-coates** [comment]
> I'm still not convinced with making `PARTITION BY` behave like `GROUP BY`. These are different operations for different purposes

A `GROUP BY` is effectively a `PARTITION BY`, (selectKey in KS parlance?), followed by an aggregation.  They two should behave in a consistent manner.

> Consider the following example:

> ``` sql
> CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
> FROM bar 
> PARTITION BY new_col1;
> ```
> We know that the result schema is new_col1, new_col2 and it is partitioned by the first column, new_col1.

You're still thinking in terms of only the value columns being part of the schema. We've moving away from this with the work on primitive keys, (almost there) and structured keys.  With this work done the key columns are as much a part of the schema as the value columns.

If you take into account that the key columns are in a schema, then the example starts to look more like:

```sql
CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
FROM bar 
PARTITION BY col1*col2 AS Id;
```

And the resulting schema is something like the following, (make up types) `ID INT KEY, NEW_COL1 INT, NEW_COL2 INT`.

But actually, this is duplicating the key column in the value, which is a waste of space if the downstream system doesn't need it, so your initial query might be better re-written as:

```sql
CREATE STREAM foo AS SELECT col3*100 as new_col2 
FROM bar 
PARTITION BY col1*col2 AS new_col1;
```

with a result schema of `NEW_COL1 INT, NEW_COL2 INT`.

However, I agree we'll need expression support in the `PARTITION BY` -> @agavra, do we get that for free with your change promoting this to a proper logic node?   Or is this something we'll need to add?  If it's the former, we should add some QTT tests covering this.

File: ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java [hunk 1]
```diff
@@ -543,6 +542,16 @@ private void analyzeGroupBy(final GroupBy groupBy) {
       }
     }
 
+    private void analyzePartitionBy(final Expression partitionBy) {
+      if (partitionBy instanceof ColumnReferenceExp) {
```
Comment (big-andy-coates) [inline ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java]: [As discussed](https://github.com/confluentinc/ksql/pull/3982#issuecomment-559452186) this will need to handle expressions, though this could be a follow up PR.

File: ksql-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriter.java [hunk 2]
```diff
@@ -188,6 +188,10 @@ protected AstNode visitQuery(final Query node, final C context) {
       final Optional<GroupBy> groupBy = node.getGroupBy()
           .map(exp -> ((GroupBy) rewriter.apply(exp, context)));
 
+      // don't rewrite the partitionBy because we expect it to be
+      // exactly as it was (a single, un-aliased, column reference)
+      final Optional<Expression> partitionBy = node.getPartitionBy();
```
Comment (big-andy-coates) [inline ksql-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriter.java]: As above, may need to change...

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java [hunk 3]
```diff
@@ -291,10 +291,10 @@ public void shouldRekeyIfPartitionByDoesNotMatchResultKey() {
     assertThat(lines.length, equalTo(4));
     assertThat(lines[0], equalTo(" > [ SINK ] | Schema: [ROWKEY STRING KEY, COL0 BIGINT, COL1 STRING, COL2 "
         + "DOUBLE] | Logger: InsertQuery_1.S1"));
-    assertThat(lines[1],
-        equalTo("\t\t > [ REKEY ] | Schema: [ROWKEY STRING KEY, COL0 BIGINT, COL1 STRING, COL2 DOUBLE] "
-            + "| Logger: InsertQuery_1.S1"));
-    assertThat(lines[2], equalTo("\t\t\t\t > [ PROJECT ] | Schema: [ROWKEY STRING KEY, COL0 BIGINT, COL1 STRING"
+    assertThat(lines[2],
+        containsString("[ REKEY ] | Schema: [TEST1.ROWKEY STRING KEY, TEST1.ROWTIME BIGINT, TEST1.ROWKEY STRING, TEST1.COL0 BIGINT, TEST1.COL1 STRING, TEST1.COL2 DOUBLE] "
```
Comment (big-andy-coates) [inline ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: Why is the schema now prefixed?

File: ksql-functional-tests/src/test/resources/query-validation-tests/key-field.json [hunk 4]
```diff
@@ -90,30 +90,30 @@
         "CREATE STREAM INPUT (foo INT, bar INT) WITH (kafka_topic='input_topic', value_format='JSON');",
         "CREATE STREAM OUTPUT AS SELECT foo AS ALIASED, bar FROM INPUT PARTITION BY ALIASED;"
       ],
+      "expectedException": {
+        "type": "io.confluent.ksql.util.KsqlStatementException",
+        "message": "Invalid identifier for PARTITION BY clause: ALIASED"
```
Comment (big-andy-coates) [inline ksql-functional-tests/src/test/resources/query-validation-tests/key-field.json]: work adding... `Only columns from the source schema can be referenced in the PARTITION BY clause`?

File: ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4 [hunk 5]
```diff
@@ -78,6 +77,7 @@ query
       (WINDOW  windowExpression)?
       (WHERE where=booleanExpression)?
       (GROUP BY groupBy)?
+      (PARTITION BY partitionBy=identifier)?
```
Comment (big-andy-coates) [inline ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4]: much nicer!

**Comment by hjafarpour** [comment]
@big-andy-coates yes, you are right in describing my thinking. Key in the current model is more of a meta field than an equivalent part of the schema. I know with the structured key support this will change and this change in `partition by` behavior can be more justified as you explained. The question is when will we have structured key supported?
I know you are working on primitive key support. With KSQL rebranding to ksqlDB I think this is a good time to make major breaking changes such as structured key support. Do you have plans to add structured key support soon after primitive key?

File: ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java (hunk 3 above)
Comment (agavra) [reply ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java]: It just uses the source schema which is prefixed, for some reason, you can look at the rest of this test class to see this. As long as the sink schema is the same it should be fine I think.

Changing this is out of scope, though we should probably do it.

**Comment by agavra** [comment]
Thanks for the review @big-andy-coates!

> One thing to check through ... we should avoid the RepartitionNode if its PARTITION BY ROWKEY.

I don't think we should do that - even with this implementation, we don't repartition because of (your) optimization that's done inside the repartition node (`SchemaKStream#selectKey`). This way the logical plan still represents exactly what the user told us to do and we don't duplicate this checking logic in two places. Also with the changes around keys (and also supporting expressions in PARTITION BY) I think it's better to keep the logical plan simple.

File: ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java (hunk 1 above)
Comment (agavra) [reply ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java]: Yup, let's do this in a follow-up

Comment (agavra) [reply ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java]: https://github.com/confluentinc/ksql/issues/4018

Comment (big-andy-coates) [reply ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java]: I've added to ksqlDb v1.0 project as we don't want to release any new version of KSQL till this is done.

**Comment by big-andy-coates** [comment]
> One thing to check through ... we should avoid the RepartitionNode if its PARTITION BY ROWKEY.

I think the logical plan should _not_ have a repartition step if its `PARTITION BY ROWKEY`, because _logically_ that step is not needed.

If anything, the logic should only exist in the logical plan and the physical plan should throw if it gets through to it still with a repartition.

**Comment by vpapavas** [comment]
Hey @big-andy-coates , 

I am confused about this:
>If you take into account that the key columns are in a schema, then the example starts to look more like:
>```
>CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
>FROM bar 
>PARTITION BY col1*col2 AS Id; 
>```

Why does the fact that the key columns will be part of the schema play a role here and change the example query?

Also, I feel that we add more functionality to the `PARTITION BY` operator than we should. It should not control what columns will be in the output, much like `GROUP BY` doesn't. If you have a `GROUP BY col1` but don't include `col1` in the projection, then the column will not be in the output schema. The same should hold for the `PARTITION BY`. 

If we agree on this, why would the example query @hjafarpour  wrote 
```
CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
FROM bar 
PARTITION BY new_col1;
```
be written as 
```
CREATE STREAM foo AS SELECT col1*col2 AS new_col1, col3*100 as new_col2 
FROM bar 
PARTITION BY col1*col2 AS Id;
```

There should not be an `AS` term in the `PARTITION BY` clause, it should only be in the `SELECT` clause, no?

Finally, the rewriting of the query you suggest for avoiding the duplication of columns should be part of the optimizer. But if we don't allow the `PARTITION BY` to control the output schema (as in add extra columns) then this would would not be an issue.

**Comment by agavra** [comment]
Thanks for looking into this @vpapavas!

> Why does the fact that the key columns will be part of the schema play a role here and change the example query?

`PARTITION BY` is the mechanism that we've given for defining the `ROWKEY`. If `ROWKEY` becomes multiple columns in the future, we need a way to define those. `PARTITION BY` makes it explicit that these columns will cause a repartitioning. So it will be part of the output schema, even if we don't give it a name.

> It should not control what columns will be in the output, much like GROUP BY doesn't. If you have a GROUP BY col1 but don't include col1 in the projection, then the column will not be in the output schema. The same should hold for the PARTITION BY.

I don't think this is necessarily true; today, the result of the `GROUP BY` becomes the `ROWKEY` of the result schema (so it does define the output schema in the same way `PARTITION BY` does). With structured keys, it will be a set of key fields if you group by more than one column.

> There should not be an AS term in the PARTITION BY clause, it should only be in the SELECT clause, no?

Today there is an "implicit" `AS` - `AS ROWKEY`. You can't have `AS ROWKEY` in the `SELECT` clause (if I understand correctly).
