### PR TITLE
fix: default to get authHeader if using basic

### LINKED ISSUE #9814: Basic authentication does not work with HA multi-node cluster
**Describe the bug**
Pull queries and multi-node communication does not work or hangs when ksql is configured for HA (2 or more node) and Basic authentication used. 

This is the exception seen in one of the nodes when running `show queries` or a pull query from another node. I can authenticate with each node directly and run pull queries with keys available in that node. But if a run a pull query available in another node, then the internal node communication fails.
```
[ERROR] 2023-03-01 22:05:49,700 [vert.x-eventloop-thread-11] io.vertx.ext.web.RoutingContext ? - Unhandled exception in router
io.confluent.ksql.api.server.KsqlApiException: Unauthorized
	at io.confluent.ksql.api.server.AuthHandlers.selectHandler(AuthHandlers.java:143)
	at io.confluent.ksql.api.server.AuthHandlers.lambda$setupAuthHandlers$2(AuthHandlers.java:63)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.confluent.ksql.api.server.AuthHandlers.pauseHandler(AuthHandlers.java:202)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.confluent.ksql.api.server.LoggingHandler.handle(LoggingHandler.java:135)
	at io.confluent.ksql.api.server.LoggingHandler.handle(LoggingHandler.java:35)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:158)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
```

Both nodes are correctly configured with Basic authentication.
```
authentication.method=BASIC
authentication.realm=KsqlServer-Props
authentication.roles=admin,developer,user,ksql-user
authentication.skip.paths=/chc/live,/chc/ready
```

The root cause is on the line of this code https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java#L41
```
    String authToken = null;
    if (server.getAuthenticationPlugin().isPresent()) {
      authToken = server.getAuthenticationPlugin().get().getAuthHeader(routingContext);
    }
```

The above condition expects an `authentication.plugin.class` in order to get the `authHeader` of the user making the request to a node. Then that node uses this `authHeader` later for internal node communication. Because no plugin is used for BASIC authentication, then the header is NULL and causes the Unauthorized errors on the other nodes.

What should be fixed?

The `authHeader` should obtain the value from the `RoutingContext` directly as default in case there is no authentication plugin. In fact, the `AuthenticationPlugin` has a default method, but there is no implementation we can use in the KSQL config.
See https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPlugin.java#LL58C3-L60C4
```
  default String getAuthHeader(final RoutingContext routingContext) {
    return routingContext.request().getHeader("Authorization");
  }
```

The fix would look something like this:
```
# Get the authorization header by default
String authToken = routingContext.request().getHeader("Authorization");
if (server.getAuthenticationPlugin().isPresent()) {
  # If plugin exists, then get the header from it
  authToken = server.getAuthenticationPlugin().get().getAuthHeader(routingContext);
}
```

### PR DESCRIPTION
**Pull request by nateab**
### Description 
Fix #9814 

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._
### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

File: ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java [hunk 1]
```diff
@@ -38,7 +38,7 @@ public static DefaultApiSecurityContext create(final RoutingContext routingConte
     }
     final ApiUser apiUser = (ApiUser) user;
 
-    String authToken = null;
+    String authToken = routingContext.request().getHeader("Authorization");
```
Comment (AlanConfluent) [inline ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java:41]: Nice, I think this is equivalent to the default before these changes:
https://github.com/confluentinc/ksql/commit/b6fc8d91152db35c2f8067f4db44ed6cba1c172b#diff-70fac99e0a455f1109c7e0ac5728bbc341ed445234d51ebf741850267a1b7f89L38

Comment (AlanConfluent) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java:41]: It would be nice if we updated one of the multi-node tests to use basic auth to exercise this.  

We did exactly this in `PullQueryRoutingFunctionalTest` (though that also has an auth plugin installed I believe to use `authentication.skip.paths`, though this isn't a limitation anymore.  Though that test is disabled anyway now!

It would be good if we could basic auth to another IT that is multi node to try to ensure that we don't regress.  At the moment, I don't think there exists any such test.

Comment (nateab) [reply ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java:41]: Added basic auth to `ShowQueriesMultiNodeFunctionalTest` to ensure no regression

**Review by pgaref — APPROVED** [review]
