### PR TITLE
Fix avro optional fields

### LINKED ISSUE #8919: VALUE_SCHEMA_ID does not work with complex structure and optional fields
**Describe the bug**

New `VALUE_SCHEMA_ID` supported in ksqlDB 0.24.0 does not work with a complex structure and optional fields. 
The issue is composed of two different behaviors:
 - 1st one: ksqlDB is not able to serialize data to topic if the schema contains a complex structure.
 - 2nd issue: ksqlDB is not able to comprehend / parse optional fields in a complex schema.

**To Reproduce**
1. The version of KSQL. 0.24.0
2. Sample source data, produce this data to a topic (transaction)
```json
{"id": "1", "transaction": { "num_shares": 50000, "amount": 50044568, "txn_ts": "2020-11-18 02:31:43", "customer": { "first_name": "Jill", "last_name": "Smith", "id": 1234567, "email": "jsmith@gmail.com" }, "company": { "name": "ACME Corp", "ticker": "ACMC", "id": "ACME837275222752952", "address": "Anytown USA, 333333"}}}
{"id": "2", "transaction": { "num_shares": 30000, "amount": 5004, "txn_ts": "2020-11-18 02:35:43", "customer": { "first_name": "Art", "last_name": "Vandeley", "id": 8976612, "email": "avendleay@gmail.com" }, "company": { "name": "Imports Corp", "ticker": "IMPC", "id": "IMPC88875222752952", "address": "Anytown USA, 333333"}}}
{"id": "3", "transaction": { "num_shares": 3000000, "amount": 50045, "txn_ts": "2020-11-18 02:36:43", "customer": { "first_name": "John", "last_name": "England", "id": 456321, "email": "je@gmail.com" }, "company": { "name": "Hechinger", "ticker": "HECH", "id": "HECH8333785222752952", "address": "Anytown USA, 333333"}}}
{"id": "4", "transaction": { "num_shares": 10000, "amount": 80044, "txn_ts": "2020-11-18 02:37:43", "customer": { "first_name": "Fred", "last_name": "Pym", "id": 333567, "email": "fjone@gmail.com" }, "company": { "name": "PymTech", "ticker": "PYMT", "id": "PYME837275222714197419202020", "address": "Anytown USA, 333333"}}}
```
3. Register the following schema
```
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
  --data '{"schema": "{\"name\":\"Transaction\",\"type\":\"record\",\"namespace\":\"com.acme.namespace\",\"fields\":[{\"name\":\"eventID\",\"type\":\"string\"},{\"name\":\"transaction\",\"type\":{\"name\":\"transaction\",\"type\":\"record\",\"fields\":[{\"name\":\"num_shares\",\"type\":\"int\"},{\"name\":\"amount\",\"type\":\"int\"},{\"name\":\"customer\",\"type\":{\"name\":\"customer\",\"type\":\"record\",\"fields\":[{\"name\":\"first_name\",\"type\":\"string\"},{\"name\":\"last_name\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"}]}}]}}]}"}' \
  http://localhost:8081/subjects/model-transaction-value/versions
```

4. Run the following statement

```sql
SET 'auto.offset.reset' = 'earliest';

# create the transaction stream
CREATE STREAM TXS (
  `id` VARCHAR,
  `transaction` VARCHAR
) WITH (
     KAFKA_TOPIC = 'transaction'
   , VALUE_FORMAT='JSON'
   , KEY_FORMAT='KAFKA'
);

# Rekey the stream to another topic
CREATE STREAM TXS_REKEY WITH (
    KAFKA_TOPIC='transaction-rekey',
    VALUE_FORMAT='JSON',
    KEY_FORMAT='KAFKA'
)
AS SELECT
`id`, `transaction`
FROM "TXS"
PARTITION BY `id`
EMIT CHANGES;

# model the stream by using an existing schema
CREATE STREAM MODEL_TXS_EVENT WITH  (
    KAFKA_TOPIC='model-transaction',
    KEY_FORMAT='KAFKA',
    VALUE_FORMAT='AVRO',
    VALUE_SCHEMA_ID='1'
)
AS
SELECT
`id`,
as_value(txs.`id`) AS `eventID`,
STRUCT(
    `num_shares` := CAST(EXTRACTJSONFIELD(txs.`transaction`, '$.num_shares') AS INT),
    `amount` := CAST(EXTRACTJSONFIELD(txs.`transaction`, '$.amount') AS INT),
    `customer` := STRUCT(
        `first_name`:= EXTRACTJSONFIELD(txs.`transaction`, '$.customer.first_name'),
        `last_name`:= EXTRACTJSONFIELD(txs.`transaction`, '$.customer.last_name'),
        `email`:= EXTRACTJSONFIELD(txs.`transaction`, '$.customer.email')
    )
) AS `transaction`
FROM TXS_REKEY txs
EMIT CHANGES;

```

**Expected behavior**

1. 1st -> Being able to consume the modeled events in the last stream (MODEL_TXS_EVENT)
2. 2nd -> Run the same queries with another variant of the schema, the schema should contain optional fields.
The optional fields are not parsed as expected, the server will complain about the structure of the schema

```bash
ksql> show streams;

 Stream Name         | Kafka Topic                 | Key Format | Value Format | Windowed
------------------------------------------------------------------------------------------
 KSQL_PROCESSING_LOG | default_ksql_processing_log | KAFKA      | JSON         | false
 MODEL_TXS_EVENT     | model-transaction           | KAFKA      | AVRO         | false
 TXS                 | transaction                 | KAFKA      | JSON         | false
 TXS_REKEY           | transaction-rekey           | KAFKA      | JSON         | false
------------------------------------------------------------------------------------------
ksql> select * from MODEL_TXS_EVENT emit changes;
+----------------------------------------+----------------------------------------+----------------------------------------+
|id                                      |eventID                                 |transaction                             |
+----------------------------------------+----------------------------------------+----------------------------------------+
```

**Actual behaviour**
The streams has been created successfully, but once your start consuming the modeled event you get the following error in ksqldb server.

1st Error:
```
ror encountered sending record to topic model-transaction for task 0_0 due to:
org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: model-transaction. Struct schemas do not match.
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:177)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:139)
        at org.apache.kafka.streams.processor.internals.SinkNode.process(SinkNode.java:85)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:194)
        at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:61)
        at org.apache.kafka.streams.processor.internals.ProcessorAdapter.process(ProcessorAdapter.java:71)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:194)
        at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:61)
        at org.apache.kafka.streams.processor.internals.ProcessorAdapter.process(ProcessorAdapter.java:71)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
        at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:780)
        at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:809)
        at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:780)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:711)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1296)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:800)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:620)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:584)
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: model-transaction. Struct schemas do not match.
        at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:56)
        at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
        at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:186)
        at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:149)
        at io.confluent.ksql.serde.GenericSerializer.serialize(GenericSerializer.java:62)
        at io.confluent.ksql.logging.processing.LoggingSerializer.serialize(LoggingSerializer.java:47)
        at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:157)
        ... 28 more
Caused by: org.apache.kafka.connect.errors.DataException: Struct schemas do not match.
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:249)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
        at io.confluent.ksql.serde.avro.AvroSRSchemaDataTranslator.toConnectRow(AvroSRSchemaDataTranslator.java:56)
        at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:52)
        ... 35 more
[2022-03-22 13:51:29,689] INFO stream-thread [_confluent-ksql-default_query_CSAS_MODEL_TXS_EVENT_65-2a4a55ed-9ebb-4bf3-afb3-bd6d82e8269a-StreamThread-5] Processed 0 total records, ran 0 punctuators, and committed 0 total tasks since the last update (org.apache.kafka.streams.processor.internals.StreamThread:874)
[2022-03-22 13:51:29,804] INFO Retrying request. Retry no: 1 Cause: 'org.apache.kafka.common.errors.GroupNotEmptyException: The group is not empty.' (io.confluent.ksql.util.ExecutorUtil:104)
```

2nd Error:
Try to modify the schema and introduce an optional field in the structure, you will get this kind of errors.

```
The following value columns are changed, missing or reordered: [`transaction` STRUCT<`num_shares` INTEGER, `amount` INTEGER, `customer` STRUCT<`first_name` STRING, `last_name` STRING, `email` STRING>>]. Schema from schema registry is [`eventID` STRING, `transaction` STRUCT<`num_shares` INTEGER, `amount` INTEGER, `customer` STRUCT<`first_name` STRING, `last_name` STRING, `email` STRING>>]
```

### PR DESCRIPTION
**Pull request by bvarghese1**
### Description 
Fixes #8919 
- Logical schema generated by Ksql always contains optional fields.
- The Schema Registry registered Avro schema may or may not contain optional
  fields.
- If the SR schema doesn't contain optional fields for compound data types such
  as array, map, struct then the schema comparison between logical and physical
  schemas fails.
- To fix this, we create a copy of the data using the physical schema thus
  getting rid of any optional fields in the process. Schema type validation is
  done before this step and therefore copying the data using physical schema is
  a safe process.

### Testing done 
Added unit tests
Added QTTs
Added RQTT

Pending - generate historical plans

### CODE REVIEW

File: ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java [hunk 1]
```diff
@@ -38,6 +42,89 @@ public class AvroSRSchemaDataTranslator extends ConnectSRSchemaDataTranslator {
...
+
+    return innerStruct;
+  }
+
+  private void copyDataWithPhysicalSchema(
+      final Struct originalData,
+      final Schema originalSchema,
+      final Struct modifiedData,
+      final Schema schema) {
+    for (final Field field : originalSchema.fields()) {
```
Comment (lihaosky) [inline ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java:110]: QQ: why do we iterate logical schema instead of physical schema. Some fields in physical schema may not appear in logical schema but we want to check if they have defaults or are optional. Basically, what

```
        if (field.schema().defaultValue() != null || field.schema().isOptional()) {
          struct.put(field, field.schema().defaultValue());
        } else {
          throw new KsqlException("Missing default value for required Avro field: [" + field.name()
              + "]. This field appears in Avro schema in Schema Registry");
        }
```
is doing.

**Review by lihaosky — COMMENTED** [review]
Thanks @bvarghese1 for the fix!

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json [hunk 2]
```diff
@@ -1183,6 +1183,90 @@
...
+        {"topic": "transaction", "key": null, "value": {"id": "3", "transaction": {"txn_ts": "2020-11-18 02:36:43", "customer": { "first_name": "John", "last_name": "England", "id": 456321, "email": "je@foo.com" }, "company": { "name": "Hechinger", "ticker": "HECH", "id": "HECH8333785222752952", "address": "Anytown USA, 333333"}}}},
+        {"topic": "transaction", "key": null, "value": {"id": "4", "transaction": {"txn_ts": "2020-11-18 02:37:43", "customer": { "first_name": "Fred", "last_name": "Pym", "id": 333567, "email": "fjone@foo.com" }, "company": { "name": "PymTech", "ticker": "PYMT", "id": "PYME837275222714197419202020", "address": "Anytown USA, 333333"}}}}
+      ],
+      "outputs": [
+        {"topic": "model-transaction", "key": "1", "value": {"eventID": "1", "transaction": {"amount": 0, "num_shares": 0, "customer": {"last_name": "Smith", "first_name": "Jill", "email": "jsmith@foo.com"}}}},
```
Comment (lihaosky) [inline ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1237]: Curious if this amount:0 is from `CAST(EXTRACTJSONFIELD(txs.`transaction`, '$.amount') AS INT)`? Since physical schema and logical schema both have `amount` field, it's not from default value?

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json [hunk 3]
```diff
@@ -1183,6 +1183,90 @@
...
+        {"topic": "transaction", "key": null, "value": {"id": "3", "transaction": {"txn_ts": "2020-11-18 02:36:43", "customer": { "first_name": "John", "last_name": "England", "id": 456321, "email": "je@foo.com" }, "company": { "name": "Hechinger", "ticker": "HECH", "id": "HECH8333785222752952", "address": "Anytown USA, 333333"}}}},
+        {"topic": "transaction", "key": null, "value": {"id": "4", "transaction": {"txn_ts": "2020-11-18 02:37:43", "customer": { "first_name": "Fred", "last_name": "Pym", "id": 333567, "email": "fjone@foo.com" }, "company": { "name": "PymTech", "ticker": "PYMT", "id": "PYME837275222714197419202020", "address": "Anytown USA, 333333"}}}}
+      ],
+      "outputs": [
+        {"topic": "model-transaction", "key": "1", "value": {"eventID": "1", "transaction": {"amount": null, "num_shares": null, "customer": {"last_name": "Smith", "first_name": "Jill", "email": "jsmith@foo.com"}}}},
```
Comment (lihaosky) [inline ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1265]: Curious if this amount:null is from `CAST(EXTRACTJSONFIELD(txs.`transaction`, '$.amount') AS INT)`? Since physical schema and logical schema both have `amount` field, it's not from default value?

Should there be a test case where logical schema doesn't have `amount` and physical schema have it, then output have `amount` equal to physical schema default or optional value?

**Review by lihaosky — COMMENTED** [review]
Thanks @bvarghese1 for the fix! Looks good overall except a few questions.

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json (hunk 2 above)
Comment (bvarghese1) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1237]: No, I tried with different default values and finally set it as 0 for the test.

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json (hunk 3 above)
Comment (bvarghese1) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1265]: I think that leads to a different exception - schema mismatch exception

File: ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java [hunk 4]
```diff
@@ -53,22 +149,12 @@ public Object toConnectRow(final Object ksqlData) {
       );
       originalData = ConnectSchemas.withCompatibleRowSchema(originalData, originalSchema);
     }
+
     validate(originalSchema, schema);
```
[the remark this answers is not in the document]
Comment (bvarghese1) [reply ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java:153]: Yeah, just checked the validation code doesn't check the fields recursively!

File: ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java [hunk 5]
```diff
@@ -38,11 +42,103 @@ public class AvroSRSchemaDataTranslator extends ConnectSRSchemaDataTranslator {
...
+      struct.put(field, field.schema().defaultValue());
+    } else {
+      throw new KsqlException("Missing default value for required Avro field: [" + field.name()
+          + "]. This field appears in Avro schema in Schema Registry");
+    }
+  }
+
   @Override
   public Object toConnectRow(final Object ksqlData) {
     if (!(ksqlData instanceof Struct)) {
```
[the remark this answers is not in the document]
Comment (bvarghese1) [reply ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java:138]: Unsure about this. Will need to experiment. Should we create a separate issue to track this?

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json (hunk 2 above)
Comment (lihaosky) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1237]: Is it because `CAST(EXTRACTJSONFIELD(txs.transaction, '$.amount') AS INT` is `null` so the default value is picked? I'm trying to understand why it used default value since the `amount` field is in both schemas and `addDefaultValueOrThrowException` won't be hit

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json (hunk 3 above)
Comment (lihaosky) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1265]: > Should there be a test case where logical schema doesn't have amount and physical schema have it, then output have amount equal to physical schema default or optional value?

Do you mean this will lead to schema mismatch exception? This will be where `addDefaultValueOrThrowException` is called I guess?

File: ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (lihaosky) [reply ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java:138]: Sounds good

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json [hunk 6]
```diff
@@ -1183,6 +1183,118 @@
...
+        {"topic": "model-transaction", "key": "2", "value": {"eventID": "2", "transaction": {"amount": null, "num_shares": null, "customer": {"last_name": "Vandeley", "first_name": "Art", "email": "avendleay@foo.com"}}}},
+        {"topic": "model-transaction", "key": "3", "value": {"eventID": "3", "transaction": {"amount": null, "num_shares": null, "customer": {"last_name": "England", "first_name": "John", "email": "je@foo.com"}}}},
+        {"topic": "model-transaction", "key": "4", "value": {"eventID": "4", "transaction": {"amount": null, "num_shares": null, "customer": {"last_name": "Pym", "first_name": "Fred", "email": "fjone@foo.com"}}}}
+      ]
+    },
+    {
+      "name": "VALUE_SCHEMA_ID with compound types and default value in the end of schema",
```
Comment (bvarghese1) [inline ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1272]: @lihaosky added this test which tests https://github.com/confluentinc/ksql/pull/9575/files#diff-07daa80e9e013e949f189df69d12f918b084b5a1e821075b03a90a91321d569eR127

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json (hunk 3 above)
Comment (bvarghese1) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1265]: Added a test as suggested

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json (hunk 2 above)
Comment (bvarghese1) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1237]: Added a test to cover addDefaultValueOrThrowException method

File: ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (bvarghese1) [reply ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java:153]: As discussed, we wont be implementing validation recursively, since we decided to keep it only for the root fields. Avro schemas are validated anyways recursively in the copy method

**Review by lihaosky — APPROVED** [review]
lgtm

File: ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json (hunk 6 above)
Comment (lihaosky) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1272]: Thanks. LGTM! Please check the build failure before merge

Comment (bvarghese1) [reply ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json:1272]: Done

**Comment by AndreasFischbach3003** [comment]
Hi, is this fix available in an release already?

**Comment by bvarghese1** [comment]
Hi @AndreasFischbach3003, this fix will be available in 0.30 release which is scheduled for next year.

**Comment by vcrfxia** [comment]
Update: this fix will now be included in the 0.29 release, instead of 0.30. (An original 0.29 release was cut earlier without this fix, but it has recently been recut and therefore this fix is now in 0.29 rather than needing to wait for 0.30.)
